Repository umbraco/Umbraco.CMS.Backoffice, pull requests merged in 2024-10, with the labels that each got.

#2387 Bugfix: TinyMCE toolbar config layout
  src/packages/rte/tiny-mce/property-editors/tiny-mce/manifests.ts
  src/packages/rte/tiny-mce/property-editors/toolbar/property-editor-ui-tiny-mce-toolbar-configuration.element.ts
Labels: type/bug, release/15.0.0

#2389 Extension Manifest Map: Entity Actions
  src/packages/core/components/entity-actions-bundle/entity-actions-bundle.element.ts
  src/packages/core/entity-action/common/delete/delete.action.ts
  src/packages/core/entity-action/common/delete/types.ts
  src/packages/core/entity-action/common/duplicate/duplicate.action.ts
  src/packages/core/entity-action/default/entity-action.element.ts
  src/packages/core/entity-action/default/index.ts
  src/packages/core/entity-action/default/types.ts
  src/packages/core/entity-action/entity-action-list.element.ts
  src/packages/core/entity-action/entity-action.extension.ts
  src/packages/core/entity-action/index.ts
  src/packages/core/extension-registry/extensions/entity-action.extension.ts
  src/packages/core/extension-registry/extensions/index.ts
  src/packages/core/recycle-bin/entity-action/empty-recycle-bin/empty-recycle-bin.action.ts
  src/packages/core/recycle-bin/entity-action/empty-recycle-bin/index.ts
  src/packages/core/recycle-bin/entity-action/empty-recycle-bin/types.ts
  src/packages/core/recycle-bin/entity-action/index.ts
  src/packages/core/recycle-bin/entity-action/restore-from-recycle-bin/index.ts
  src/packages/core/recycle-bin/entity-action/restore-from-recycle-bin/restore-from-recycle-bin.action.ts
  src/packages/core/recycle-bin/entity-action/restore-from-recycle-bin/types.ts
  src/packages/core/recycle-bin/entity-action/trash/index.ts
  src/packages/core/recycle-bin/entity-action/trash/trash.action.ts
  src/packages/core/recycle-bin/entity-action/trash/types.ts
  src/packages/core/recycle-bin/index.ts
  src/packages/core/server-file-system/rename/rename-server-file.action.ts
  src/packages/core/server-file-system/rename/types.ts
  src/packages/core/tree/entity-actions/duplicate-to/duplicate-to.action.ts
  src/packages/core/tree/entity-actions/duplicate-to/types.ts
  src/packages/core/tree/entity-actions/move/index.ts
  src/packages/core/tree/entity-actions/move/move-to.action.ts
  src/packages/core/tree/entity-actions/move/types.ts
  src/packages/core/tree/entity-actions/reload-tree-item-children/reload-tree-item-children.action.ts
  src/packages/core/tree/entity-actions/reload-tree-item-children/types.ts
  src/packages/core/tree/entity-actions/sort-children-of/index.ts
  src/packages/core/tree/entity-actions/sort-children-of/sort-children-of.action.ts
  src/packages/core/tree/entity-actions/sort-children-of/types.ts
  src/packages/core/tree/folder/entity-action/create-folder/create-folder.action.ts
  src/packages/core/tree/folder/entity-action/create-folder/index.ts
  src/packages/core/tree/folder/entity-action/create-folder/types.ts
  src/packages/core/tree/folder/entity-action/delete-folder/delete-folder.action.ts
  src/packages/core/tree/folder/entity-action/delete-folder/index.ts
  src/packages/core/tree/folder/entity-action/delete-folder/types.ts
  src/packages/core/tree/folder/entity-action/index.ts
  src/packages/core/tree/folder/entity-action/update-folder/index.ts
  src/packages/core/tree/folder/entity-action/update-folder/types.ts
  src/packages/core/tree/folder/entity-action/update-folder/update-folder.action.ts
  src/packages/core/tree/folder/types.ts
  src/packages/documents/documents/entity-actions/notifications/manifests.ts
  src/packages/user/user/entity-actions/manifests.ts
Labels: category/breaking, release/15.0.0

#2390 Bugfix: Tiptap toolbar, ensure component exists
  src/packages/rte/tiptap/components/input-tiptap/tiptap-fixed-menu.element.ts
Labels: ignore-for-release

#2391 Tiptap: Renamed "umb-tiptap-fixed-menu" to "umb-tiptap-toolbar"
  src/packages/tiptap/components/input-tiptap/input-tiptap.element.ts
  src/packages/tiptap/components/input-tiptap/tiptap-toolbar.element.ts
Labels: ignore-for-release

#2393 Tiptap: Validates toolbar configuration value
  src/packages/tiptap/property-editors/tiptap/components/property-editor-ui-tiptap-toolbar-configuration.element.ts
Labels: type/bug, release/15.1.0

#2399 V15: Hotfix: Create dictionary collection action wrong path
  src/packages/dictionary/collection/action/manifests.ts
  src/packages/translation/menu/manifests.ts
Labels: type/bug, ignore-for-release, release/15.0.0

#2400 V15 Hotfix: Media previews are not shown for anything other than images
  src/packages/media/media/components/input-upload-field/input-upload-field.element.ts
Labels: type/bug, ignore-for-release

#2406 Added arabic language
  src/assets/lang/ar.ts
  src/packages/core/localization/manifests.ts
Labels: release/15.0.0

#2403 Chore: Add unit tests for math functions
  src/packages/core/utils/math/calculate-extrapolated-value.test.ts
  src/packages/core/utils/math/clamp.test.ts
  src/packages/core/utils/math/distance.test.ts
  src/packages/core/utils/math/get-accumulated-value-of-index.test.ts
  src/packages/core/utils/math/get-interpolated-index-of-position-in-weight-map.test.ts
  src/packages/core/utils/math/inverse-lerp.test.ts
  src/packages/core/utils/math/is-within-rect.test.ts
  src/packages/core/utils/math/lerp.test.ts
Labels: ignore-for-release

#2402 Chore: Add unit tests for the state manager
  src/packages/core/utils/state-manager/state.manager.test.ts
Labels: ignore-for-release

#2404 Chore: Add unit tests for the debounce function
  src/packages/core/utils/debounce/debounce.function.test.ts
Labels: ignore-for-release

#2408 Feature: Handle mandatory languages in publish'ish dialogs
  .vscode/settings.json
  src/packages/documents/documents/modals/publish-modal/document-publish-modal.element.ts
  src/packages/documents/documents/modals/publish-with-descendants-modal/document-publish-with-descendants-modal.element.ts
  src/packages/documents/documents/modals/schedule-modal/document-schedule-modal.element.ts
  src/packages/documents/documents/modals/shared/document-variant-language-picker.element.ts
  src/packages/documents/documents/modals/unpublish-modal/document-unpublish-modal.element.ts
  src/packages/documents/documents/modals/utils.ts
  src/packages/documents/documents/workspace/document-workspace.context.ts
Labels: release/15.1.0

#2407 Added more padding/gap in context menu, #16696
  src/packages/core/section/section-sidebar-context-menu/section-sidebar-context-menu.element.ts
Labels: community/pr, type/bug, hacktoberfest-accepted, hacktoberfest/contrib-2024, release/15.1.0

#2405 Chore: Add unit tests for string functions
  src/packages/core/utils/index.ts
  src/packages/core/utils/path/path-folder-name.function.ts
  src/packages/core/utils/string/from-camel-case/from-camel-case.function.test.ts
  src/packages/core/utils/string/from-camel-case/from-camel-case.function.ts
  src/packages/core/utils/string/from-camel-case/index.ts
  src/packages/core/utils/string/generate-umbraco-alias.function.ts
  src/packages/core/utils/string/generate-umbraco-alias/generate-umbraco-alias.function.ts
  src/packages/core/utils/string/generate-umbraco-alias/index.ts
  src/packages/core/utils/string/increment-string.function.ts
  src/packages/core/utils/string/increment-string/increment-string.function.test.ts
  src/packages/core/utils/string/increment-string/increment-string.function.ts
  src/packages/core/utils/string/increment-string/index.ts
  src/packages/core/utils/string/index.ts
  src/packages/core/utils/string/split-string-to-array/index.ts
  src/packages/core/utils/string/split-string-to-array/split-string-to-array.function.test.ts
  src/packages/core/utils/string/split-string-to-array/split-string-to-array.function.ts
  src/packages/core/utils/string/string-or-string-array-contains.function.ts
  src/packages/core/utils/string/string-or-string-array-contains/index.ts
  src/packages/core/utils/string/string-or-string-array-contains/string-or-string-array-contains.function.test.ts
  src/packages/core/utils/string/string-or-string-array-contains/string-or-string-array-contains.function.ts
  src/packages/core/utils/string/to-camel-case/index.ts
Labels: ignore-for-release

#2411 Chore: Property Type Clean up
  src/packages/block/block/workspace/block-element-manager.ts
  src/packages/core/content-type/components/property-type-based-property/property-type-based-property.element.ts
  src/packages/core/property/property/property.context.ts
  src/packages/core/property/property/property.element.ts
Labels: release/15.1.0

#2414 Tweak Arabic translations
  src/assets/lang/ar.ts
Labels: community/pr, type/bug, hacktoberfest-accepted, hacktoberfest/contrib-2024

#2413 style: increase z-index of element in installer layout
  src/apps/installer/shared/layout/installer-layout.element.ts
Labels: community/pr, type/bug, hacktoberfest-accepted, hacktoberfest/contrib-2024, release/15.1.0

#2420 V14: Add sanitization to dictionary
  src/assets/lang/bs.ts
  src/assets/lang/cs-cz.ts
  src/assets/lang/cy-gb.ts
  src/assets/lang/da-dk.ts
  src/assets/lang/de-de.ts
  src/assets/lang/en-us.ts
  src/assets/lang/en.ts
  src/assets/lang/es-es.ts
  src/assets/lang/fr-fr.ts
  src/assets/lang/he-il.ts
  src/assets/lang/hr-hr.ts
  src/assets/lang/it-it.ts
  src/assets/lang/ja-jp.ts
  src/assets/lang/ko-kr.ts
  src/assets/lang/nb-no.ts
  src/assets/lang/nl-nl.ts
  src/assets/lang/pl-pl.ts
  src/assets/lang/pt-br.ts
  src/assets/lang/ru-ru.ts
  src/assets/lang/tr-tr.ts
  src/assets/lang/uk-ua.ts
  src/assets/lang/zh-cn.ts
  src/assets/lang/zh-tw.ts
  src/packages/core/utils/index.ts
  src/packages/core/utils/sanitize/sanitize-html.function.ts
  src/packages/dictionary/workspace/views/workspace-view-dictionary-editor.element.ts
  src/packages/markdown-editor/components/input-markdown-editor/input-markdown.element.ts
Labels: type/bug, release/14.3.1

#2419 Feature: Adds the missing dictionary to search
  src/packages/dictionary/manifests.ts
  src/packages/dictionary/search/constants.ts
  src/packages/dictionary/search/dictionary-search.repository.ts
  src/packages/dictionary/search/dictionary-search.server.data-source.ts
  src/packages/dictionary/search/dictionary.search-provider.ts
  src/packages/dictionary/search/index.ts
  src/packages/dictionary/search/manifests.ts
Labels: type/feature, release/15.1.0

#2422 V15: Ensure all localization variables are present in the default language
  src/assets/lang/en-us.ts
  src/assets/lang/en.ts
Labels: type/bug

#2116 V15: Upload folders in dropzone
  src/packages/documents/document-types/entity-actions/import/modal/document-type-import-modal.element.ts
  src/packages/media/media-types/entity-actions/import/modal/media-type-import-modal.element.ts
  src/packages/media/media-types/repository/structure/media-type-structure.repository.ts
  src/packages/media/media-types/repository/structure/media-type-structure.server.data-source.ts
  src/packages/media/media-types/utils.ts/index.ts
  src/packages/media/media/collection/media-collection.element.ts
  src/packages/media/media/components/input-rich-media/input-rich-media.element.ts
  src/packages/media/media/dropzone/dropzone-manager.class.ts
  src/packages/media/media/dropzone/dropzone.element.ts
  src/packages/media/media/dropzone/types.ts
  src/packages/media/media/modals/media-picker/media-picker-modal.element.ts
Labels: type/feature, release/15.1.0

#2429 Bugfix: Allow/disallow multiple files for dropzone
  src/packages/media/media/collection/media-collection.element.ts
  src/packages/media/media/components/input-rich-media/input-rich-media.element.ts
  src/packages/media/media/dropzone/dropzone.element.ts
  src/packages/media/media/modals/media-picker/media-picker-modal.element.ts
Labels: community/pr, type/bug, release/15.1.0

#2421 Hotfix: Block inline editing — create block variant
  src/assets/lang/da-dk.ts
  src/assets/lang/en-us.ts
  src/assets/lang/en.ts
  src/packages/block/block-list/context/block-list-entries.context.ts
  src/packages/block/block/context/block-entry.context.ts
  src/packages/block/block/context/block-manager.context.ts
  src/packages/block/block/workspace/block-workspace.context.ts
  src/packages/block/block/workspace/views/edit/block-workspace-view-edit-content-no-router.element.ts
  src/packages/core/content-type/structure/content-type-structure-manager.class.ts
  src/packages/documents/documents/workspace/document-workspace.context.ts
Labels: release/15.0.0

#2417 Hotfix: Align templating icons
  src/packages/core/icon-registry/icon-dictionary.json
  src/packages/core/icon-registry/icons.ts
  src/packages/core/icon-registry/icons/icon-document-3d.ts
  src/packages/core/icon-registry/icons/icon-document-chart-bar.ts
  src/packages/core/icon-registry/icons/icon-document-chart-graph.ts
  src/packages/core/icon-registry/icons/icon-document-command.ts
  src/packages/core/icon-registry/icons/icon-document-font.ts
  src/packages/core/icon-registry/icons/icon-document-html.ts
  src/packages/core/icon-registry/icons/icon-document-image.ts
  src/packages/core/icon-registry/icons/icon-document-js.ts
  src/packages/core/icon-registry/icons/icon-document-key.ts
  src/packages/core/icon-registry/icons/icon-document-medal.ts
  src/packages/core/icon-registry/icons/icon-document-play.ts
  src/packages/core/icon-registry/icons/icon-document-search.ts
  src/packages/core/icon-registry/icons/icon-document-settings.ts
  src/packages/core/icon-registry/icons/icon-document-spreadsheet.ts
  src/packages/core/icon-registry/icons/icon-document-user.ts
  src/packages/documents/document-types/entity-actions/create/modal/document-type-create-options-modal.element.ts
  src/packages/documents/document-types/workspace/document-type-workspace.context.ts
  src/packages/documents/documents/workspace/views/info/document-workspace-view-info.element.ts
  src/packages/packages/package-builder/workspace/workspace-package-builder.element.ts
  src/packages/templating/partial-views/entity-actions/create/options-modal/partial-view-create-options-modal.element.ts
  src/packages/templating/partial-views/entity-actions/create/snippet-modal/create-from-snippet-modal.ts
  src/packages/templating/partial-views/tree/partial-view-tree.server.data-source.ts
  src/packages/templating/scripts/entity-actions/create/options-modal/script-create-options-modal.element.ts
  src/packages/templating/scripts/tree/script-tree.server.data-source.ts
  src/packages/templating/stylesheets/entity-actions/create/options-modal/stylesheet-create-options-modal.element.ts
  src/packages/templating/stylesheets/tree/stylesheet-tree.server.data-source.ts
  src/packages/templating/templates/global-components/template-card/template-card.element.ts
  src/packages/templating/templates/tree/template-tree.server.data-source.ts
Labels: type/bug, release/15.0.0

#2418 Hotfix: Invariant preview url
  src/packages/documents/documents/workspace/document-workspace.context.ts
Labels: type/bug, release/15.0.0

#2409 V15/feature/use uui ref href for document type input
  src/packages/documents/document-types/components/input-document-type/input-document-type.element.ts
Labels: release/15.1.0

#2423 Feature: UFM as string
  src/libs/controller-api/controller-host.mixin.ts
  src/packages/block/block/context/block-entry.context.ts
  src/packages/ufm/components/ufm-render/ufm-render.element.ts
  src/packages/ufm/controllers/ufm-virtual-render.controller.ts
  src/packages/ufm/index.ts
  src/packages/ufm/types.ts
Labels: type/feature, release/15.1.0

#2437 build(deps): update @umbraco-ui/uui from 1.10.0 to 1.10.1
  package-lock.json
  package.json
Labels: dependencies, release/15.0.0, release/15.0.0-rc2

#2442 Hotfix: Expose global types
  devops/build/global-types.js
  devops/importmap/index.js
  devops/utils/index.js
  package.json
Labels: type/feature, release/15.0.0-rc2

#2424 Fix: Block Editors — use create labels and hide 'edit'-action if no properties
  src/packages/block/block-custom-view/types.ts
  src/packages/block/block-grid/components/block-grid-block-inline/block-grid-block-inline.element.ts
  src/packages/block/block-grid/components/block-grid-block/block-grid-block.element.ts
  src/packages/block/block-grid/components/block-grid-entries/block-grid-entries.element.ts
  src/packages/block/block-grid/components/block-grid-entry/block-grid-entry.element.ts
  src/packages/block/block-grid/context/block-grid-entries.context.ts
  src/packages/block/block-grid/context/block-grid-entry.context.ts
  src/packages/block/block-grid/context/block-grid-manager.context.ts
  src/packages/block/block-grid/property-editors/block-grid-editor/property-editor-ui-block-grid.element.ts
  src/packages/block/block-grid/types.ts
  src/packages/block/block-list/components/block-list-entry/block-list-entry.element.ts
  src/packages/block/block-list/context/block-list-entry.context.ts
  src/packages/block/block-rte/components/block-rte-entry/block-rte-entry.element.ts
  src/packages/block/block-rte/context/block-rte-entry.context.ts
  src/packages/block/block/context/block-entry.context.ts
  src/packages/block/block/context/block-manager.context.ts
Labels: type/bug, release/15.0.0, release/15.0.0-rc2

#2435 Make Grid List Create Button Respect the Translation of a document type
  src/libs/localization-api/localization.controller.test.ts
  src/libs/localization-api/localization.controller.ts
  src/packages/block/block-grid/components/block-grid-entries/block-grid-entries.element.ts
  src/packages/block/block-list/property-editors/block-list-editor/property-editor-ui-block-list.element.ts
  src/packages/block/block-type/components/block-type-card/block-type-card.element.ts
  src/packages/block/block/workspace/block-workspace-editor.element.ts
  src/packages/block/block/workspace/views/edit/block-workspace-view-edit.element.ts
  src/packages/core/tree/tree-picker-modal/tree-picker-modal.element.ts
Labels: community/pr, type/bug, hacktoberfest-accepted, hacktoberfest/contrib-2024, release/15.1.0

#2431 Feature: Readonly Block Grid Property Editor UI
  src/packages/block/block-grid/components/block-grid-entries/block-grid-entries.element.ts
  src/packages/block/block-grid/components/block-grid-entry/block-grid-entry.element.ts
  src/packages/block/block-grid/property-editors/block-grid-editor/manifests.ts
  src/packages/block/block-grid/property-editors/block-grid-editor/property-editor-ui-block-grid.element.ts
  src/packages/block/block-list/components/block-list-entry/block-list-entry.element.ts
  src/packages/block/block-list/property-editors/block-list-editor/property-editor-ui-block-list.element.ts
  src/packages/block/block/context/block-entry.context.ts
  src/packages/block/block/context/block-manager.context.ts
  src/packages/block/block/workspace/block-workspace.context.ts
  src/packages/core/utils/state-manager/read-only-state.manager.ts
  src/packages/core/utils/state-manager/read-only-variant-state.manager.ts
Labels: type/feature, release/15.1.0

#2438 Pass workspace path to document type edit path
  src/packages/documents/document-types/paths.ts
Labels: type/bug, release/15.0.0-rc2

#2410 Feature: Select all variants option in publishing dialogs
  src/assets/lang/bs.ts
  src/assets/lang/cs-cz.ts
  src/assets/lang/cy-gb.ts
  src/assets/lang/da-dk.ts
  src/assets/lang/de-de.ts
  src/assets/lang/en-us.ts
  src/assets/lang/en.ts
  src/assets/lang/es-es.ts
  src/assets/lang/fr-fr.ts
  src/assets/lang/he-il.ts
  src/assets/lang/hr-hr.ts
  src/assets/lang/it-it.ts
  src/assets/lang/ja-jp.ts
  src/assets/lang/ko-kr.ts
  src/assets/lang/nb-no.ts
  src/assets/lang/nl-nl.ts
  src/assets/lang/pl-pl.ts
  src/assets/lang/pt-br.ts
  src/assets/lang/ru-ru.ts
  src/assets/lang/sv-se.ts
  src/assets/lang/tr-tr.ts
  src/assets/lang/uk-ua.ts
  src/assets/lang/zh-cn.ts
  src/assets/lang/zh-tw.ts
  src/packages/core/utils/selection-manager/selection.manager.test.ts
  src/packages/core/utils/selection-manager/selection.manager.ts
  src/packages/documents/documents/modals/save-modal/document-save-modal.element.ts
  src/packages/documents/documents/modals/schedule-modal/document-schedule-modal.element.ts
  src/packages/documents/documents/modals/shared/document-variant-language-picker.element.ts
  src/packages/log-viewer/workspace/views/search/components/log-viewer-log-level-filter-menu.element.ts
Labels: type/feature, release/15.1.0

#2452 Update Collection view's instruction text to match current Backoffice terminology
  src/packages/property-editors/collection/manifests.ts
Labels: type/bug

#2453 Dependencies: Update @umbraco-ui/uui to 1.11.0
  package-lock.json
  package.json
Labels: dependencies, release/15.0.0, release/15.0.0-rc2

#2451 Adds read-only mode to Color Picker Property Editor
  src/packages/core/components/input-color/input-color.element.ts
  src/packages/property-editors/color-picker/manifests.ts
  src/packages/property-editors/color-picker/property-editor-ui-color-picker.element.ts
Labels: community/pr, type/feature, hacktoberfest-accepted, hacktoberfest/contrib-2024, release/15.1.0

#2455 Bugfix: Set ?readonly only on color swatches, and not on the individual swatch
  src/packages/core/components/input-color/input-color.element.ts
Labels: type/bug, ignore-for-release

#2456 Fixes icon alignment in links in redirect dashboard
  src/packages/documents/document-redirect-management/dashboard-redirect-management.element.ts
Labels: community/pr, type/bug, hacktoberfest-accepted, hacktoberfest/contrib-2024, release/15.1.0

#2457 Adds gap between grouped buttons in settings welcome dashboard
  src/packages/settings/welcome/settings-welcome-dashboard.element.ts
Labels: community/pr, type/bug, hacktoberfest-accepted, hacktoberfest/contrib-2024, release/15.1.0

#2462 Bugfix: TinyMCE anchor links without base URL
  src/packages/multi-url-picker/tiny-mce-plugin/tiny-mce-multi-url-picker.plugin.ts
  src/packages/tiny-mce/plugins/tiny-mce-code-editor.plugin.ts
Labels: type/bug, release/15.1.0, release/15.0.0-rc2

#1021 Adjust Image Cropper handle (focal point)
  src/packages/media/media/components/input-image-cropper/crop-change.event.ts
  src/packages/media/media/components/input-image-cropper/focalpoint-change.event.ts
  src/packages/media/media/components/input-image-cropper/image-cropper-field.element.ts
  src/packages/media/media/components/input-image-cropper/image-cropper-focus-setter.element.ts
  src/packages/media/media/components/input-image-cropper/image-cropper.element.ts
  src/packages/media/media/components/input-image-cropper/index.ts
Labels: community/pr, type/feature, release/15.1.0

#2465 Tiptap: allow images to be uploaded from the clipboard
  src/packages/core/temporary-file/temporary-file-manager.class.ts
  src/packages/tiptap/extensions/core/media-upload.extension.ts
Labels: type/bug, release/15.0.0-rc2

#2464 Bugfix: Variant Blocks create duplicates in the frontend when created in an area
  src/packages/block/block-grid/context/block-grid-manager.context.ts
  src/packages/block/block-list/context/block-list-entries.context.ts
  src/packages/block/block-list/context/block-list-manager.context.ts
  src/packages/block/block-rte/context/block-rte-entries.context.ts
  src/packages/block/block-rte/context/block-rte-manager.context.ts
  src/packages/block/block/context/block-manager.context.ts
  src/packages/block/block/workspace/block-workspace.context.ts
Labels: type/bug, release/15.0.0-rc2

#2461 Removes unnecessary margin in ufm-render-element
  src/packages/ufm/components/ufm-render/ufm-render.element.ts
Labels: community/pr, type/bug, hacktoberfest-accepted, hacktoberfest/contrib-2024

#2468 use server paths for preview url construction
  src/packages/documents/documents/workspace/document-workspace.context.ts
Labels: type/bug, release/15.0.0-rc2

#2467 Feature: Collection Toolbar Filter Field
  src/packages/core/collection/components/collection-action-bundle.element.ts
  src/packages/core/collection/components/collection-filter-field.element.ts
  src/packages/core/collection/components/collection-view-bundle.element.ts
  src/packages/core/collection/components/index.ts
  src/packages/dictionary/collection/dictionary-collection.element.ts
  src/packages/documents/documents/collection/document-collection-toolbar.element.ts
  src/packages/documents/documents/collection/document-collection.element.ts
  src/packages/extension-insights/collection/extension-collection.element.ts
  src/packages/media/media/collection/media-collection-toolbar.element.ts
  src/packages/media/media/collection/media-collection.element.ts
  src/packages/members/member/collection/member-collection-header.element.ts
  src/packages/members/member/collection/member-collection.element.ts
  src/packages/relations/relation-types/collection/relation-type-collection.element.ts
  src/packages/user/user-group/collection/user-group-collection-header.element.ts
  src/packages/user/user-group/collection/user-group-collection.element.ts
  src/packages/user/user/collection/user-collection-header.element.ts
  src/packages/user/user/collection/user-collection.element.ts
Labels: type/feature, release/15.1.0

#2469 Bugfix: Tiptap RTE custom dimensions configuration
  src/packages/tiptap/components/input-tiptap/input-tiptap.element.ts
Labels: community/pr, type/bug, hacktoberfest-accepted, hacktoberfest/contrib-2024, release/15.1.0

#2478 Hotfix: document variant publication info
  src/packages/documents/documents/property-dataset-context/index.ts
  src/packages/documents/documents/workspace/views/info/document-workspace-view-info.element.ts
Labels: type/bug, release/15.0.0-rc3

#2477 Feature: Link Picker modal refactor
  src/assets/lang/ar.ts
  src/assets/lang/bs.ts
  src/assets/lang/cs-cz.ts
  src/assets/lang/cy-gb.ts
  src/assets/lang/da-dk.ts
  src/assets/lang/de-de.ts
  src/assets/lang/en-us.ts
  src/assets/lang/en.ts
  src/assets/lang/fr-fr.ts
  src/assets/lang/he-il.ts
  src/assets/lang/hr-hr.ts
  src/assets/lang/it-it.ts
  src/assets/lang/ja-jp.ts
  src/assets/lang/ko-kr.ts
  src/assets/lang/nb-no.ts
  src/assets/lang/nl-nl.ts
  src/assets/lang/pl-pl.ts
  src/assets/lang/pt-br.ts
  src/assets/lang/ru-ru.ts
  src/assets/lang/sv-se.ts
  src/assets/lang/tr-tr.ts
  src/assets/lang/uk-ua.ts
  src/assets/lang/zh-cn.ts
  src/assets/lang/zh-tw.ts
  src/packages/documents/documents/components/input-document/input-document.element.ts
  src/packages/documents/documents/repository/detail/document-detail.server.data-source.ts
  src/packages/documents/documents/types.ts
  src/packages/media/media/components/input-media/input-media.element.ts
  src/packages/media/media/repository/detail/media-detail.server.data-source.ts
  src/packages/media/media/types.ts
  src/packages/multi-url-picker/components/input-multi-url/input-multi-url.element.ts
  src/packages/multi-url-picker/link-picker-modal/link-picker-modal.element.ts
  src/packages/multi-url-picker/link-picker-modal/link-picker-modal.token.ts
Labels: type/feature, type/bug, release/15.1.0

#2481 Workaround: Ignore discard changes when in a workspace modal
  src/packages/core/workspace/entity-detail/entity-detail-workspace-base.ts
Labels: type/bug, release/15.0.0-rc3

#2482 Bugfix: Allow breadcrumb for variant root items
  src/packages/core/menu/menu-variant-tree-structure-workspace-context-base.ts
Labels: type/bug, release/15.0.0-rc3

#2475 Feature: save selected app language in local storage
  src/packages/language/global-contexts/app-language.context.ts
Labels: type/feature, release/15.1.0

#2474 Feature: Add read only tag for read only languages in app language select
  src/assets/lang/da-dk.ts
  src/assets/lang/en-us.ts
  src/assets/lang/en.ts
  src/packages/core/workspace/components/workspace-split-view/workspace-split-view-variant-selector.element.ts
  src/packages/language/app-language-select/app-language-select.element.ts
  src/packages/language/global-contexts/app-language.context.ts
Labels: type/feature, release/15.1.0

#2479 Bugfix: Prevent delete a template when has children
  src/packages/templating/templates/conditions/allow-delete/const.ts
  src/packages/templating/templates/conditions/allow-delete/manifest.ts
  src/packages/templating/templates/conditions/allow-delete/template-allow-delete-action.condition.ts
  src/packages/templating/templates/conditions/manifests.ts
  src/packages/templating/templates/entity-actions/manifests.ts
  src/packages/templating/templates/manifests.ts
Labels: type/bug, release/15.0.0-rc3

#2489 Tags matchlist on top of following markdown toolbar
  src/packages/tags/components/tags-input/tags-input.element.ts
Labels: type/bug, release/15.0.0-rc3

#2484 Bugfix: Hide template input when there are no allowed templates
  src/packages/documents/documents/workspace/views/info/document-workspace-view-info.element.ts
Labels: type/bug, release/15.0.0-rc3

#2486 Hotfix: Publish with decendants structure reload
  src/packages/documents/documents/entity-actions/unpublish.action.ts
  src/packages/documents/documents/tree/tree-item/document-tree-item.element.ts
  src/packages/documents/documents/workspace/document-workspace.context.ts
Labels: type/bug, release/15.0.0-rc3

#2487 Hotfix: Correct user enable notification
  src/packages/user/user/repository/disable/disable-user.repository.ts
  src/packages/user/user/repository/enable/enable-user.repository.ts
Labels: type/bug, release/15.0.0-rc3

#2471 Content type group sorting placeholder
  src/packages/core/content-type/workspace/views/design/content-type-design-editor-group.element.ts
Labels: community/pr, type/bug, release/15.0.0-rc3

#2491 Bugfix: Detail repository base `save()` returns updated model
  src/packages/core/repository/detail/detail-repository-base.ts
Labels: type/bug, release/15.0.0-rc3

#2494 Feature: Tiptap "Clear Formatting" toolbar action
  src/packages/core/icon-registry/icon-dictionary.json
  src/packages/core/icon-registry/icons.ts
  src/packages/core/icon-registry/icons/icon-clear-formatting.ts
  src/packages/tiptap/extensions/manifests.ts
  src/packages/tiptap/extensions/toolbar/clear-formatting.extension.ts
Labels: type/feature, release/15.1.0

#2495 Cosmetic: Tiptap toolbar, background color + box shadow
  src/packages/tiptap/components/input-tiptap/tiptap-toolbar.element.ts
Labels: type/feature, release/15.1.0

#2492 Feature: Document Workspace Info reload components
  src/packages/core/components/history/history-item.element.ts
  src/packages/documents/documents/repository/index.ts
  src/packages/documents/documents/repository/manifests.ts
  src/packages/documents/documents/repository/url/constants.ts
  src/packages/documents/documents/repository/url/document-url.repository.ts
  src/packages/documents/documents/repository/url/document-url.server.data-source.ts
  src/packages/documents/documents/repository/url/document-url.store.context-token.ts
  src/packages/documents/documents/repository/url/document-url.store.ts
  src/packages/documents/documents/repository/url/index.ts
  src/packages/documents/documents/repository/url/manifests.ts
  src/packages/documents/documents/repository/url/types.ts
  src/packages/documents/documents/workspace/views/info/document-workspace-view-info-history.element.ts
  src/packages/documents/documents/workspace/views/info/document-workspace-view-info-links.element.ts
  src/packages/documents/documents/workspace/views/info/document-workspace-view-info-reference.element.ts
  src/packages/documents/documents/workspace/views/info/document-workspace-view-info.element.ts
Labels: type/feature, release/15.1.0

#2496 Bugfix: Word wraps long Data Type names in picker
  src/packages/data-type/modals/data-type-picker-flow/data-type-picker-flow-data-type-picker-modal.element.ts
  src/packages/data-type/modals/data-type-picker-flow/data-type-picker-flow-modal.element.ts
Labels: community/pr, type/bug, hacktoberfest/contrib-2024

#2493 feat: Add validation hints to unnamed tabs
  src/packages/core/content-type/workspace/views/design/content-type-design-editor.element.ts
Labels: community/pr, type/bug, hacktoberfest/contrib-2024

#2498 Feature: Markdown Editor toolbar styling
  src/packages/markdown-editor/components/input-markdown-editor/input-markdown.element.ts
  src/packages/markdown-editor/monaco-markdown-editor-action.extension.ts
  src/packages/multi-url-picker/monaco-markdown-editor-action/manifests.ts
Labels: type/feature, release/15.1.0

#2497 Feature: Document Workspace Info Link State
  src/packages/documents/documents/workspace/views/info/document-workspace-view-info-links.element.ts
Labels: type/feature, release/15.1.0
