Repository umbraco/Umbraco.CMS.Backoffice, pull requests merged in 2024-08, with the labels that each got.

#2151 Bugfix: focus directive refactor to support late case
  src/packages/core/lit-element/directives/focus.lit-directive.ts
  src/packages/core/workspace/components/workspace-split-view/workspace-split-view-variant-selector.element.ts
Labels: type/bug

#2161 refactor composition logic
  src/packages/core/content-type/structure/content-type-container-structure-helper.class.ts
  src/packages/core/content-type/structure/content-type-property-structure-helper.class.ts
  src/packages/core/content-type/structure/content-type-structure-manager.class.ts
Labels: type/bug

#2154 Feature: Document Type reference localizations
  src/assets/lang/en.ts
  src/packages/core/components/input-entity/input-entity.element.ts
  src/packages/core/content-type/modals/composition-picker/composition-picker-modal.element.ts
  src/packages/core/content-type/workspace/views/design/content-type-design-editor.element.ts
  src/packages/core/content/workspace/views/edit/content-editor-tab.element.ts
  src/packages/core/content/workspace/views/edit/content-editor.element.ts
  src/packages/core/modal/common/item-picker/item-picker-modal.element.ts
  src/packages/data-type/workspace/views/info/data-type-workspace-view-info-reference.element.ts
  src/packages/documents/document-types/components/input-document-type/input-document-type.element.ts
  src/packages/documents/documents/entity-actions/create/document-create-options-modal.element.ts
  src/packages/documents/documents/workspace/views/info/document-workspace-view-info.element.ts
  src/packages/media/media-types/components/input-media-type/input-media-type.element.ts
  src/packages/media/media/entity-actions/create/media-create-options-modal.element.ts
  src/packages/members/member-type/components/input-member-type/input-member-type.element.ts
  src/packages/templating/modals/templating-page-field-builder/components/template-field-dropdown-list/template-field-dropdown-list.element.ts
Labels: type/feature, release/14.2.0

#2157 Use constant for language workspace alias
  src/packages/language/workspace/language/constants.ts
  src/packages/language/workspace/language/language-workspace.context.ts
  src/packages/language/workspace/language/manifests.ts
Labels: release/14.2.0

#2160 V14/bugfix/block area config use workspace create
  src/packages/block/block-grid/components/block-grid-area-config-entry/workspace/block-grid-area-type-workspace.context.ts
  src/packages/block/block-grid/property-editors/block-grid-areas-config/property-editor-ui-block-grid-areas-config.element.ts
  src/packages/block/block-type/workspace/block-type-workspace.context.ts
Labels: type/bug, release/14.2.0

#2171 Chore: Make build happy
  examples/block-custom-view/block-custom-view.ts
Labels: ignore-for-release, internal

#2159 Block Grid: Retrieve and render content type name in Area Permission Config
  src/packages/block/block-grid/property-editors/block-grid-area-type-permission/block-grid-area-type-permission.element.ts
Labels: release/14.2.0

#2172 Bugfix: Member workspace, mandatory markers
  src/packages/members/member/workspace/views/member/member-workspace-view-member-info.element.ts
  src/packages/members/member/workspace/views/member/member-workspace-view-member.element.ts
Labels: type/bug

#2176 Chore: Property Type manifest name correction
  src/packages/core/property-type/workspace/manifests.ts
Labels: type/bug, release/14.2.0

#2177 Bugfix: Set trashed context when creating a new item
  src/packages/documents/documents/workspace/document-workspace.context.ts
Labels: type/bug, release/14.2.0

#2182 Chore: Remove property-actions for textbox property-editor
  src/packages/core/property-action/manifests.ts
Labels: release/14.2.0

#2185 Chore: temp solution: move manifest viewer files to the blocks package
  src/packages/block/block-type/components/block-type-custom-view-guide/block-type-custom-view-guide.element.ts
  src/packages/block/manifests.ts
  src/packages/block/modals/manifest-viewer/index.ts
  src/packages/block/modals/manifest-viewer/manifest-viewer-modal.element.ts
  src/packages/block/modals/manifest-viewer/manifest-viewer-modal.token.ts
  src/packages/block/modals/manifest-viewer/manifest.ts
  src/packages/core/extension-registry/index.ts
  src/packages/core/extension-registry/manifests.ts
Labels: ignore-for-release

#2180 Chore: Bundle Models Builder package
  package-lock.json
  package.json
  src/packages/models-builder/package.json
  src/packages/models-builder/vite.config.ts
Labels: release/14.3.0

#2181 Chore: Bundle Search Package
  package-lock.json
  package.json
  src/packages/search/package.json
  src/packages/search/vite.config.ts
Labels: release/14.3.0

#2096 Chore: Circular check with madge
  .madgerc
  package-lock.json
  package.json
Labels: ignore-for-release, internal

#2184 Chore: Bundle Package Management Package
  package-lock.json
  package.json
  src/packages/packages/package-builder/manifests.ts
  src/packages/packages/package-repo/manifests.ts
  src/packages/packages/package.json
  src/packages/packages/package/repository/constants.ts
  src/packages/packages/package/repository/manifests.ts
  src/packages/packages/vite.config.ts
Labels: release/14.3.0

#2190 Chore: Bundle Log Viewer Package
  package-lock.json
  package.json
  src/packages/log-viewer/package.json
  src/packages/log-viewer/vite.config.ts
Labels: release/14.3.0

#2191 Chore: Bundle Static File Package
  package-lock.json
  package.json
  src/packages/static-file/modals/static-file-picker-modal.token.ts
  src/packages/static-file/package.json
  src/packages/static-file/tree/constants.ts
  src/packages/static-file/tree/index.ts
  src/packages/static-file/tree/manifests.ts
  src/packages/static-file/vite.config.ts
Labels: release/14.3.0

#2192 Chore: Bundle Relations Package
  package-lock.json
  package.json
  src/packages/relations/index.ts
  src/packages/relations/package.json
  src/packages/relations/relation-types/collection/constants.ts
  src/packages/relations/relation-types/collection/index.ts
  src/packages/relations/relation-types/collection/manifests.ts
  src/packages/relations/relation-types/collection/repository/constants.ts
  src/packages/relations/relation-types/collection/repository/index.ts
  src/packages/relations/relation-types/collection/repository/manifests.ts
  src/packages/relations/relation-types/repository/detail/constants.ts
  src/packages/relations/relation-types/repository/detail/index.ts
  src/packages/relations/relation-types/repository/detail/manifests.ts
  src/packages/relations/vite.config.ts
Labels: release/14.3.0

#2193 Chore: Bundle Markdown Package
  package-lock.json
  package.json
  src/packages/markdown-editor/package.json
  src/packages/markdown-editor/vite.config.ts
Labels: release/14.3.0

#2194 Chore: Bundle UFM Package
  package-lock.json
  package.json
  src/packages/ufm/package.json
  src/packages/ufm/vite.config.ts
Labels: release/14.3.0

#2197 Chore: Telemetry Package and Bundle
  package-lock.json
  package.json
  src/apps/backoffice/backoffice.element.ts
  src/packages/settings/dashboards/manifests.ts
  src/packages/telemetry/dashboard-telemetry.element.ts
  src/packages/telemetry/dashboard-telemetry.stories.ts
  src/packages/telemetry/dashboard-telemetry.test.ts
  src/packages/telemetry/manifests.ts
  src/packages/telemetry/package.json
  src/packages/telemetry/umbraco-package.ts
  src/packages/telemetry/vite.config.ts
Labels: release/14.3.0

#2202 Feature: Export member and member group collection module
  src/packages/members/member-group/index.ts
  src/packages/members/member/index.ts
Labels: release/14.3.0

#2198 Chore: Performance Profiling Package and Bundle
  package-lock.json
  package.json
  src/apps/backoffice/backoffice.element.ts
  src/packages/performance-profiling/dashboard-performance-profiling.element.ts
  src/packages/performance-profiling/dashboard-performance-profiling.stories.ts
  src/packages/performance-profiling/manifests.ts
  src/packages/performance-profiling/package.json
  src/packages/performance-profiling/umbraco-package.ts
  src/packages/performance-profiling/vite.config.ts
  src/packages/settings/dashboards/manifests.ts
Labels: release/14.3.0

#2189 Feature: Data Type / Property Editor UI picker modal amends
  src/packages/code-editor/property-editor/manifests.ts
  src/packages/core/modal/token/property-editor-ui-picker-modal.token.ts
  src/packages/data-type/components/data-type-flow-input/data-type-flow-input.element.ts
  src/packages/data-type/modals/data-type-picker-flow/data-type-picker-flow-data-type-picker-modal.element.ts
  src/packages/data-type/modals/data-type-picker-flow/data-type-picker-flow-modal.element.ts
  src/packages/data-type/modals/data-type-picker-flow/data-type-picker-flow-modal.token.ts
  src/packages/data-type/modals/property-editor-ui-picker/property-editor-ui-picker-modal.element.ts
  src/packages/documents/documents/property-editors/document-picker/manifests.ts
  src/packages/markdown-editor/property-editors/markdown-editor/manifests.ts
  src/packages/media/media/property-editors/image-cropper/manifests.ts
  src/packages/media/media/property-editors/media-picker/manifests.ts
  src/packages/media/media/property-editors/upload-field/manifests.ts
  src/packages/property-editors/dropdown/manifests.ts
  src/packages/property-editors/label/manifests.ts
  src/packages/tiny-mce/property-editors/tiny-mce/manifests.ts
Labels: type/feature

#2207 Bugfix: Reexport `UmbBlockTypeBaseModel` from `@umbraco-cms/backoffice/block-type`
  src/packages/block/block-type/types.ts
Labels: type/bug, release/14.2.0

#2076 Feature: Search in Member Picker
  src/packages/members/member/components/member-picker-modal/member-picker-modal.element.ts
Labels: type/feature, release/14.3.0

#2213 [v14.2.0-RC] Fix Block Grid `layoutStylesheet` not using correct URL
  src/mocks/data/data-type/data-type.data.ts
  src/packages/block/block-grid/context/block-grid-manager.context.ts
  src/packages/block/block-type/components/block-type-card/block-type-card.element.ts
  src/packages/block/block-type/types.ts
  src/packages/core/utils/index.ts
  src/packages/core/utils/path/remove-initial-slash-from-path.function.ts
  src/packages/core/utils/path/remove-last-slash-from-path.function.ts
Labels: release/14.3.0

#2210 Feature: Document types import/export
  src/packages/documents/document-types/entity-actions/export/document-type-export.action.ts
  src/packages/documents/document-types/entity-actions/export/manifests.ts
  src/packages/documents/document-types/entity-actions/export/repository/constants.ts
  src/packages/documents/document-types/entity-actions/export/repository/document-type-export.repository.ts
  src/packages/documents/document-types/entity-actions/export/repository/document-type-export.server.data-source.ts
  src/packages/documents/document-types/entity-actions/export/repository/index.ts
  src/packages/documents/document-types/entity-actions/export/repository/manifests.ts
  src/packages/documents/document-types/entity-actions/import/document-type-import.action.ts
  src/packages/documents/document-types/entity-actions/import/manifests.ts
  src/packages/documents/document-types/entity-actions/import/modal/document-type-import-modal.element.ts
  src/packages/documents/document-types/entity-actions/import/modal/document-type-import-modal.token.ts
  src/packages/documents/document-types/entity-actions/import/modal/index.ts
  src/packages/documents/document-types/entity-actions/import/modal/manifests.ts
  src/packages/documents/document-types/entity-actions/import/repository/constants.ts
  src/packages/documents/document-types/entity-actions/import/repository/document-type-import.repository.ts
  src/packages/documents/document-types/entity-actions/import/repository/document-type-import.server.data-source.ts
  src/packages/documents/document-types/entity-actions/import/repository/index.ts
  src/packages/documents/document-types/entity-actions/import/repository/manifests.ts
  src/packages/documents/document-types/entity-actions/manifests.ts
Labels: type/feature, release/14.3.0

#2211 Feature: Media types import/export
  src/packages/media/media-types/entity-actions/export/manifests.ts
  src/packages/media/media-types/entity-actions/export/media-type-export.action.ts
  src/packages/media/media-types/entity-actions/export/repository/constants.ts
  src/packages/media/media-types/entity-actions/export/repository/index.ts
  src/packages/media/media-types/entity-actions/export/repository/manifests.ts
  src/packages/media/media-types/entity-actions/export/repository/media-type-export.repository.ts
  src/packages/media/media-types/entity-actions/export/repository/media-type-export.server.data-source.ts
  src/packages/media/media-types/entity-actions/import/manifests.ts
  src/packages/media/media-types/entity-actions/import/media-type-import.action.ts
  src/packages/media/media-types/entity-actions/import/modal/index.ts
  src/packages/media/media-types/entity-actions/import/modal/manifests.ts
  src/packages/media/media-types/entity-actions/import/modal/media-type-import-modal.element.ts
  src/packages/media/media-types/entity-actions/import/modal/media-type-import-modal.token.ts
  src/packages/media/media-types/entity-actions/import/repository/constants.ts
  src/packages/media/media-types/entity-actions/import/repository/index.ts
  src/packages/media/media-types/entity-actions/import/repository/manifests.ts
  src/packages/media/media-types/entity-actions/import/repository/media-type-import.repository.ts
  src/packages/media/media-types/entity-actions/import/repository/media-type-import.server.data-source.ts
  src/packages/media/media-types/entity-actions/manifests.ts
Labels: type/feature, release/14.3.0

#2206 Feature: System for searching in Pickers
  package.json
  src/packages/core/collection/collection-item-picker-modal/collection-item-picker-modal.context.ts
  src/packages/core/collection/collection-item-picker-modal/index.ts
  src/packages/core/collection/index.ts
  src/packages/core/components/ref-item/ref-item.element.ts
  src/packages/core/extension-registry/models/index.ts
  src/packages/core/extension-registry/models/picker-search-result-item.model.ts
  src/packages/core/manifests.ts
  src/packages/core/modal/types.ts
  src/packages/core/picker/index.ts
  src/packages/core/picker/manifests.ts
  src/packages/core/picker/picker.context.token.ts
  src/packages/core/picker/picker.context.ts
  src/packages/core/picker/search/index.ts
  src/packages/core/picker/search/manager/index.ts
  src/packages/core/picker/search/manager/picker-search.manager.ts
  src/packages/core/picker/search/manager/types.ts
  src/packages/core/picker/search/manifests.ts
  src/packages/core/picker/search/picker-search-field.element.ts
  src/packages/core/picker/search/picker-search-result.element.ts
  src/packages/core/picker/search/result-item/default/default-picker-search-result-item.context.token.ts
  src/packages/core/picker/search/result-item/default/default-picker-search-result-item.context.ts
  src/packages/core/picker/search/result-item/default/default-picker-search-result-item.element.ts
  src/packages/core/picker/search/result-item/default/manifests.ts
  src/packages/core/picker/search/result-item/manifests.ts
  src/packages/core/picker/types.ts
  src/packages/core/tree/index.ts
  src/packages/core/tree/manifests.ts
  src/packages/core/tree/tree-item-picker/index.ts
  src/packages/core/tree/tree-item-picker/tree-item-picker.context.ts
  src/packages/core/tree/tree-picker-modal/constants.ts
  src/packages/core/tree/tree-picker-modal/index.ts
  src/packages/core/tree/tree-picker-modal/manifests.ts
  src/packages/core/tree/tree-picker-modal/tree-picker-modal.element.ts
  src/packages/core/tree/tree-picker-modal/tree-picker-modal.token.ts
  src/packages/core/tree/tree-picker/tree-picker-modal.element.ts
  src/packages/core/vite.config.ts
  src/packages/documents/document-types/modals/document-type-picker-modal.token.ts
  src/packages/documents/document-types/search/constants.ts
  src/packages/documents/document-types/search/index.ts
  src/packages/documents/document-types/search/manifests.ts
  src/packages/documents/documents/manifests.ts
  src/packages/documents/documents/modals/document-picker-modal.token.ts
  src/packages/documents/documents/picker/manifests.ts
  src/packages/documents/documents/recycle-bin/entity-action/manifests.ts
  src/packages/documents/documents/search/constants.ts
  src/packages/documents/documents/search/index.ts
  src/packages/documents/documents/search/manifests.ts
  src/packages/documents/manifests.ts
  src/packages/members/manifests.ts
  src/packages/members/member/components/member-picker-modal/member-picker-modal.element.ts
  src/packages/members/member/components/member-picker-modal/member-picker-modal.token.ts
  src/packages/members/member/manifests.ts
  src/packages/members/member/picker/manifests.ts
  src/packages/members/member/search/constants.ts
  src/packages/members/member/search/index.ts
  src/packages/members/member/search/manifests.ts
  src/packages/search/types.ts
  tsconfig.json
Labels: type/feature, release/14.3.0

#2214 Block Workspace: Inherit Property VariantId
  src/packages/block/block-grid/components/block-grid-area-config-entry/workspace/block-grid-area-type-workspace.context.ts
  src/packages/block/block-grid/components/block-grid-block-inline/block-grid-inline-property-dataset.context.ts
  src/packages/block/block-type/workspace/block-type-workspace.context.ts
  src/packages/block/block/workspace/block-element-manager.ts
  src/packages/block/block/workspace/block-element-property-dataset.context.ts
  src/packages/block/block/workspace/block-workspace.context.ts
  src/packages/core/content/property-dataset-context/content-property-dataset.context.ts
  src/packages/core/property-type/workspace/property-type-workspace.context.ts
  src/packages/core/property/property-dataset/property-dataset-base-context.ts
  src/packages/core/property/property-dataset/property-dataset-context.interface.ts
  src/packages/core/property/property/property.context.ts
  src/packages/core/workspace/workspace-property-dataset/invariant-workspace-property-dataset-context.ts
  src/packages/data-type/workspace/data-type-workspace.context.ts
  src/packages/documents/document-blueprints/workspace/document-blueprint-workspace.context.ts
  src/packages/documents/documents/workspace/document-workspace.context.ts
  src/packages/media/media/workspace/media-workspace.context.ts
  src/packages/members/member/workspace/member-workspace.context.ts
  src/packages/property-editors/text-box/property-editor-ui-text-box.element.ts
Labels: type/bug, release/14.3.0

#2217 Bump @web/test-runner dependency
  package-lock.json
  package.json
Labels: dependencies, release/14.3.0

#2156 Feature: Read-only documents
  src/packages/block/block-grid/components/block-grid-block-inline/block-grid-inline-property-dataset.context.ts
  src/packages/block/block/workspace/block-element-property-dataset.context.ts
  src/packages/core/content/property-dataset-context/content-property-dataset.context.ts
  src/packages/core/content/workspace/content-workspace-context.interface.ts
  src/packages/core/manifests.ts
  src/packages/core/property-action/manifests.ts
  src/packages/core/property/conditions/constants.ts
  src/packages/core/property/conditions/index.ts
  src/packages/core/property/conditions/manifests.ts
  src/packages/core/property/conditions/writable-property.condition.ts
  src/packages/core/property/index.ts
  src/packages/core/property/manifests.ts
  src/packages/core/property/property-dataset/property-dataset-base-context.ts
  src/packages/core/property/property-dataset/property-dataset-context.interface.ts
  src/packages/core/property/property/property.context.ts
  src/packages/core/property/property/property.element.ts
  src/packages/core/utils/index.ts
  src/packages/core/utils/state-manager/index.ts
  src/packages/core/utils/state-manager/read-only-state.manager.ts
  src/packages/core/utils/state-manager/read-only-variant-state.manager.ts
  src/packages/core/utils/state-manager/state.manager.ts
  src/packages/core/workspace/components/workspace-split-view/workspace-split-view-variant-selector.element.ts
  src/packages/core/workspace/workspace-property-dataset/invariant-workspace-property-dataset-context.ts
  src/packages/documents/document-blueprints/workspace/document-blueprint-workspace.context.ts
  src/packages/documents/documents/utils.ts
  src/packages/documents/documents/workspace/document-workspace.context.ts
  src/packages/language/manifests.ts
  src/packages/language/permissions/language-access.workspace-context.token.ts
  src/packages/language/permissions/language-access.workspace-context.ts
  src/packages/media/media/workspace/media-workspace.context.ts
  src/packages/members/member/workspace/member-workspace.context.ts
  src/packages/property-editors/label/manifests.ts
  src/packages/property-editors/number/manifests.ts
  src/packages/property-editors/text-box/manifests.ts
  src/packages/property-editors/textarea/manifests.ts
  src/packages/tags/property-editors/tags/manifests.ts
  src/packages/user/current-user/current-user.context.ts
Labels: type/feature, release/14.3.0

#2219 Feature: Readonly mode for Date Picker Property Editor UI
  src/packages/core/components/input-date/input-date.element.ts
  src/packages/property-editors/date-picker/manifests.ts
  src/packages/property-editors/date-picker/property-editor-ui-date-picker.element.ts
Labels: type/feature, release/14.3.0

#2220 Feature: Readonly mode for Slider Property Editor UI
  src/packages/core/components/input-slider/input-slider.element.ts
  src/packages/property-editors/slider/manifests.ts
  src/packages/property-editors/slider/property-editor-ui-slider.element.ts
Labels: type/feature, release/14.3.0

#2222 Feature: Readonly mode for Dropdown Property Editor UI
  src/packages/core/components/input-dropdown/input-dropdown-list.element.ts
  src/packages/property-editors/dropdown/manifests.ts
  src/packages/property-editors/dropdown/property-editor-ui-dropdown.element.ts
Labels: type/feature, release/14.3.0

#2221 Feature: Readonly mode for Radio Button List Property Editor UI
  src/packages/core/components/input-radio-button-list/input-radio-button-list.element.ts
  src/packages/property-editors/radio-button-list/manifests.ts
  src/packages/property-editors/radio-button-list/property-editor-ui-radio-button-list.element.ts
Labels: type/feature, release/14.3.0

#2223 Feature: Readonly mode for Tiny MCE Property Editor UI
  src/packages/tiny-mce/components/input-tiny-mce/input-tiny-mce.element.ts
  src/packages/tiny-mce/property-editors/tiny-mce/manifests.ts
  src/packages/tiny-mce/property-editors/tiny-mce/property-editor-ui-tiny-mce.element.ts
Labels: type/feature, release/14.3.0

#2218 Chore: Combine settings files
  src/packages/core/manifests.ts
  src/packages/core/settings/manifests.ts
  src/packages/settings/advanced/constants.ts
  src/packages/settings/advanced/index.ts
  src/packages/settings/advanced/manifests.ts
  src/packages/settings/index.ts
  src/packages/settings/manifests.ts
  src/packages/settings/section/constants.ts
  src/packages/settings/section/index.ts
  src/packages/settings/section/manifests.ts
  src/packages/settings/section/paths.ts
  src/packages/settings/structure/constants.ts
  src/packages/settings/structure/index.ts
  src/packages/settings/structure/manifests.ts
  src/packages/settings/umbraco-package.ts
  src/packages/settings/welcome/manifests.ts
  src/packages/settings/welcome/settings-welcome-dashboard.element.ts
  src/packages/settings/welcome/settings-welcome-dashboard.stories.ts
  src/packages/settings/welcome/settings-welcome-dashboard.test.ts
Labels: ignore-for-release, internal

#2092 Bugfix: Auto generate alias
  src/packages/core/components/input-with-alias/input-with-alias.element.ts
  src/packages/core/content-type/workspace/views/design/content-type-design-editor-property.element.ts
  src/packages/core/property-type/workspace/views/settings/property-workspace-view-settings.element.ts
Labels: type/bug

#2224 Bugfix: Set document name to read only when user does not have access to edit a language
  src/packages/core/workspace/components/workspace-split-view/workspace-split-view-variant-selector.element.ts
Labels: type/bug, release/14.3.0

#2226 Feature: Readonly mode for Document Picker Property Editor UI
  src/packages/core/sorter/sorter.controller.test.ts
  src/packages/core/sorter/sorter.controller.ts
  src/packages/documents/documents/components/input-document/input-document.element.ts
  src/packages/documents/documents/property-editors/document-picker/manifests.ts
  src/packages/documents/documents/property-editors/document-picker/property-editor-ui-document-picker.element.ts
Labels: type/feature, release/14.3.0

#2225 Feature: Support Language Permissions in Dictionary Section
  src/packages/dictionary/workspace/views/workspace-view-dictionary-editor.element.ts
Labels: type/feature, release/14.3.0

#2232 Hotfix: Add back reexport of UmbSaveWorkspaceAction
  src/packages/core/workspace/components/workspace-action/common/submit/submit.action.ts
Labels: type/bug, release/14.2.0

#2227 Feature: Readonly mode for Rich Media Picker Property Editor UI
  src/packages/media/media/components/input-rich-media/input-rich-media.element.ts
  src/packages/media/media/property-editors/media-picker/manifests.ts
  src/packages/media/media/property-editors/media-picker/property-editor-ui-media-picker.element.ts
  src/packages/property-editors/toggle/manifests.ts
Labels: type/feature, release/14.3.0

#2239 Merge Release 14.2 branch into main
  .github/RELEASE_INSTRUCTION.md
  src/packages/core/workspace/components/workspace-action/common/submit/submit.action.ts
  src/packages/media/media/workspace/views/info/media-workspace-view-info.element.ts
Labels: ignore-for-release, internal

#2240 Chore: Bump version to 14.3
  package-lock.json
  package.json
Labels: ignore-for-release, internal

#2243 Bugfix: Exports `UmbUfmComponentBase` type
  examples/ufm-custom-component/README.md
  examples/ufm-custom-component/custom-ufm-component.ts
  examples/ufm-custom-component/index.ts
  src/packages/ufm/index.ts
Labels: type/bug

#2228 Feature: Readonly mode for Member Picker Property Editor UI
  src/packages/members/member/components/input-member/input-member.element.ts
  src/packages/members/member/property-editor/member-picker/manifests.ts
  src/packages/members/member/property-editor/member-picker/property-editor-ui-member-picker.element.ts
Labels: type/feature, release/14.3.0

#2230 Feature: Readonly mode for Multi URL Picker Property Editor UI
  src/packages/multi-url-picker/components/input-multi-url/input-multi-url.element.ts
  src/packages/multi-url-picker/link-picker-modal/link-picker-modal.element.ts
  src/packages/multi-url-picker/property-editor/manifests.ts
  src/packages/multi-url-picker/property-editor/property-editor-ui-multi-url-picker.element.ts
Labels: type/feature, release/14.3.0

#2231 Feature: Readonly mode for Checkbox List Property Editor UI
  src/packages/property-editors/checkbox-list/components/input-checkbox-list/input-checkbox-list.element.ts
  src/packages/property-editors/checkbox-list/manifests.ts
  src/packages/property-editors/checkbox-list/property-editor-ui-checkbox-list.element.ts
Labels: type/feature, release/14.3.0

#2241 Feature: Readonly mode for Markdown Property Editor UI
  src/packages/markdown-editor/components/input-markdown-editor/input-markdown.element.ts
  src/packages/markdown-editor/property-editors/markdown-editor/manifests.ts
  src/packages/markdown-editor/property-editors/markdown-editor/property-editor-ui-markdown-editor.element.ts
Labels: type/feature, release/14.3.0

#2238 Feature: Readonly mode for Member Group Picker Property Editor UI
  src/packages/members/member-group/components/input-member-group/input-member-group.element.ts
  src/packages/members/member-group/property-editor/member-group-picker/manifests.ts
  src/packages/members/member-group/property-editor/member-group-picker/property-editor-ui-member-group-picker.element.ts
Labels: type/feature, release/14.3.0
