Repository umbraco/Umbraco.CMS.Backoffice, pull requests merged in 2024-05, with the labels that each got.

#1736 Bugfix: Document Collection View - loading state + opens modal
  src/packages/core/collection/default/collection-default.context.ts
  src/packages/core/collection/default/collection-default.element.ts
  src/packages/documents/documents/collection/types.ts
  src/packages/documents/documents/collection/views/grid/document-grid-collection-view.element.ts
  src/packages/documents/documents/collection/views/table/column-layouts/document-table-column-name.element.ts
  src/packages/documents/documents/collection/views/table/column-layouts/document-table-column-state.element.ts
  src/packages/documents/documents/collection/views/table/document-table-collection-view.element.ts
Labels: type/bug

#1707 Bugfix: Content Type Composition Interfaces
  src/packages/core/content-type/composition/content-type-composition-data-source.interface.ts
  src/packages/core/content-type/composition/content-type-composition-repository.interface.ts
  src/packages/core/content-type/composition/index.ts
  src/packages/core/content-type/composition/types.ts
  src/packages/core/content-type/index.ts
  src/packages/core/content-type/modals/composition-picker/composition-picker-modal.element.ts
  src/packages/documents/document-types/repository/composition/document-type-composition.repository.ts
  src/packages/documents/document-types/repository/composition/document-type-composition.server.data-source.ts
  src/packages/documents/document-types/types.ts
Labels: type/bug

#1744 dont show label for block type + use parent path
  src/packages/block/block-type/components/block-type-card/block-type-card.element.ts
  src/packages/block/block/modals/block-catalogue/block-catalogue-modal.element.ts
  src/packages/documents/document-types/workspace/document-type-workspace-editor.element.ts
  src/packages/documents/documents/paths.ts
Labels: type/bug

#1720 Feature: Login without losing changes
  docs/authentication.md
  src/apps/app/app-auth.controller.ts
  src/apps/app/app-error.element.ts
  src/apps/app/app.element.ts
  src/assets/lang/da-dk.ts
  src/assets/lang/en-us.ts
  src/assets/lang/en.ts
  src/external/openid/redirect_based_handler.ts
  src/external/rxjs/index.ts
  src/libs/extension-api/initializers/extension-initializer-base.ts
  src/packages/core/auth/auth-flow.ts
  src/packages/core/auth/auth.context.ts
  src/packages/core/auth/components/auth-provider-default.element.ts
  src/packages/core/auth/modals/umb-app-auth-modal.element.ts
  src/packages/core/auth/modals/umb-app-auth-modal.token.ts
  src/packages/core/auth/types.ts
  src/packages/core/extension-registry/initializers/app-entry-point-extension-initializer.ts
  src/packages/core/extension-registry/initializers/backoffice-entry-point-extension-initializer.ts
  src/packages/core/extension-registry/models/auth-provider.model.ts
  src/packages/core/validation/context/server-model-validation.context.ts
Labels: type/feature, notable

#1754 Adds different content for `Community` and `Support` blocks
  .github/localization_overview.md
  src/assets/lang/da-dk.ts
  src/assets/lang/en-us.ts
  src/assets/lang/en.ts
  src/packages/core/settings/welcome-dashboard/settings-welcome-dashboard.element.ts
Labels: community/pr, type/bug

#1732 Feature: Entity Is trashed condition + filter document/media entity actions
  src/packages/core/components/entity-actions-bundle/entity-actions-bundle.element.ts
  src/packages/core/recycle-bin/conditions/is-not-trashed/constants.ts
  src/packages/core/recycle-bin/conditions/is-not-trashed/entity-is-not-trashed.condition.manifest.ts
  src/packages/core/recycle-bin/conditions/is-not-trashed/entity-is-not-trashed.condition.ts
  src/packages/core/recycle-bin/conditions/is-trashed/constants.ts
  src/packages/core/recycle-bin/conditions/is-trashed/entity-is-trashed.condition.manifest.ts
  src/packages/core/recycle-bin/conditions/is-trashed/entity-is-trashed.condition.ts
  src/packages/core/recycle-bin/conditions/manifests.ts
  src/packages/core/recycle-bin/contexts/is-trashed/index.ts
  src/packages/core/recycle-bin/contexts/is-trashed/is-trashed.entity-context-token.ts
  src/packages/core/recycle-bin/contexts/is-trashed/is-trashed.entity-context.ts
  src/packages/core/recycle-bin/index.ts
  src/packages/core/recycle-bin/manifests.ts
  src/packages/core/tree/tree-item/tree-item-base/tree-item-context-base.ts
  src/packages/documents/documents/entity-actions/create-blueprint/manifests.ts
  src/packages/documents/documents/entity-actions/create/manifests.ts
  src/packages/documents/documents/entity-actions/culture-and-hostnames/manifests.ts
  src/packages/documents/documents/entity-actions/duplicate/manifests.ts
  src/packages/documents/documents/entity-actions/manifests.ts
  src/packages/documents/documents/entity-actions/move-to/manifests.ts
  src/packages/documents/documents/entity-actions/public-access/manifests.ts
  src/packages/documents/documents/entity-actions/sort-children-of/manifests.ts
  src/packages/documents/documents/recycle-bin/entity-action/manifests.ts
  src/packages/documents/documents/tree/tree-item/document-tree-item.context.ts
  src/packages/documents/documents/workspace/conditions/document-is-not-trashed.condition.manifest.ts
  src/packages/documents/documents/workspace/conditions/document-is-not-trashed.condition.ts
  src/packages/documents/documents/workspace/conditions/is-not-trashed/document-is-not-trashed.condition.manifest.ts
  src/packages/documents/documents/workspace/conditions/is-not-trashed/document-is-not-trashed.condition.ts
  src/packages/documents/documents/workspace/conditions/is-trashed/document-is-trashed.condition.manifest.ts
  src/packages/documents/documents/workspace/conditions/is-trashed/document-is-trashed.condition.ts
  src/packages/documents/documents/workspace/conditions/manifests.ts
  src/packages/documents/documents/workspace/document-workspace.context.ts
  src/packages/documents/documents/workspace/manifests.ts
  src/packages/media/media/entity-actions/create/manifests.ts
  src/packages/media/media/entity-actions/manifests.ts
  src/packages/media/media/entity-actions/move-to/manifests.ts
  src/packages/media/media/recycle-bin/entity-action/manifests.ts
  src/packages/media/media/tree/tree-item/media-tree-item.context.ts
  src/packages/media/media/workspace/manifests.ts
  src/packages/media/media/workspace/media-workspace.context.ts
Labels: type/feature, type/bug

#1727 Bugfix: Persist User document and media start nodes
  src/external/backend-api/src/models.ts
  src/external/backend-api/src/services.ts
  src/mocks/data/data-type/data-type.data.ts
  src/mocks/data/data-type/data-type.db.ts
  src/mocks/data/user/user.data.ts
  src/mocks/data/user/user.db.ts
  src/packages/data-type/repository/detail/data-type-detail.server.data-source.ts
  src/packages/user/user/collection/repository/user-collection.server.data-source.ts
  src/packages/user/user/repository/detail/user-detail.server.data-source.ts
  src/packages/user/user/types.ts
  src/packages/user/user/workspace/components/user-workspace-access-settings/user-workspace-access-settings.element.ts
  src/packages/user/user/workspace/components/user-workspace-access/user-workspace-access.element.ts
  src/packages/user/user/workspace/components/user-workspace-assign-access/user-workspace-assign-access.element.ts
  src/packages/user/user/workspace/user-workspace-editor.element.ts
  src/packages/user/user/workspace/user-workspace.context.ts
Labels: type/bug

#1751 Feature: Add User Group Alias
  src/external/backend-api/src/models.ts
  src/mocks/data/user-group/user-group.data.ts
  src/mocks/data/user-group/user-group.db.ts
  src/packages/core/components/input-with-alias/input-with-alias.element.ts
  src/packages/user/user-group/collection/repository/user-group-collection.server.data-source.ts
  src/packages/user/user-group/repository/detail/user-group-detail.server.data-source.ts
  src/packages/user/user-group/types.ts
  src/packages/user/user-group/workspace/user-group-workspace-editor.element.ts
  src/packages/user/user-group/workspace/user-group-workspace.context.ts
Labels: type/feature

#1762 Feature: RTE oEmbed implementation
  src/mocks/handlers/rte-embed.handlers.ts
  src/packages/core/modal/common/embedded-media/embedded-media-modal.element.ts
  src/packages/core/modal/common/embedded-media/index.ts
  src/packages/core/modal/common/embedded-media/manifests.ts
  src/packages/core/modal/common/embedded-media/repository/index.ts
  src/packages/core/modal/common/embedded-media/repository/manifests.ts
  src/packages/core/modal/common/embedded-media/repository/oembed.repository.ts
  src/packages/core/modal/common/embedded-media/repository/oembed.server.data.ts
  src/packages/core/modal/common/index.ts
  src/packages/core/modal/token/embedded-media-modal.token.ts
  src/packages/tiny-mce/plugins/tiny-mce-embeddedmedia.plugin.ts
Labels: type/feature

#1768 set es2022 for tsconfig
  tsconfig.json
Labels: storybook

#1767 fix: assume you are logged in if there is a token persisted
  src/packages/core/auth/auth-flow.ts
Labels: type/bug

#1770 Feature/webhooks
  src/packages/webhook/collection/repository/webhook-collection.server.data-source.ts
  src/packages/webhook/collection/views/table/column-layouts/content-type/webhook-table-name-column-layout.element.ts
  src/packages/webhook/collection/views/table/column-layouts/entity-actions/webhook-table-entity-actions-column-layout.element.ts
  src/packages/webhook/collection/views/table/column-layouts/name/webhook-table-name-column-layout.element.ts
  src/packages/webhook/collection/views/table/webhook-table-collection-view.element.ts
  src/packages/webhook/components/input-webhook-events.element.ts
  src/packages/webhook/components/input-webhook-headers.element.ts
  src/packages/webhook/components/webhook-events-modal/webhook-events-modal.element.ts
  src/packages/webhook/components/webhook-events-modal/webhook-events-modal.token.ts
  src/packages/webhook/entity-actions/manifests.ts
  src/packages/webhook/entity.ts
  src/packages/webhook/manifests.ts
  src/packages/webhook/menu-item/manifests.ts
  src/packages/webhook/repository/detail/index.ts
  src/packages/webhook/repository/detail/manifests.ts
  src/packages/webhook/repository/detail/webhook-detail.repository.ts
  src/packages/webhook/repository/detail/webhook-detail.server.data-source.ts
  src/packages/webhook/repository/detail/webhook-detail.store.ts
  src/packages/webhook/repository/event/index.ts
  src/packages/webhook/repository/event/manifests.ts
  src/packages/webhook/repository/event/webhook-event.repository.ts
  src/packages/webhook/repository/event/webhook-event.server.data-source.ts
  src/packages/webhook/repository/event/webhook-event.store.ts
  src/packages/webhook/repository/index.ts
  src/packages/webhook/repository/item/index.ts
  src/packages/webhook/repository/item/manifests.ts
  src/packages/webhook/repository/item/types.ts
  src/packages/webhook/repository/item/webhook-item.repository.ts
  src/packages/webhook/repository/item/webhook-item.server.data-source.ts
  src/packages/webhook/repository/item/webhook-item.store.ts
  src/packages/webhook/repository/manifests.ts
  src/packages/webhook/types.ts
  src/packages/webhook/workspace/manifests.ts
  src/packages/webhook/workspace/webhook-root/manifests.ts
  src/packages/webhook/workspace/webhook-root/webhook-root-workspace.element.ts
  src/packages/webhook/workspace/webhook/manifests.ts
  src/packages/webhook/workspace/webhook/views/webhook-details-workspace-view.element.ts
  src/packages/webhook/workspace/webhook/webhook-workspace-editor.element.ts
  src/packages/webhook/workspace/webhook/webhook-workspace.context-token.ts
  src/packages/webhook/workspace/webhook/webhook-workspace.context.ts
  src/packages/webhook/workspace/webhook/webhook-workspace.element.ts
Labels: type/feature, notable

#1758 remove the unused 'allowDecimals' configuration and the "Integer" property editor
  src/mocks/data/data-type/data-type.data.ts
  src/packages/property-editors/number/Umbraco.Integer.ts
  src/packages/property-editors/number/manifests.ts
Labels: type/feature

#1738 Bugfix: Media Collection View - loading state + opens modal
  src/packages/media/media/collection/repository/media-collection.server.data-source.ts
  src/packages/media/media/collection/types.ts
  src/packages/media/media/collection/views/grid/media-grid-collection-view.element.ts
  src/packages/media/media/collection/views/table/column-layouts/media-table-column-name.element.ts
  src/packages/media/media/collection/views/table/media-table-collection-view.element.ts
  src/packages/media/media/index.ts
  src/packages/media/media/paths.ts
Labels: type/bug

#1774 Retry requests after log in
  src/apps/backoffice/backoffice.context.ts
  src/apps/backoffice/backoffice.element.ts
  src/packages/language/global-contexts/app-language.context.ts
Labels: type/bug

#1779 Feature: Confirm Modal: Adds `cancelLabel` option
  src/packages/core/modal/common/confirm/confirm-modal.element.ts
  src/packages/core/modal/token/confirm-modal.token.ts
Labels: type/feature

#1785 Bugfix: remove create action on doc type items
  src/packages/documents/document-types/entity-actions/create/manifests.ts
Labels: type/bug

#1784 fix: token after refresh is not persisted
  src/packages/core/auth/auth-flow.ts
Labels: type/bug

#1792 Bugfix: Split panel overflow
  src/packages/core/components/split-panel/split-panel.element.ts
Labels: type/bug

#1789 Feature/bigger user card avatars
  src/packages/user/user/collection/views/grid/user-grid-collection-view.element.ts
Labels: type/feature

#1791 Feature: umb-body-layout - Hide empty slots
  src/packages/core/components/body-layout/body-layout.element.ts
Labels: type/bug

#1790 Bugfix: Don't lower case iso codes
  src/packages/language/repository/detail/language-detail.server.data-source.ts
Labels: type/bug

#1799 fix: tinymce does not use its default config
  src/packages/tiny-mce/components/input-tiny-mce/input-tiny-mce.defaults.ts
  src/packages/tiny-mce/components/input-tiny-mce/input-tiny-mce.element.ts
Labels: type/bug

#1798 fix: multiple TinyMCE's on the same page does not work
  src/packages/tiny-mce/components/input-tiny-mce/input-tiny-mce.element.ts
Labels: type/bug

#1801 Feature: Login without popup
  src/apps/app/app.element.ts
  src/assets/lang/da-dk.ts
  src/assets/lang/en-us.ts
  src/assets/lang/en.ts
  src/packages/core/auth/modals/umb-app-auth-modal.element.ts
Labels: type/feature

#1802 Feature: Validate the token on first load
  src/apps/app/app-auth.controller.ts
  src/packages/core/auth/auth-flow.ts
  src/packages/core/auth/auth.context.ts
Labels: type/feature

#1806 Bugfix: Color Picker modal focus
  src/packages/core/components/multiple-color-picker-input/multiple-color-picker-item-input.element.ts
Labels: type/bug

#1807 Bugfix: Document Picker: Start node
  src/packages/documents/documents/property-editors/document-picker/property-editor-ui-document-picker.element.ts
Labels: type/bug

#1805 Chore: `umb-debug` UI tweaks
  src/libs/context-api/debug/context-data.function.ts
  src/libs/context-api/provide/context-provider.ts
  src/packages/core/debug/debug.element.ts
  src/packages/core/debug/modals/debug/debug-modal.element.ts
  src/packages/core/debug/stories/umb-debug-dialog.jpg
  src/packages/core/debug/stories/umb-debug.jpg
Labels: storybook

#1804 Bugfix: Eye Dropper: Show Palette / Swatches
  src/packages/core/components/input-eye-dropper/input-eye-dropper.element.ts
  src/packages/core/components/input-eye-dropper/input-eye-dropper.stories.ts
  src/packages/property-editors/eye-dropper/property-editor-ui-eye-dropper.element.ts
Labels: type/bug, storybook

#1808 Bugfix: Document Collection: Create action modal route
  src/packages/documents/documents/collection/action/create-document-collection-action.element.ts
Labels: type/bug

#1793 Feature: Add user group query filter
  src/packages/user/user-group/collection/manifests.ts
  src/packages/user/user-group/collection/repository/user-group-collection.server.data-source.ts
  src/packages/user/user-group/collection/types.ts
  src/packages/user/user-group/collection/user-group-collection-header.element.ts
  src/packages/user/user-group/collection/user-group-collection.context.ts
  src/packages/user/user-group/collection/user-group-collection.element.ts
  src/packages/user/user-group/collection/views/constants.ts
  src/packages/user/user-group/collection/views/manifests.ts
Labels: type/feature

#1810 Feature: Support for name/value options in list property editors
  src/packages/core/components/input-radio-button-list/input-radio-button-list.element.ts
  src/packages/property-editors/checkbox-list/components/input-checkbox-list/input-checkbox-list.element.ts
  src/packages/property-editors/checkbox-list/property-editor-ui-checkbox-list.element.ts
  src/packages/property-editors/dropdown/property-editor-ui-dropdown.element.ts
  src/packages/property-editors/radio-button-list/property-editor-ui-radio-button-list.element.ts
  src/packages/property-editors/select/property-editor-ui-select.element.ts
  src/packages/property-editors/select/property-editor-ui-select.test.ts
Labels: type/feature

#1796 Bugfix: Add recycle bin conditions for media + document root access
  src/packages/core/extension-registry/models/menu-item.model.ts
  src/packages/documents/documents/recycle-bin/allow-document-recycle-bin.condition.ts
  src/packages/documents/documents/recycle-bin/manifests.ts
  src/packages/documents/documents/recycle-bin/menu-item/manifests.ts
  src/packages/media/media/recycle-bin/allow-media-recycle-bin.condition.ts
  src/packages/media/media/recycle-bin/manifests.ts
  src/packages/media/media/recycle-bin/menu-item/manifests.ts
  src/packages/user/current-user/current-user.context.ts
  src/packages/user/current-user/repository/current-user.server.data-source.ts
  src/packages/user/current-user/types.ts
Labels: type/bug

#1797 Chore: Move extension components to extension-registry module
  src/packages/core/components/index.ts
  src/packages/core/entry-point.ts
  src/packages/core/extension-registry/components/extension-slot/extension-slot.element.ts
  src/packages/core/extension-registry/components/extension-slot/extension-slot.test.ts
  src/packages/core/extension-registry/components/extension-slot/index.ts
  src/packages/core/extension-registry/components/extension-with-api-slot/extension-with-api-slot.element.ts
  src/packages/core/extension-registry/components/extension-with-api-slot/extension-with-api-slot.test.ts
  src/packages/core/extension-registry/components/extension-with-api-slot/index.ts
  src/packages/core/extension-registry/components/index.ts
  src/packages/core/property/property/property.element.ts
Labels: storybook

#1757 Multi Url Picker package - including markdown editor action extension point
  src/apps/backoffice/backoffice.element.ts
  src/packages/core/components/index.ts
  src/packages/core/components/input-multi-url/index.ts
  src/packages/core/components/input-multi-url/input-multi-url.stories.ts
  src/packages/core/extension-registry/models/index.ts
  src/packages/core/extension-registry/models/monaco-markdown-editor-action.model.ts
  src/packages/core/modal/common/manifests.ts
  src/packages/core/modal/token/index.ts
  src/packages/markdown-editor/components/input-markdown-editor/input-markdown.element.ts
  src/packages/multi-url-picker/link-picker-modal/constants.ts
  src/packages/multi-url-picker/link-picker-modal/link-picker-modal.element.ts
  src/packages/multi-url-picker/link-picker-modal/link-picker-modal.stories.ts
  src/packages/multi-url-picker/link-picker-modal/link-picker-modal.token.ts
  src/packages/multi-url-picker/link-picker-modal/manifests.ts
  src/packages/multi-url-picker/link-picker-modal/types.ts
  src/packages/multi-url-picker/manifests.ts
  src/packages/multi-url-picker/monaco-markdown-editor-action/manifests.ts
  src/packages/multi-url-picker/monaco-markdown-editor-action/url-picker-monaco-markdown-editor-action.ts
  src/packages/multi-url-picker/multi-url-picker/index.ts
  src/packages/multi-url-picker/multi-url-picker/multi-url-picker.element.ts
  src/packages/multi-url-picker/multi-url-picker/multi-url-picker.stories.ts
  src/packages/multi-url-picker/property-editor/Umbraco.MultiUrlPicker.ts
  src/packages/multi-url-picker/property-editor/manifests.ts
  src/packages/multi-url-picker/property-editor/property-editor-ui-multi-url-picker.element.ts
  src/packages/multi-url-picker/property-editor/property-editor-ui-multi-url-picker.stories.ts
  src/packages/multi-url-picker/property-editor/property-editor-ui-multi-url-picker.test.ts
  src/packages/multi-url-picker/tiny-mce-plugin/manifests.ts
  src/packages/multi-url-picker/tiny-mce-plugin/tiny-mce-multi-url-picker.plugin.ts
  src/packages/multi-url-picker/umbraco-package.ts
  src/packages/property-editors/manifests.ts
  src/packages/property-editors/multi-url-picker/manifests.ts
  src/packages/tiny-mce/plugins/manifests.ts
Labels: type/feature, category/breaking

#1816 Bugfix: Re-introduces Integer, removes Number editor
  src/mocks/data/data-type/data-type.data.ts
  src/packages/block/block-grid/property-editors/block-grid-editor/manifests.ts
  src/packages/block/block-grid/workspace/views/block-grid-type-workspace-view-areas.element.ts
  src/packages/multi-url-picker/property-editor/Umbraco.MultiUrlPicker.ts
  src/packages/property-editors/collection/manifests.ts
  src/packages/property-editors/content-picker/Umbraco.MultiNodeTreePicker.ts
  src/packages/property-editors/multiple-text-string/Umbraco.MultipleTextString.ts
  src/packages/property-editors/number/Umbraco.Integer.ts
  src/packages/property-editors/number/manifests.ts
  src/packages/property-editors/slider/Umbraco.Slider.ts
  src/packages/property-editors/slider/manifests.ts
  src/packages/property-editors/text-box/Umbraco.TextBox.ts
  src/packages/property-editors/textarea/Umbraco.TextArea.ts
  src/packages/property-editors/textarea/manifests.ts
Labels: type/bug

#1800 fix: a black icon is shown twice in the icon picker
  src/packages/core/resources/extractUmbColorVariable.function.ts
Labels: type/bug

#1821 Chore: fix storybook build
  src/packages/multi-url-picker/link-picker-modal/link-picker-modal.stories.ts
Labels: storybook

#1823 Bugfix: Sets width of header logo modal
  src/apps/backoffice/components/backoffice-header-logo.element.ts
Labels: type/bug

#1834 fix: donut chart components are not exported
  src/packages/log-viewer/index.ts
Labels: type/bug

#1814 Bugfix: Ignore user start node for document and media trees
  src/packages/core/content-type/components/property-type-based-property/property-type-based-property.element.ts
  src/packages/core/content/content-property.context-token.ts
  src/packages/core/content/content-property.context.ts
  src/packages/core/content/index.ts
  src/packages/core/tree/data/tree-data-source.interface.ts
  src/packages/core/tree/data/tree-repository-base.ts
  src/packages/core/tree/data/tree-repository.interface.ts
  src/packages/core/tree/data/tree-server-data-source-base.ts
  src/packages/core/tree/default/default-tree.context-token.ts
  src/packages/core/tree/default/default-tree.context.ts
  src/packages/core/tree/default/default-tree.element.ts
  src/packages/core/tree/default/index.ts
  src/packages/core/tree/tree-item/tree-item-base/tree-item-context-base.ts
  src/packages/documents/documents/components/input-document/input-document.element.ts
  src/packages/documents/documents/property-editors/document-picker/property-editor-ui-document-picker.element.ts
  src/packages/documents/documents/tree/document-tree.context.ts
  src/packages/documents/documents/tree/document-tree.element.ts
  src/packages/documents/documents/tree/document-tree.server.data-source.ts
  src/packages/documents/documents/tree/manifests.ts
  src/packages/documents/documents/tree/types.ts
  src/packages/media/media/components/input-media/input-media.element.ts
  src/packages/media/media/tree/manifests.ts
  src/packages/media/media/tree/media-tree.context.ts
  src/packages/media/media/tree/media-tree.element.ts
  src/packages/media/media/tree/media-tree.server.data-source.ts
  src/packages/media/media/tree/types.ts
  src/packages/members/member/collection/action/create-member-collection-action.element.ts
  src/packages/members/member/collection/member-collection-header.element.ts
  src/packages/multi-url-picker/link-picker-modal/link-picker-modal.element.ts
  src/packages/multi-url-picker/link-picker-modal/link-picker-modal.token.ts
  src/packages/multi-url-picker/multi-url-picker/multi-url-picker.element.ts
  src/packages/multi-url-picker/property-editor/property-editor-ui-multi-url-picker.element.ts
  src/packages/multi-url-picker/tiny-mce-plugin/tiny-mce-multi-url-picker.plugin.ts
  src/packages/property-editors/content-picker/components/input-content/input-content.element.ts
  src/packages/property-editors/content-picker/property-editor-ui-content-picker.element.ts
Labels: category/breaking

#1778 Feature: Document Preview
  src/apps/app/app.element.ts
  src/apps/preview/apps/manifests.ts
  src/apps/preview/apps/preview-culture.element.ts
  src/apps/preview/apps/preview-device.element.ts
  src/apps/preview/apps/preview-exit.element.ts
  src/apps/preview/apps/preview-open-website.element.ts
  src/apps/preview/preview.context.ts
  src/apps/preview/preview.element.ts
  src/apps/preview/preview.stories.ts
  src/apps/preview/preview.test.ts
  src/packages/core/extension-registry/models/index.ts
  src/packages/core/extension-registry/models/preview-app.model.ts
  src/packages/documents/documents/repository/index.ts
  src/packages/documents/documents/repository/preview/document-preview.repository.ts
  src/packages/documents/documents/repository/preview/index.ts
  src/packages/documents/documents/workspace/actions/save-and-preview.action.ts
  src/packages/documents/documents/workspace/document-workspace.context.ts
Labels: type/feature, notable

#1836 Bugfix: Fix image cropper remove issue
  src/packages/media/media/components/input-image-cropper/input-image-cropper.element.ts
  src/packages/media/media/property-editors/image-cropper/property-editor-ui-image-cropper.element.ts
Labels: type/bug

#1815 Feature: Link and Unlink External Login Providers
  src/apps/app/app.element.ts
  src/assets/lang/da-dk.ts
  src/assets/lang/en-us.ts
  src/assets/lang/en.ts
  src/external/backend-api/src/models.ts
  src/external/backend-api/src/services.ts
  src/mocks/data/user/user.data.ts
  src/mocks/handlers/manifests.handlers.ts
  src/mocks/handlers/user/current.handlers.ts
  src/packages/core/auth/auth-flow.ts
  src/packages/core/auth/auth.context.ts
  src/packages/core/auth/components/auth-provider-default.element.ts
  src/packages/core/auth/providers/manifests.ts
  src/packages/core/icon-registry/icon-dictionary.json
  src/packages/core/icon-registry/icons/icon-window-popout.js
  src/packages/core/icon-registry/icons/icons.ts
  src/packages/user/current-user/external-login/configure-external-login-providers-action.ts
  src/packages/user/current-user/external-login/manifests.ts
  src/packages/user/current-user/external-login/modals/external-login-modal.element.ts
  src/packages/user/current-user/external-login/modals/external-login-modal.stories.ts
  src/packages/user/current-user/external-login/modals/external-login-modal.token.ts
  src/packages/user/current-user/manifests.ts
  src/packages/user/current-user/modals/current-user-mfa/current-user-mfa-modal.element.ts
  src/packages/user/current-user/repository/current-user.repository.ts
  src/packages/user/current-user/repository/current-user.server.data-source.ts
  src/packages/user/current-user/repository/current-user.store.ts
  src/packages/user/current-user/types.ts
  src/packages/user/user/conditions/manifests.ts
  src/packages/user/user/conditions/user-allow-external-login-action.condition.ts
  src/packages/user/user/modals/user-mfa/user-mfa-modal.element.ts
Labels: type/feature, storybook

#1840 Feature: MediaPickerModal Filters & InputMedia Configuration
  src/packages/media/media/collection/views/grid/media-grid-collection-view.element.ts
  src/packages/media/media/components/input-media/input-media.context.ts
  src/packages/media/media/components/input-media/input-media.element.ts
  src/packages/media/media/modals/media-picker/media-picker-modal.element.ts
  src/packages/media/media/modals/media-picker/media-picker-modal.token.ts
  src/packages/media/media/modals/media-picker/types.ts
  src/packages/media/media/property-editors/media-entity-picker/property-editor-ui-media-entity-picker.element.ts
  src/packages/media/media/property-editors/media-picker/components/index.ts
  src/packages/media/media/property-editors/media-picker/components/input-rich-media/index.ts
  src/packages/media/media/property-editors/media-picker/components/input-rich-media/input-rich-media.element.ts
  src/packages/media/media/property-editors/media-picker/index.ts
  src/packages/media/media/property-editors/media-picker/property-editor-ui-media-picker.element.ts
  src/packages/media/media/tree/media-tree.repository.ts
  src/packages/packages/package-builder/workspace/workspace-package-builder.element.ts
  src/packages/tiny-mce/plugins/tiny-mce-mediapicker.plugin.ts
Labels: type/feature

#1846 Map has access to sensitive data
  src/packages/user/current-user/repository/current-user.server.data-source.ts
  src/packages/user/current-user/types.ts
Labels: type/feature

#1847 Bugfix: Reload user collection on disable, enable, and unlock
  src/packages/user/user/entity-bulk-actions/disable/disable.action.ts
  src/packages/user/user/entity-bulk-actions/enable/enable.action.ts
  src/packages/user/user/entity-bulk-actions/unlock/unlock.action.ts
Labels: type/bug

#1760 fix: ensure any property editor UIs save their initial value on the context
  src/packages/core/property/property/property.element.ts
Labels: type/bug

#1855 Chore: Storybook: Hide legacy icons
  src/packages/core/icon-registry/icon.stories.ts
Labels: storybook

#1844 Feature: Render Property description with Markdown
  package-lock.json
  package.json
  src/external/dompurify/index.ts
  src/libs/formatting-api/formatting.controller.ts
  src/libs/formatting-api/index.ts
  src/libs/formatting-api/localizeAndTransform.function.ts
  src/packages/core/property/property-layout/property-layout.element.ts
  tsconfig.json
  web-test-runner.config.mjs
Labels: type/feature

#1858 Bugfix: Long breadcrumbs hides workspace actions
  src/packages/core/workspace/components/workspace-breadcrumb/workspace-variant-menu-breadcrumb/workspace-variant-menu-breadcrumb.element.ts
  src/packages/core/workspace/components/workspace-footer/workspace-footer.element.ts
Labels: type/bug

#1831 Bugfix: Await Property Value Changes + Block Grid Editor fixes
  examples/workspace-context-counter/counter-workspace-context.ts
  package-lock.json
  package.json
  src/libs/element-api/element.test.ts
  src/libs/observable-api/states/array-state.ts
  src/libs/observable-api/states/basic-state.ts
  src/libs/observable-api/states/deep-state.ts
  src/libs/observable-api/states/object-state.test.ts
  src/libs/observable-api/states/object-state.ts
  src/packages/block/block-grid/components/block-grid-entries/block-grid-entries.element.ts
  src/packages/block/block-grid/context/block-grid-entries.context.ts
  src/packages/block/block-grid/context/block-grid-entry.context.ts
  src/packages/block/block-grid/context/block-grid-manager.context.ts
  src/packages/block/block-grid/context/block-grid-scale-manager/block-grid-scale-manager.controller.ts
  src/packages/block/block-grid/property-editors/block-grid-column-span/property-editor-ui-block-grid-column-span.element.ts
  src/packages/block/block-grid/property-editors/block-grid-editor/property-editor-ui-block-grid.element.ts
  src/packages/block/block-list/context/block-list-entries.context.ts
  src/packages/block/block-list/property-editors/block-list-editor/property-editor-ui-block-list.element.ts
  src/packages/block/block/context/block-entries.context.ts
  src/packages/block/block/context/block-entry.context.ts
  src/packages/block/block/context/block-manager.context.ts
  src/packages/block/block/workspace/block-element-manager.ts
  src/packages/block/block/workspace/block-workspace.context.ts
  src/packages/core/property/property/property.context.ts
  src/packages/documents/document-blueprints/property-dataset-context/document-blueprint-property-dataset-context.ts
  src/packages/documents/document-blueprints/workspace/document-blueprint-workspace.context.ts
  src/packages/documents/documents/property-dataset-context/document-property-dataset-context.ts
  src/packages/documents/documents/workspace/document-workspace.context.ts
  src/packages/media/media/property-dataset-context/media-property-dataset-context.ts
  src/packages/media/media/workspace/media-workspace.context.ts
  src/packages/members/member/property-dataset-context/member-property-dataset-context.ts
  src/packages/members/member/workspace/member-workspace.context.ts
Labels: storybook

#1859 Feature: allow wide content in property descriptions
  src/packages/core/property/property-layout/property-layout.element.ts
Labels: type/feature

#1857 Feature: Login should support returnPath
  src/apps/app/app-auth.controller.ts
  src/apps/app/app.element.ts
  src/packages/core/utils/index.ts
  src/packages/core/utils/path/ensure-local-path.function.test.ts
  src/packages/core/utils/path/ensure-local-path.function.ts
  src/packages/core/utils/path/stored-path.function.test.ts
  src/packages/core/utils/path/stored-path.function.ts
Labels: type/feature

#1870 use scroll container for actions modal
  src/packages/core/section/section-sidebar-context-menu/section-sidebar-context-menu.element.ts
Labels: type/bug

#1867 Bugfix: Collection: determine if `filter.skip` has preconfigured value
  src/packages/core/collection/default/collection-default.context.ts
Labels: type/bug

#1872 Bugfix: Document Picker: Ensures `max = 1`
  src/packages/documents/documents/property-editors/document-picker/property-editor-ui-document-picker.element.ts
Labels: type/bug

#1877 Bugfix: Add missing EN translations
  src/assets/lang/en.ts
Labels: type/bug

#1873 Bugfix: Picker inputs - moved `addValidator()` calls to `constructor()`
  src/packages/core/components/input-entity/input-entity.element.ts
  src/packages/documents/documents/components/input-document/input-document.element.ts
  src/packages/members/member-group/components/input-member-group/input-member-group.element.ts
  src/packages/members/member/components/input-member/input-member.element.ts
Labels: type/bug

#1878 RTE plugins localization
  src/assets/lang/da-dk.ts
  src/assets/lang/en-us.ts
  src/assets/lang/en.ts
  src/packages/multi-url-picker/tiny-mce-plugin/tiny-mce-multi-url-picker.plugin.ts
  src/packages/tiny-mce/plugins/tiny-mce-code-editor.plugin.ts
  src/packages/tiny-mce/plugins/tiny-mce-embeddedmedia.plugin.ts
  src/packages/tiny-mce/plugins/tiny-mce-mediapicker.plugin.ts
Labels: type/feature

#1879 Bugfix: Property descriptions should use uui-scroll-container
  src/packages/core/property/property-layout/property-layout.element.ts
Labels: type/bug

#1885 Bugfix: Fix tree folder cyclic imports
  src/packages/core/tree/folder/entity-action/create-folder/create-folder.action.ts
  src/packages/core/tree/folder/entity-action/delete-folder/delete-folder.action.ts
  src/packages/core/tree/folder/entity-action/update-folder/update-folder.action.ts
Labels: type/bug

#1884 Bugfix: Move upload field and component
  src/packages/core/components/index.ts
  src/packages/media/entry-point.ts
  src/packages/media/manifests.ts
  src/packages/media/media/components/index.ts
  src/packages/media/media/components/input-upload-field/index.ts
  src/packages/media/media/components/input-upload-field/input-upload-field-audio.element.ts
  src/packages/media/media/components/input-upload-field/input-upload-field-file.element.ts
  src/packages/media/media/components/input-upload-field/input-upload-field-image.element.ts
  src/packages/media/media/components/input-upload-field/input-upload-field-svg.element.ts
  src/packages/media/media/components/input-upload-field/input-upload-field-video.element.ts
  src/packages/media/media/components/input-upload-field/input-upload-field.element.ts
  src/packages/media/media/components/input-upload-field/input-upload-field.stories.ts
  src/packages/media/media/index.ts
  src/packages/media/media/property-editors/index.ts
  src/packages/media/media/property-editors/manifests.ts
  src/packages/media/media/property-editors/upload-field/Umbraco.UploadField.ts
  src/packages/media/media/property-editors/upload-field/index.ts
  src/packages/media/media/property-editors/upload-field/manifests.ts
  src/packages/media/media/property-editors/upload-field/property-editor-ui-upload-field.element.ts
  src/packages/media/media/property-editors/upload-field/property-editor-ui-upload-field.stories.ts
  src/packages/media/media/property-editors/upload-field/property-editor-ui-upload-field.test.ts
  src/packages/media/media/property-editors/upload-field/types.ts
  src/packages/media/umbraco-package.ts
  src/packages/property-editors/manifests.ts
Labels: category/breaking

#1887 Bugfix: Restore custom validation on property editors
  src/assets/lang/en.ts
  src/packages/core/content-type/modals/property-type-settings/property-type-settings-modal.element.ts
Labels: type/bug

#1889 fix: the backoffice does not work with window.open
  src/apps/app/app.element.ts
  src/packages/core/utils/index.ts
  src/packages/core/utils/path/has-own-opener.function.test.ts
  src/packages/core/utils/path/has-own-opener.function.ts
Labels: type/bug

#1894 Bugfix: Media Collection (Section View) missing layouts
  src/packages/media/media/section-view/media-section-view.element.ts
Labels: type/bug

#1892 Bugfix: modal route registration circular dependency
  src/packages/block/block-grid/context/block-grid-entries.context.ts
  src/packages/block/block-grid/property-editors/block-grid-areas-config/property-editor-ui-block-grid-areas-config.element.ts
  src/packages/block/block-grid/property-editors/block-grid-type-configuration/property-editor-ui-block-grid-type-configuration.element.ts
  src/packages/block/block-list/context/block-list-entries.context.ts
  src/packages/block/block-list/property-editors/block-list-editor/property-editor-ui-block-list.element.ts
  src/packages/block/block-list/property-editors/block-list-type-configuration/property-editor-ui-block-list-type-configuration.element.ts
  src/packages/block/block-type/components/input-block-type/input-block-type.element.ts
  src/packages/block/block/context/block-entries.context.ts
  src/packages/block/block/modals/block-catalogue/block-catalogue-modal.element.ts
  src/packages/core/collection/index.ts
  src/packages/core/components/input-collection-configuration/input-collection-configuration.element.ts
  src/packages/core/content-type/workspace/views/design/content-type-design-editor-properties.element.ts
  src/packages/core/content-type/workspace/views/design/content-type-design-editor-property.element.ts
  src/packages/core/content-type/workspace/views/design/content-type-design-editor-tab.element.ts
  src/packages/core/modal/context/index.ts
  src/packages/core/modal/index.ts
  src/packages/core/router/index.ts
  src/packages/core/router/modal-registration/modal-route-registration.controller.ts
  src/packages/core/router/modal-registration/modal-route-registration.interface.ts
  src/packages/core/router/route.context.ts
  src/packages/core/tree/tree-picker/tree-picker-modal.element.ts
  src/packages/data-type/components/data-type-flow-input/data-type-flow-input.element.ts
  src/packages/data-type/modals/data-type-picker-flow/data-type-picker-flow-modal.element.ts
  src/packages/documents/document-types/components/input-document-type/input-document-type.element.ts
  src/packages/documents/documents/collection/action/create-document-collection-action.element.ts
  src/packages/documents/documents/collection/views/grid/document-grid-collection-view.element.ts
  src/packages/documents/documents/collection/views/table/document-table-collection-view.element.ts
  src/packages/documents/documents/components/input-document/input-document.element.ts
  src/packages/documents/documents/workspace/views/info/document-workspace-view-info-reference.element.ts
  src/packages/documents/documents/workspace/views/info/document-workspace-view-info.element.ts
  src/packages/media/media-types/components/input-media-type/input-media-type.element.ts
  src/packages/media/media/collection/action/create-media-collection-action.element.ts
  src/packages/media/media/collection/views/grid/media-grid-collection-view.element.ts
  src/packages/media/media/collection/views/table/media-table-collection-view.element.ts
  src/packages/media/media/components/input-media/input-media.element.ts
  src/packages/media/media/workspace/views/info/media-workspace-view-info-reference.element.ts
  src/packages/media/media/workspace/views/info/media-workspace-view-info.element.ts
  src/packages/members/member-group/components/input-member-group/input-member-group.element.ts
  src/packages/members/member/components/input-member/input-member.element.ts
  src/packages/members/member/workspace/views/member/member-workspace-view-member-info.element.ts
  src/packages/multi-url-picker/multi-url-picker/multi-url-picker.element.ts
  src/packages/search/examine-management-dashboard/views/section-view-examine-searchers.ts
  src/packages/templating/templates/components/input-template/input-template.element.ts
Labels: category/breaking

#1853 Feature: Media Picker - Image crop editor modal
  src/packages/media/imaging/imaging.repository.ts
  src/packages/media/media/components/index.ts
  src/packages/media/media/components/input-image-cropper/image-cropper-field.element.ts
  src/packages/media/media/components/input-image-cropper/image-cropper-focus-setter.element.ts
  src/packages/media/media/components/input-media/input-media.context.ts
  src/packages/media/media/components/input-media/input-media.element.ts
  src/packages/media/media/components/input-rich-media/index.ts
  src/packages/media/media/components/input-rich-media/input-rich-media.element.ts
  src/packages/media/media/dropzone/dropzone.element.ts
  src/packages/media/media/modals/image-cropper-editor/image-cropper-editor-modal.element.ts
  src/packages/media/media/modals/image-cropper-editor/image-cropper-editor-modal.token.ts
  src/packages/media/media/modals/image-cropper-editor/index.ts
  src/packages/media/media/modals/image-cropper-editor/manifests.ts
  src/packages/media/media/modals/index.ts
  src/packages/media/media/modals/manifests.ts
  src/packages/media/media/modals/media-picker/media-picker-modal.element.ts
  src/packages/media/media/modals/media-picker/media-picker-modal.token.ts
  src/packages/media/media/modals/media-picker/types.ts
  src/packages/media/media/property-editors/media-picker/components/index.ts
  src/packages/media/media/property-editors/media-picker/components/input-rich-media/index.ts
  src/packages/media/media/property-editors/media-picker/components/input-rich-media/input-rich-media.element.ts
  src/packages/media/media/property-editors/media-picker/index.ts
  src/packages/media/media/property-editors/media-picker/property-editor-ui-media-picker.element.ts
Labels: type/feature

#1904 Bugfix: Media Workspace Info details
  src/packages/media/media/workspace/views/info/media-workspace-view-info.element.ts
Labels: type/bug

#1900 Feature: Markdown Editor: Wired up media URLs
  src/packages/markdown-editor/components/input-markdown-editor/input-markdown.element.ts
Labels: type/feature

#1895 Bugfix: Audit log are missing a few translations
  src/assets/lang/en.ts
  src/packages/documents/documents/workspace/views/info/document-workspace-view-info-history.element.ts
  src/packages/documents/documents/workspace/views/info/utils.ts
  src/packages/media/media/workspace/views/info/media-workspace-view-info-history.element.ts
Labels: type/bug

#1897 Feature: Extendable section routes
  src/packages/core/extension-registry/models/index.ts
  src/packages/core/extension-registry/models/section-route.model.ts
  src/packages/core/router/index.ts
  src/packages/core/router/types.ts
  src/packages/core/section/section-default.element.ts
  src/packages/core/utils/path/path-encode.function.ts
  src/packages/core/workspace/manifests.ts
  src/packages/core/workspace/section-routes/manifests.ts
  src/packages/core/workspace/section-routes/workspace-section-route.route-entry.ts
Labels: type/feature

#1907 Add placeholder to name input
  src/packages/core/components/input-with-alias/input-with-alias.element.ts
  src/packages/documents/document-types/workspace/document-type-workspace-editor.element.ts
  src/packages/media/media-types/workspace/media-type-workspace-editor.element.ts
  src/packages/members/member-type/workspace/member-type-workspace-editor.element.ts
  src/packages/user/user-group/workspace/user-group-workspace-editor.element.ts
Labels: community/pr, type/bug

#1914 Bugfix: Media info links, corrected localization for no links
  src/packages/media/media/workspace/views/info/media-workspace-view-info.element.ts
Labels: type/bug

#1915 Bugfix: Document Type: History Cleanup UI
  src/packages/documents/document-types/workspace/document-type-workspace.context.ts
  src/packages/documents/document-types/workspace/views/settings/document-type-workspace-view-settings.element.ts
Labels: type/bug

#1916 Bugfix: Public Access, corrected Member Group picker
  src/packages/documents/documents/entity-actions/public-access/modal/public-access-modal.element.ts
Labels: type/bug

#1902 Chore: Lee's code sweep (for RC5)
  src/packages/core/components/multiple-text-string-input/input-multiple-text-string-item.element.ts
  src/packages/core/components/multiple-text-string-input/input-multiple-text-string.element.ts
  src/packages/core/menu/components/menu-item/menu-item-default.element.ts
  src/packages/core/menu/components/menu/menu.element.ts
  src/packages/documents/documents/components/input-document/input-document.element.ts
  src/packages/markdown-editor/components/input-markdown-editor/input-markdown.element.ts
  src/packages/markdown-editor/property-editors/markdown-editor/property-editor-ui-markdown-editor.element.ts
  src/packages/media/media/collection/views/grid/media-grid-collection-view.element.ts
  src/packages/media/media/components/input-media/input-media.element.ts
  src/packages/media/media/components/input-rich-media/input-rich-media.element.ts
  src/packages/media/media/property-editors/media-picker/property-editor-ui-media-picker.element.ts
  src/packages/multi-url-picker/monaco-markdown-editor-action/url-picker-monaco-markdown-editor-action.ts
  src/packages/multi-url-picker/property-editor/property-editor-ui-multi-url-picker.element.ts
  src/packages/property-editors/multiple-text-string/property-editor-ui-multiple-text-string.element.ts
  src/packages/property-editors/slider/property-editor-ui-slider.element.ts
  src/packages/property-editors/textarea/property-editor-ui-textarea.element.ts
  src/packages/property-editors/toggle/property-editor-ui-toggle.element.ts
  src/packages/user/current-user/theme/current-user-theme-user-profile-app.element.ts
  src/packages/user/user/components/user-input/user-input.element.ts
Labels: type/bug

#1920 Bugfix: Document workspace info, fixes document type modal
  src/packages/documents/documents/workspace/views/info/document-workspace-view-info.element.ts
Labels: type/bug

#1922 Bugfix: Initial section
  src/apps/backoffice/backoffice.context.ts
  src/apps/backoffice/components/backoffice-main.element.ts
  src/packages/user/current-user/current-user.context.ts
Labels: type/bug

#1925 Feature: Allow conditional trees
  src/packages/core/extension-registry/models/tree.model.ts
Labels: type/feature

#1926 Bugfix: Static file picker
  src/packages/block/block-grid/property-editors/block-grid-layout-stylesheet/property-editor-ui-block-grid-layout-stylesheet.element.ts
  src/packages/static-file/components/input-static-file/input-static-file.context.ts
  src/packages/static-file/components/input-static-file/input-static-file.element.ts
  src/packages/static-file/modals/static-file-picker-modal.token.ts
  src/packages/static-file/repository/item/static-file-item.server.data-source.ts
Labels: type/bug

#1923 Bugfix: Close global search on outside click
  src/packages/search/search-modal/search-modal.element.ts
Labels: type/bug

#1924 Bugfix: Add navigation tips to global search
  src/assets/lang/da-dk.ts
  src/assets/lang/en.ts
  src/packages/search/search-modal/search-modal.element.ts
Labels: type/bug

#1930 Feature: Document Type Descriptions
  src/packages/documents/document-types/workspace/document-type-workspace-editor.element.ts
  src/packages/documents/documents/entity-actions/create/document-create-options-modal.element.ts
Labels: type/feature

#1932 Feature: Media Type Descriptions
  src/packages/media/media-types/workspace/media-type-workspace-editor.element.ts
  src/packages/media/media/entity-actions/create/media-create-options-modal.element.ts
Labels: type/feature

#1933 Feature: Member Type Descriptions
  src/packages/members/member-type/workspace/member-type-workspace-editor.element.ts
Labels: type/feature

#1911 Feature: DataType tracked references
  src/external/backend-api/src/models.ts
  src/mocks/data/media-type/media-type.data.ts
  src/mocks/data/media-type/media-type.db.ts
  src/packages/data-type/reference/index.ts
  src/packages/data-type/reference/manifests.ts
  src/packages/data-type/reference/repository/data-type-reference.repository.ts
  src/packages/data-type/reference/repository/data-type-reference.server.data.ts
  src/packages/data-type/reference/repository/index.ts
  src/packages/data-type/reference/repository/manifests.ts
  src/packages/data-type/workspace/views/info/data-type-workspace-view-info-reference.element.ts
  src/packages/data-type/workspace/views/info/workspace-view-data-type-info.element.ts
Labels: type/feature

#1938 fix: turn off generated url encoding for `OpenAPI`
  src/apps/app/app.element.ts
  src/packages/core/auth/auth.context.ts
  src/packages/core/auth/models/openApiConfiguration.ts
Labels: type/bug

#1940 Bugfix: Search results for data types
  src/packages/data-type/modals/data-type-picker-flow/data-type-picker-flow-modal.element.ts
Labels: type/bug

#1939 fix inserting block only at the right spot
  src/packages/block/block-grid/context/block-grid-manager.context.ts
  src/packages/block/block-grid/workspace/block-grid-workspace.modal-token.ts
  src/packages/block/block-list/workspace/block-list-workspace.modal-token.ts
  src/packages/block/block/context/block-manager.context.ts
  src/packages/block/block/workspace/block-workspace.context.ts
Labels: type/bug

#1941 Fix: editing block in Area
  src/packages/block/block-grid/context/block-grid-entries.context.ts
  src/packages/block/block-list/context/block-list-entries.context.ts
  src/packages/block/block-rte/context/block-rte-entries.context.ts
  src/packages/block/block-rte/workspace/block-rte-workspace.modal-token.ts
  src/packages/block/block/context/block-entries.context.ts
  src/packages/block/block/workspace/block-workspace.context.ts
Labels: type/bug

#1944 Bugfix: Fix render of documenttype routing in info tab
  src/packages/documents/documents/workspace/views/info/document-workspace-view-info.element.ts
Labels: type/bug

#1946 Chore: Use import aliases for imports in dictionary picker modal
  src/packages/dictionary/modals/dictionary-picker-modal.token.ts
Labels: type/bug

#1945 Bugfix: Clean up event listeners when collection context is destroyed
  src/packages/core/collection/collection.element.ts
  src/packages/core/collection/default/collection-default.context.ts
  src/packages/core/extension-registry/collection/repository/extension-collection.repository.ts
  src/packages/core/extension-registry/extension-element-and-api-slot-element-base.ts
  src/packages/data-type/collection/repository/data-type-collection.repository.ts
  src/packages/dictionary/collection/repository/dictionary-collection.repository.ts
  src/packages/documents/documents/collection/repository/document-collection.repository.ts
  src/packages/language/collection/repository/language-collection.repository.ts
  src/packages/media/media/collection/repository/media-collection.repository.ts
  src/packages/members/member-group/collection/repository/member-group-collection.repository.ts
  src/packages/relations/relation-types/collection/repository/relation-type-collection.repository.ts
  src/packages/relations/relations/collection/repository/relation-collection.repository.ts
  src/packages/webhook/collection/repository/webhook-collection.repository.ts
Labels: type/bug

#1948 Feature: Hide focalpoint in ImageCropper
  src/packages/media/media/components/input-image-cropper/image-cropper-field.element.ts
  src/packages/media/media/components/input-image-cropper/image-cropper-focus-setter.element.ts
Labels: type/feature

#1951 Bugfix: Image Cropper, focal point reset
  src/packages/media/media/components/input-image-cropper/image-cropper-field.element.ts
  src/packages/media/media/components/input-image-cropper/image-cropper-focus-setter.element.ts
  src/packages/media/media/modals/image-cropper-editor/image-cropper-editor-modal.element.ts
Labels: type/bug

#1953 The document `Custom` status is not translated correctly
  devops/localization/unused-language-keys.js
  src/packages/documents/documents/workspace/views/info/utils.ts
Labels: type/bug

#1950 Feat: expose uniques and aliases in structure manager
  src/packages/core/content-type/structure/content-type-structure-manager.class.ts
Labels: type/feature

#1954 V14/bugfix/bad slider configuration
  src/packages/property-editors/slider/Umbraco.Slider.ts
  src/packages/property-editors/slider/manifests.ts
  src/packages/property-editors/slider/property-editor-ui-slider.element.ts
Labels: type/bug

#1955 Bugfix: Redirects the Partial View on Create
  src/packages/templating/partial-views/workspace/partial-view-workspace.context.ts
Labels: type/bug

#1943 Chore: EsLint Rule No relative import to import map module
  .eslintrc.json
  devops/eslint/rules/no-relative-import-to-import-map-module.cjs
  eslint-local-rules.cjs
  src/libs/class-api/class.interface.ts
  src/libs/class-api/context-base.class.ts
  src/libs/class-api/context.interface.ts
  src/libs/class-api/controller-base.class.ts
  src/libs/controller-api/controller-host.mixin.ts
  src/libs/element-api/element.interface.ts
  src/packages/property-editors/collection/property-editor-ui-collection.element.ts
  src/packages/property-editors/date-picker/property-editor-ui-date-picker.element.ts
  src/packages/property-editors/multiple-text-string/property-editor-ui-multiple-text-string.element.ts
  src/packages/property-editors/number-range/property-editor-ui-number-range.element.ts
  src/packages/property-editors/radio-button-list/property-editor-ui-radio-button-list.element.ts
  src/packages/property-editors/slider/property-editor-ui-slider.element.ts
  src/packages/property-editors/toggle/property-editor-ui-toggle.element.ts
  src/packages/tiny-mce/components/input-tiny-mce/input-tiny-mce.element.ts
  web-test-runner.config.mjs
Labels: storybook

#1956 Bugfix: Document Type Workspace, localizes the name and alias input placeholders
  src/packages/core/components/input-with-alias/input-with-alias.element.ts
  src/packages/documents/document-types/workspace/document-type-workspace-editor.element.ts
  src/packages/media/media-types/workspace/media-type-workspace-editor.element.ts
  src/packages/members/member-type/workspace/member-type-workspace-editor.element.ts
  src/packages/user/user-group/workspace/user-group-workspace-editor.element.ts
Labels: type/bug

#1960 Bugfix: Media workspace info references correct localization
  src/packages/media/media/workspace/views/info/media-workspace-view-info-reference.element.ts
Labels: type/bug

#1963 Bugfix: Only render folders for move media type
  src/packages/media/media-types/entity-actions/move-to/manifests.ts
  src/packages/media/media-types/tree/media-type-tree.server.data-source.ts
Labels: type/bug

#1968 Bugfix: Add sidebar bottom space
  src/packages/core/section/section-sidebar/section-sidebar.element.ts
Labels: type/bug

#1967 Bugfix: Focus folder name input
  src/packages/core/tree/folder/modal/folder-modal-element-base.ts
Labels: type/bug

#1966 Feature: implement folders only for duplicate to
  src/packages/core/extension-registry/models/entity-action.model.ts
  src/packages/core/tree/entity-actions/duplicate-to/duplicate-to.action.ts
  src/packages/core/tree/entity-actions/duplicate-to/modal/duplicate-to-modal.element.ts
  src/packages/core/tree/entity-actions/duplicate-to/modal/duplicate-to-modal.token.ts
  src/packages/data-type/entity-actions/duplicate/manifests.ts
  src/packages/documents/document-types/entity-actions/duplicate/manifests.ts
  src/packages/media/media-types/entity-actions/duplicate/manifests.ts
Labels: type/feature, type/bug

#1969 Server models 2024-05-31
  src/external/backend-api/src/models.ts
  src/external/backend-api/src/services.ts
  src/packages/documents/document-blueprints/repository/detail/document-blueprint-detail.server.data-source.ts
Labels: ignore-for-release

#1970 Bugfix: Remove of in translation
  src/assets/lang/en-us.ts
  src/assets/lang/en.ts
Labels: type/bug
