Repository umbraco/Umbraco.CMS.Backoffice, pull requests merged in 2024-06, with the labels that each got.

#1979 Bugfix: TinyMCE does not show its box-shadow
  src/packages/tiny-mce/components/input-tiny-mce/input-tiny-mce.element.ts
Labels: type/bug

#1978 Feature: TinyMce Custom Configuration
  public-assets/App_Plugins/tinyMcePlugin.js
  src/mocks/handlers/manifests.handlers.ts
  src/packages/core/extension-registry/models/tinymce-plugin.model.ts
  src/packages/tiny-mce/components/input-tiny-mce/input-tiny-mce.element.ts
Labels: type/feature

#1983 Bugfix: Close context menu before executing primary action
  src/packages/core/components/entity-actions-bundle/entity-actions-bundle.element.ts
Labels: type/bug

#1989 Makes the styles optional in stylesheets
  src/packages/templating/stylesheets/components/stylesheet-rule-input/stylesheet-rule-settings-modal.element.ts
  src/packages/templating/stylesheets/utils/stylesheet-rule-manager.ts
Labels: type/bug

#1988 Bugfix: Workspace breadcrumbs, error when new at root
  src/packages/core/menu/menu-tree-structure-workspace-context-base.ts
Labels: type/bug

#1990 Bugfix: Disable duplicate button when nothing is selected
  src/packages/core/tree/entity-actions/duplicate-to/modal/duplicate-to-modal.element.ts
  src/packages/documents/documents/entity-actions/duplicate/modal/duplicate-document-modal.element.ts
Labels: type/bug

#1993 Bugfix: Tinymce allows potentially unsafe embeds
  src/packages/tiny-mce/components/input-tiny-mce/input-tiny-mce.element.ts
Labels: type/bug

#1992 Bugfix: Add missing edit permissions for create options modals
  src/packages/documents/documents/entity-actions/create/document-create-options-modal.element.ts
  src/packages/media/media/entity-actions/create/media-create-options-modal.element.ts
Labels: type/bug

#1985 Bugfix: Document Public Access cancelled server requests
  src/assets/lang/en-us.ts
  src/assets/lang/en.ts
  src/packages/documents/documents/entity-actions/public-access/manifests.ts
  src/packages/documents/documents/entity-actions/public-access/modal/public-access-modal.element.ts
  src/packages/documents/documents/entity-actions/public-access/public-access.action.ts
  src/packages/documents/documents/entity-actions/public-access/repository/public-access.repository.ts
  src/packages/documents/documents/tree/tree-item/document-tree-item.element.ts
Labels: type/bug

#2004 Bugfix: Query Builder sending previous data
  src/packages/templating/templates/modals/query-builder/query-builder-filter.element.ts
Labels: type/bug

#2003 Improved example + minor code refactor
  examples/sorter-with-nested-containers/sorter-dashboard.ts
  examples/sorter-with-nested-containers/sorter-group.ts
  src/packages/core/sorter/sorter.controller.ts
Labels: category/documentation

#1999 fix: Issue 1170 - Markdown editor is not responsive
  src/packages/markdown-editor/components/input-markdown-editor/input-markdown.element.ts
Labels: type/bug

#2020 Bugfix: Custom menu item label ellipsis
  src/packages/documents/documents/tree/tree-item/document-tree-item.element.ts
  src/packages/media/media/tree/tree-item/media-tree-item.element.ts
Labels: type/bug

#2021 Feature: Split panel keyboard navigation
  src/packages/core/components/split-panel/split-panel.element.ts
Labels: type/feature

#2027 Feature: Readonly mode for Text Box Property Editor UI
  src/packages/property-editors/text-box/property-editor-ui-text-box.element.ts
Labels: type/feature

#1976 Block Grid: Correct settings data if config changed
  src/libs/context-api/consume/context-consumer.test.ts
  src/packages/block/block-grid/components/block-grid-block-inline/block-grid-inline-property-dataset.context.ts
  src/packages/block/block/context/block-entries.context.ts
  src/packages/block/block/context/block-entry.context.ts
  src/packages/block/block/context/block-manager.context.ts
  src/packages/block/block/types.ts
  src/packages/block/block/workspace/block-workspace.context.ts
  src/packages/core/property/property-dataset/property-dataset.element.test.ts
  src/packages/core/utils/pagination-manager/pagination.manager.test.ts
  src/packages/core/utils/string/split-string-to-array.ts
  src/packages/documents/document-types/components/input-document-type/input-document-type.element.ts
  src/packages/documents/document-types/property-editors/document-type-picker/property-editor-ui-document-type-picker.element.ts
Labels: type/bug, storybook

#2034 Upgrade to typescript 5.5
  package-lock.json
  package.json
Labels: dependencies, internal

#2019 Chore: Bundle Block Package
  package-lock.json
  package.json
  src/packages/block/package.json
  src/packages/block/vite.config.ts
Labels: type/feature

#2023 Switch class to "Tab" when in sort mode
  src/packages/core/content-type/workspace/views/design/content-type-design-editor.element.ts
Labels: type/bug

#2035 Bugfix: Block types do not show their descriptions
  src/packages/block/block-type/components/block-type-card/block-type-card.element.ts
  src/packages/documents/document-types/repository/item/document-type-item.server.data-source.ts
  src/packages/documents/document-types/repository/item/types.ts
Labels: type/bug

#2036 Make allowAtRoot preset for Block Grid Types
  src/packages/block/block-grid/components/block-grid-area-config-entry/workspace/block-grid-area-type-workspace.context.ts
  src/packages/block/block-grid/property-editors/block-grid-type-configuration/property-editor-ui-block-grid-type-configuration.element.ts
  src/packages/block/block-grid/workspace/block-grid-type-workspace.modal-token.ts
  src/packages/block/block-grid/workspace/block-grid-workspace.modal-token.ts
  src/packages/block/block-grid/workspace/index.ts
  src/packages/block/block-list/workspace/block-list-workspace.modal-token.ts
  src/packages/block/block-rte/workspace/block-rte-workspace.modal-token.ts
  src/packages/block/block-type/workspace/block-type-workspace.context.ts
  src/packages/block/block/workspace/block-workspace.modal-token.ts
  src/packages/core/modal/context/modal.context.ts
  src/packages/data-type/workspace/data-type-workspace.modal-token.ts
  src/packages/documents/document-types/workspace/document-type-workspace.modal-token.ts
  src/packages/language/workspace/language/language-workspace.modal-token.ts
Labels: type/bug

#2042 Bugfix: Remove image card when trashed outside a property editor
  src/packages/media/media/components/input-media/input-media.element.ts
Labels: type/bug

#2037 V14/feature/media picker cropper editor modal UI
  src/packages/media/media/components/input-image-cropper/image-cropper-field.element.ts
  src/packages/media/media/components/input-image-cropper/image-cropper-preview.element.ts
  src/packages/media/media/modals/image-cropper-editor/components/image-cropper-editor-field.element.ts
  src/packages/media/media/modals/image-cropper-editor/components/index.ts
  src/packages/media/media/modals/image-cropper-editor/image-cropper-editor-modal.element.ts
  src/packages/media/media/modals/image-cropper-editor/index.ts
Labels: type/feature

#1998 Bugfix: Installer does not take the minimum password length into account
  src/apps/installer/user/installer-user.element.ts
Labels: community/pr, type/bug

#2028 Feature: Readonly mode for Text Area Property Editor UI
  src/packages/property-editors/textarea/property-editor-ui-textarea.element.ts
Labels: type/feature

#2010 Bugfix: Render calculated user start nodes in User Workspace
  src/external/backend-api/src/models.ts
  src/external/backend-api/src/services.ts
  src/mocks/data/user/user.db.ts
  src/packages/core/repository/detail/detail-data-source.interface.ts
  src/packages/core/repository/detail/detail-repository-base.ts
  src/packages/user/user/components/user-document-start-node/user-document-start-node.element.ts
  src/packages/user/user/components/user-media-start-node/user-media-start-node.element.ts
  src/packages/user/user/repository/detail/types.ts
  src/packages/user/user/repository/detail/user-detail.repository.ts
  src/packages/user/user/repository/detail/user-detail.server.data-source.ts
  src/packages/user/user/types.ts
  src/packages/user/user/workspace/components/user-workspace-access/user-workspace-access.element.ts
  src/packages/user/user/workspace/user-workspace.context.ts
Labels: type/bug

#2045 Feature: Umbraco Flavored Markdown
  package.json
  src/apps/backoffice/backoffice.element.ts
  src/libs/context-api/consume/context-consumer.test.ts
  src/libs/formatting-api/formatting.controller.ts
  src/libs/formatting-api/localizeAndTransform.function.ts
  src/packages/block/block-grid/components/block-grid-block/block-grid-block.element.ts
  src/packages/block/block-list/components/ref-list-block/ref-list-block.element.ts
  src/packages/core/components/table/table.element.ts
  src/packages/core/extension-registry/models/index.ts
  src/packages/core/extension-registry/models/ufm-component.model.ts
  src/packages/core/localization/localize.element.ts
  src/packages/core/property/property-dataset/property-dataset.element.test.ts
  src/packages/core/property/property-layout/property-layout.element.ts
  src/packages/core/utils/pagination-manager/pagination.manager.test.ts
  src/packages/documents/documents/collection/views/grid/document-grid-collection-view.element.ts
  src/packages/documents/documents/collection/views/table/document-table-collection-view.element.ts
  src/packages/property-editors/collection/config/column/column-configuration.element.ts
  src/packages/ufm/components/ufm-render/index.ts
  src/packages/ufm/components/ufm-render/ufm-render.context.ts
  src/packages/ufm/components/ufm-render/ufm-render.element.ts
  src/packages/ufm/index.ts
  src/packages/ufm/manifests.ts
  src/packages/ufm/plugins/marked-ufm.plugin.ts
  src/packages/ufm/ufm-components/document-name.component.ts
  src/packages/ufm/ufm-components/document-name.element.ts
  src/packages/ufm/ufm-components/label-value.component.ts
  src/packages/ufm/ufm-components/label-value.element.ts
  src/packages/ufm/ufm-components/localize.component.ts
  src/packages/ufm/ufm-components/ufm-component-base.ts
  src/packages/ufm/umbraco-package.ts
  tsconfig.json
Labels: type/feature

#2049 Bugfix: Package Builder import errors
  src/packages/data-type/components/data-type-flow-input/data-type-flow-input.element.ts
  src/packages/data-type/components/data-type-input/index.ts
  src/packages/data-type/components/index.ts
  src/packages/dictionary/components/index.ts
  src/packages/dictionary/components/input-dictionary/index.ts
  src/packages/dictionary/index.ts
  src/packages/packages/package-builder/workspace/workspace-package-builder.element.ts
  src/packages/templating/partial-views/components/index.ts
  src/packages/templating/partial-views/components/input-partial-view/index.ts
  src/packages/templating/partial-views/index.ts
  src/packages/templating/scripts/components/index.ts
  src/packages/templating/scripts/components/input-script/index.ts
  src/packages/templating/scripts/index.ts
  src/packages/templating/stylesheets/components/index.ts
  src/packages/templating/stylesheets/components/stylesheet-input/index.ts
  src/packages/templating/stylesheets/index.ts
  src/packages/templating/templates/components/index.ts
  src/packages/templating/templates/components/input-template/index.ts
Labels: type/bug

#2062 Hotfix: Propagate data changes for Block Grid Area Types
  src/packages/block/block-grid/components/block-grid-area-config-entry/block-grid-area-config-entry.context.ts
Labels: type/bug
