Repository umbraco/Umbraco.CMS.Backoffice, pull requests merged in 2024-07, with the labels that each got.

#2063 [FIX] Scroll Bar / Panel Width Adjustment cursor
  src/packages/core/components/split-panel/split-panel.element.ts
Labels: community/pr, type/bug

#2069 Bugfix: Render collection icon for document/media tree items
  src/packages/documents/documents/tree/tree-item/document-tree-item.element.ts
  src/packages/media/media/tree/tree-item/media-tree-item.element.ts
Labels: type/bug

#2077 Adds background-color to umb-table header
  src/packages/core/components/table/table.element.ts
Labels: type/bug

#2066 Bugfix: Ensure entity structure is reloaded after publish
  src/packages/documents/documents/workspace/document-workspace.context.ts
Labels: type/bug

#2061 Feature: Route not found + router features
  src/apps/backoffice/components/backoffice-main.element.ts
  src/assets/lang/da-dk.ts
  src/assets/lang/en-us.ts
  src/assets/lang/en.ts
  src/external/router-slot/router-slot.ts
  src/libs/extension-api/controller/base-extension-initializer.controller.ts
  src/libs/observable-api/observer.ts
  src/packages/block/block-grid/components/block-grid-areas-container/block-grid-areas-container.element.ts
  src/packages/block/block-grid/context/block-grid-entry.context.ts
  src/packages/block/block-grid/property-editors/block-grid-areas-config/property-editor-ui-block-grid-areas-config.element.ts
  src/packages/block/block-list/property-editors/block-list-editor/manifests.ts
  src/packages/block/block-type/workspace/block-type-workspace.context.ts
  src/packages/block/block/workspace/manifests.ts
  src/packages/block/block/workspace/views/edit/block-workspace-view-edit.element.ts
  src/packages/core/collection/collection-view.manager.ts
  src/packages/core/components/table/table.element.ts
  src/packages/core/content-type/workspace/views/design/content-type-design-editor.element.ts
  src/packages/core/content/workspace/views/edit/content-editor.element.ts
  src/packages/core/property/property/property.context.ts
  src/packages/core/router/components/not-found/route-not-found.element.ts
  src/packages/core/router/index.ts
  src/packages/core/router/router-slot.element.ts
  src/packages/core/section/section-default.element.ts
  src/packages/core/section/section-main-views/section-main-views.element.ts
  src/packages/core/workspace/components/workspace-editor/workspace-editor.element.ts
  src/packages/core/workspace/components/workspace-split-view/workspace-split-view-variant-selector.element.ts
  src/packages/core/workspace/components/workspace-split-view/workspace-split-view.context.ts
  src/packages/core/workspace/components/workspace-split-view/workspace-split-view.element.ts
  src/packages/core/workspace/controllers/workspace-route-manager.controller.ts
  src/packages/core/workspace/controllers/workspace-split-view-manager.controller.ts
  src/packages/core/workspace/kinds/editable/editable-workspace.element.ts
  src/packages/core/workspace/kinds/editable/editable-workspace.kind.ts
  src/packages/core/workspace/kinds/manifests.ts
  src/packages/data-type/workspace/data-type-workspace.context.ts
  src/packages/data-type/workspace/manifests.ts
  src/packages/dictionary/workspace/dictionary-workspace.context.ts
  src/packages/documents/document-blueprints/workspace/document-blueprint-workspace-editor.element.ts
  src/packages/documents/document-types/workspace/document-type-workspace.context.ts
  src/packages/documents/documents/tree/tree-item/document-tree-item.element.ts
  src/packages/documents/documents/workspace/document-workspace-editor.element.ts
  src/packages/health-check/dashboard-health-check.element.ts
  src/packages/language/workspace/language/language-workspace.context.ts
  src/packages/media/media-types/workspace/media-type-workspace.context.ts
  src/packages/media/media/section-view/media-section-view.element.ts
  src/packages/media/media/workspace/media-workspace-editor.element.ts
  src/packages/members/member-group/section-view/member-group-section-view.element.ts
  src/packages/members/member-group/workspace/member-group-workspace.context.ts
  src/packages/members/member-type/workspace/member-type-workspace.context.ts
  src/packages/members/member/section-view/member-section-view.element.ts
  src/packages/members/member/workspace/member-workspace-editor.element.ts
  src/packages/packages/package-section/views/created/created-packages-section-view.element.ts
  src/packages/search/examine-management-dashboard/dashboard-examine-management.element.ts
  src/packages/templating/partial-views/workspace/partial-view-workspace.context.ts
  src/packages/templating/partial-views/workspace/partial-view-workspace.element.ts
  src/packages/templating/scripts/workspace/script-workspace.context.ts
  src/packages/templating/stylesheets/workspace/stylesheet-workspace.context.ts
  src/packages/templating/templates/workspace/template-workspace.context.ts
  src/packages/user/user-group/section-view/user-group-section-view.element.ts
  src/packages/user/user-group/workspace/user-group-workspace.context.ts
  src/packages/user/user/section-view/users-section-view.element.ts
Labels: type/feature, storybook

#2079 chore: separate the build_test into two different jobs to save time
  .github/workflows/build_test.yml
  src/rollup.config.js
Labels: ignore-for-release, internal

#2081 Chore: Remove unused test
  src/packages/core/workspace/kinds/editable/editable-workspace.test.ts
Labels: ignore-for-release, internal

#2083 Chore: Fix test runner log filter
  web-test-runner.config.mjs
Labels: ignore-for-release, internal

#2082 Bugfix: Add getter for pickerContext in UmbInputEntityElement
  src/packages/core/components/input-entity/input-entity.element.ts
Labels: type/bug

#2087 Bugfix: Add back sidebar context
  src/packages/core/section/section-sidebar/section-sidebar.element.ts
Labels: ignore-for-release, internal

#2091 Chore: Fix failing test: Catch unresolved extension error instead of using timeout
  package.json
  src/packages/core/extension-registry/utils/create-extension-api-by-alias.test.ts
  src/packages/documents/document-redirect-management/dashboard-redirect-management.test.ts
  web-test-runner.config.mjs
Labels: ignore-for-release, internal

#2075 Bugfix: Hide Content Editor workspace view when no properties (Document, Media, Member)
  src/packages/core/content/workspace/content-workspace.context-token.ts
  src/packages/core/content/workspace/index.ts
  src/packages/core/content/workspace/manifests.ts
  src/packages/core/content/workspace/views/edit/conditions/has-properties/constants.ts
  src/packages/core/content/workspace/views/edit/conditions/has-properties/content-has-properties.condition.manifest.ts
  src/packages/core/content/workspace/views/edit/conditions/has-properties/content-has-properties.condition.ts
  src/packages/core/content/workspace/views/edit/conditions/has-properties/index.ts
  src/packages/core/content/workspace/views/edit/conditions/manifests.ts
  src/packages/core/content/workspace/views/edit/index.ts
  src/packages/core/content/workspace/views/edit/manifests.ts
  src/packages/documents/documents/workspace/manifests.ts
  src/packages/media/media/workspace/manifests.ts
  src/packages/members/member/workspace/manifests.ts
Labels: type/bug

#2099 ESLint linebreak on windows
  eslint.config.js
Labels: ignore-for-release, internal

#2065 Feature: Block Custom Views
  src/libs/extension-api/controller/base-extensions-initializer.controller.ts
  src/packages/block/block-grid/components/block-grid-block-inline/block-grid-block-inline.element.ts
  src/packages/block/block-grid/components/block-grid-block/block-grid-block.element.ts
  src/packages/block/block-grid/components/block-grid-entry/block-grid-entry.element.ts
  src/packages/block/block-grid/types.ts
  src/packages/block/block-list/components/block-list-entry/block-list-entry.element.ts
  src/packages/block/block-list/property-editors/block-list-editor/property-editor-ui-block-list.element.ts
  src/packages/block/block-list/property-editors/block-list-type-configuration/property-editor-ui-block-list-type-configuration.element.ts
  src/packages/block/block-list/types.ts
  src/packages/block/block-rte/components/block-rte-entry/block-rte-entry.element.ts
  src/packages/block/block-rte/tiny-mce-plugin/tiny-mce-block-picker.plugin.ts
  src/packages/block/block-rte/types.ts
  src/packages/block/block-type/components/input-block-type/input-block-type.element.ts
  src/packages/block/block-type/types.ts
  src/packages/block/block-type/workspace/block-type-workspace.context.ts
  src/packages/block/block/context/block-entries.context-token.ts
  src/packages/block/block/context/block-entries.context.ts
  src/packages/block/block/context/block-entry.context-token.ts
  src/packages/block/block/context/block-entry.context.ts
  src/packages/block/block/context/block-manager.context.ts
  src/packages/block/block/modals/block-catalogue/block-catalogue-modal.token.ts
  src/packages/block/block/types.ts
  src/packages/block/custom-view/custom-view.element.ts
  src/packages/block/custom-view/manifest.ts
  src/packages/block/manifests.ts
  src/packages/core/extension-registry/components/extension-slot/extension-slot.element.ts
  src/packages/core/extension-registry/components/extension-with-api-slot/extension-with-api-slot.element.ts
  src/packages/core/extension-registry/interfaces/block-editor-custom-view-element.interface.ts
  src/packages/core/extension-registry/interfaces/index.ts
  src/packages/core/extension-registry/models/block-editor-custom-view.model.ts
  src/packages/core/extension-registry/models/entity-action.model.ts
  src/packages/core/utils/index.ts
  src/packages/core/utils/string/string-or-string-array-contains.function.ts
  src/packages/tiny-mce/property-editors/block-configuration/property-editor-ui-block-rte-type-configuration.element.ts
Labels: type/feature, notable

#2101 hotfix: block grid live editing race condition
  src/packages/block/block/workspace/block-workspace.context.ts
Labels: type/bug

#2100 Bugfix: Create new datatype configuration directly
  src/packages/data-type/modals/data-type-picker-flow/data-type-picker-flow-modal.element.ts
Labels: type/bug

#2094 Bugfix: MNTP min/max validation
  src/packages/core/picker-input/picker-input.context.ts
  src/packages/documents/documents/components/input-document/input-document.element.ts
  src/packages/media/media/components/input-media/input-media.element.ts
  src/packages/members/member/components/input-member/input-member.element.ts
  src/packages/members/member/property-editor/member-picker/property-editor-ui-member-picker.element.ts
  src/packages/property-editors/content-picker/components/input-content/input-content.element.ts
  src/packages/property-editors/content-picker/components/input-content/input-content.test.ts
  src/packages/property-editors/content-picker/property-editor-ui-content-picker.element.ts
Labels: type/bug

#2104 Bugfix: Collection View menu close on selection
  src/packages/core/collection/components/collection-view-bundle.element.ts
Labels: type/bug

#2106 Feature: Property label mandatory indicator
  src/packages/core/content-type/components/property-type-based-property/property-type-based-property.element.ts
  src/packages/core/property/property-layout/property-layout.element.ts
  src/packages/core/property/property/property.context.ts
  src/packages/core/property/property/property.element.ts
Labels: type/feature

#2105 V14: The option `usernameIsEmail` is not supported
  src/assets/lang/da-dk.ts
  src/assets/lang/en-us.ts
  src/assets/lang/en.ts
  src/external/backend-api/src/services.gen.ts
  src/external/backend-api/src/types.gen.ts
  src/packages/core/store/index.ts
  src/packages/core/store/store-object-base.ts
  src/packages/user/user/repository/config/constants.ts
  src/packages/user/user/repository/config/index.ts
  src/packages/user/user/repository/config/manifests.ts
  src/packages/user/user/repository/config/user-config.repository.ts
  src/packages/user/user/repository/config/user-config.server.data-source.ts
  src/packages/user/user/repository/config/user-config.store.token.ts
  src/packages/user/user/repository/config/user-config.store.ts
  src/packages/user/user/repository/manifests.ts
  src/packages/user/user/types.ts
  src/packages/user/user/workspace/components/user-workspace-profile-settings/user-workspace-profile-settings.element.ts
  src/packages/user/user/workspace/user-workspace.context.ts
Labels: type/bug

#2107 Bugfix: Resized media urls result in the request path being too long
  src/packages/media/imaging/constants.ts
  src/packages/media/imaging/imaging.repository.ts
  src/packages/media/imaging/imaging.store.token.ts
  src/packages/media/imaging/imaging.store.ts
  src/packages/media/imaging/manifests.ts
  src/packages/media/media/collection/media-collection.context.ts
  src/packages/media/media/modals/media-picker/media-picker-modal.element.ts
Labels: type/bug

#2108 Hotfix: Ensures word-wrap for `<umb-ufm-render>` component
  src/packages/ufm/components/ufm-render/ufm-render.element.ts
Labels: type/bug

#2109 Feature: Imaging thumbnail component to load thumbnails in parallel
  src/packages/media/imaging/components/imaging-thumbnail.element.ts
  src/packages/media/imaging/components/index.ts
  src/packages/media/imaging/imaging.repository.ts
  src/packages/media/imaging/index.ts
  src/packages/media/imaging/types.ts
  src/packages/media/media/collection/media-collection.context.ts
  src/packages/media/media/collection/views/grid/media-grid-collection-view.element.ts
  src/packages/media/media/components/input-media/input-media.element.ts
  src/packages/media/media/components/input-rich-media/input-rich-media.element.ts
  src/packages/media/media/modals/media-picker/media-picker-modal.element.ts
Labels: type/feature

#2110 Test: Enable more FlatConfig ESLint rules
  devops/eslint/rules/no-direct-api-import.cjs
  eslint.config.js
  package-lock.json
  package.json
  src/packages/block/block-rte/components/block-rte-entry/block-rte-entry.element.ts
  src/packages/umbraco-news/umbraco-news-dashboard.element.ts
Labels: ignore-for-release, internal

#2114 Translate package section to español
  src/assets/lang/es-es.ts
Labels: community/pr, type/feature

#2115 Bugfix: Date Picker with only "date" or "time" does not display correctly
  src/packages/property-editors/date-picker/property-editor-ui-date-picker.element.ts
  src/packages/property-editors/date-picker/property-editor-ui-date-picker.test.ts
Labels: type/bug

#2119 Bugfix: Localizes 'sectionSidebarApp' headers
  src/assets/lang/en.ts
  src/packages/core/section/section-sidebar-menu-with-entity-actions/section-sidebar-menu-with-entity-actions.element.ts
  src/packages/core/section/section-sidebar-menu/section-sidebar-menu.element.ts
  src/packages/core/settings/manifests.ts
  src/packages/dictionary/section/manifests.ts
  src/packages/documents/section/manifests.ts
  src/packages/media/media-section/manifests.ts
  src/packages/templating/menu/manifests.ts
Labels: type/bug

#2120 Bugfix: Localizes collection create action labels
  src/packages/core/collection/action/collection-action-button.element.ts
  src/packages/core/collection/types.ts
  src/packages/dictionary/collection/action/manifests.ts
  src/packages/documents/documents/collection/action/create-document-collection-action.element.ts
  src/packages/documents/documents/collection/action/manifests.ts
  src/packages/language/collection/action/manifests.ts
  src/packages/media/media/collection/action/create-media-collection-action.element.ts
  src/packages/webhook/collection/action/manifests.ts
Labels: type/bug, release/14.2.0

#2121 Feature: Entity Bulk Action `moveTo` kind
  src/packages/core/entity-bulk-action/common/index.ts
  src/packages/core/entity-bulk-action/common/move-to/index.ts
  src/packages/core/entity-bulk-action/common/move-to/manifests.ts
  src/packages/core/entity-bulk-action/common/move-to/move-to-repository.interface.ts
  src/packages/core/entity-bulk-action/common/move-to/move-to.action.kind.ts
  src/packages/core/entity-bulk-action/common/move-to/move-to.action.ts
  src/packages/core/entity-bulk-action/common/move-to/types.ts
  src/packages/core/entity-bulk-action/default/default.action.kind.ts
  src/packages/core/entity-bulk-action/default/manifests.ts
  src/packages/core/entity-bulk-action/entity-bulk-action-element.interface.ts
  src/packages/core/entity-bulk-action/entity-bulk-action.element.ts
  src/packages/core/entity-bulk-action/index.ts
  src/packages/core/entity-bulk-action/manifests.ts
  src/packages/core/extension-registry/models/entity-bulk-action.model.ts
  src/packages/core/manifests.ts
  src/packages/media/media/entity-bulk-actions/manifests.ts
  src/packages/media/media/entity-bulk-actions/move-to/index.ts
  src/packages/media/media/entity-bulk-actions/move-to/manifests.ts
  src/packages/media/media/entity-bulk-actions/move-to/repository/constants.ts
  src/packages/media/media/entity-bulk-actions/move-to/repository/index.ts
  src/packages/media/media/entity-bulk-actions/move-to/repository/manifests.ts
  src/packages/media/media/entity-bulk-actions/move-to/repository/move-to.repository.ts
  src/packages/media/media/entity-bulk-actions/move/move.action.ts
  src/packages/media/media/section-view/media-section-view.element.ts
Labels: type/feature

#2122 Feature: Document entity bulk action "move to"
  src/packages/documents/documents/entity-bulk-actions/manifests.ts
  src/packages/documents/documents/entity-bulk-actions/move-to/constants.ts
  src/packages/documents/documents/entity-bulk-actions/move-to/index.ts
  src/packages/documents/documents/entity-bulk-actions/move-to/manifests.ts
  src/packages/documents/documents/entity-bulk-actions/move-to/repository/constants.ts
  src/packages/documents/documents/entity-bulk-actions/move-to/repository/index.ts
  src/packages/documents/documents/entity-bulk-actions/move-to/repository/manifests.ts
  src/packages/documents/documents/entity-bulk-actions/move-to/repository/move-to.repository.ts
Labels: type/feature

#2123 Bugfix: Localizes the Collection view's "Clear" button label
  src/packages/core/collection/components/collection-selection-actions.element.ts
Labels: type/bug

#2125 Feature: Document entity bulk action "duplicate to"
  src/packages/core/entity-bulk-action/common/duplicate-to/duplicate-to-repository.interface.ts
  src/packages/core/entity-bulk-action/common/duplicate-to/duplicate-to.action.kind.ts
  src/packages/core/entity-bulk-action/common/duplicate-to/duplicate-to.action.ts
  src/packages/core/entity-bulk-action/common/duplicate-to/index.ts
  src/packages/core/entity-bulk-action/common/duplicate-to/manifests.ts
  src/packages/core/entity-bulk-action/common/duplicate-to/types.ts
  src/packages/core/entity-bulk-action/common/index.ts
  src/packages/core/entity-bulk-action/manifests.ts
  src/packages/core/extension-registry/models/entity-bulk-action.model.ts
  src/packages/documents/documents/entity-bulk-actions/duplicate-to/index.ts
  src/packages/documents/documents/entity-bulk-actions/duplicate-to/manifests.ts
  src/packages/documents/documents/entity-bulk-actions/duplicate-to/repository/constants.ts
  src/packages/documents/documents/entity-bulk-actions/duplicate-to/repository/duplicate-to.repository.ts
  src/packages/documents/documents/entity-bulk-actions/duplicate-to/repository/index.ts
  src/packages/documents/documents/entity-bulk-actions/duplicate-to/repository/manifests.ts
  src/packages/documents/documents/entity-bulk-actions/duplicate-to/repository/types.ts
  src/packages/documents/documents/entity-bulk-actions/duplicate/duplicate.action.ts
  src/packages/documents/documents/entity-bulk-actions/manifests.ts
  src/packages/documents/documents/entity-bulk-actions/move/move.action.ts
  src/packages/property-editors/collection/config/bulk-action-permissions/permissions.element.ts
Labels: type/feature, release/14.2.0

#2126 Remove all filter option from User Status
  src/packages/user/user/collection/utils/index.ts
Labels: type/bug

#2127 Feature: Entity Bulk Action `trash` kind
  src/packages/core/entity-bulk-action/common/index.ts
  src/packages/core/entity-bulk-action/common/trash/index.ts
  src/packages/core/entity-bulk-action/common/trash/manifests.ts
  src/packages/core/entity-bulk-action/common/trash/trash-repository.interface.ts
  src/packages/core/entity-bulk-action/common/trash/trash.action.kind.ts
  src/packages/core/entity-bulk-action/common/trash/trash.action.ts
  src/packages/core/entity-bulk-action/common/trash/types.ts
  src/packages/core/entity-bulk-action/manifests.ts
  src/packages/core/extension-registry/models/entity-bulk-action.model.ts
  src/packages/media/media/entity-bulk-actions/delete/delete.action.ts
  src/packages/media/media/entity-bulk-actions/duplicate/duplicate.action.ts
  src/packages/media/media/entity-bulk-actions/manifests.ts
  src/packages/media/media/entity-bulk-actions/trash/index.ts
  src/packages/media/media/entity-bulk-actions/trash/manifests.ts
  src/packages/media/media/entity-bulk-actions/trash/repository/constants.ts
  src/packages/media/media/entity-bulk-actions/trash/repository/index.ts
  src/packages/media/media/entity-bulk-actions/trash/repository/manifests.ts
  src/packages/media/media/entity-bulk-actions/trash/repository/trash.repository.ts
  src/packages/property-editors/collection/config/bulk-action-permissions/permissions.element.ts
Labels: type/feature

#2128 Feature: Document entity bulk action "trash"
  src/packages/documents/documents/entity-bulk-actions/delete/delete.action.ts
  src/packages/documents/documents/entity-bulk-actions/manifests.ts
  src/packages/documents/documents/entity-bulk-actions/trash/index.ts
  src/packages/documents/documents/entity-bulk-actions/trash/manifests.ts
  src/packages/documents/documents/entity-bulk-actions/trash/repository/constants.ts
  src/packages/documents/documents/entity-bulk-actions/trash/repository/index.ts
  src/packages/documents/documents/entity-bulk-actions/trash/repository/manifests.ts
  src/packages/documents/documents/entity-bulk-actions/trash/repository/trash.repository.ts
Labels: type/feature, release/14.2.0

#2129 Chore: Remove the `user-defined.css` as it is not needed
  index.html
  src/css/user-defined.css
  web-test-runner.config.mjs
Labels: internal, release/14.2.0

#1227 Feature: Code Editor
  package-lock.json
  package.json
  src/apps/backoffice/backoffice.element.ts
  src/assets/lang/da-dk.ts
  src/assets/lang/en-us.ts
  src/assets/lang/en.ts
  src/mocks/data/data-type/data-type.data.ts
  src/mocks/data/document-type/document-type.data.ts
  src/mocks/data/document/document.data.ts
  src/packages/code-editor/code-editor.controller.ts
  src/packages/code-editor/components/code-editor.element.ts
  src/packages/code-editor/components/code-editor.stories.ts
  src/packages/code-editor/components/index.ts
  src/packages/code-editor/index.ts
  src/packages/code-editor/manifests.ts
  src/packages/code-editor/models/code-editor-loaded.event.ts
  src/packages/code-editor/models/code-editor.model.ts
  src/packages/code-editor/models/index.ts
  src/packages/code-editor/package.json
  src/packages/code-editor/property-editor/manifests.ts
  src/packages/code-editor/property-editor/property-editor-ui-code-editor.element.ts
  src/packages/code-editor/property-editor/property-editor-ui-code-editor.stories.ts
  src/packages/code-editor/themes/code-editor.dark.theme.ts
  src/packages/code-editor/themes/code-editor.hc-dark.theme.ts
  src/packages/code-editor/themes/code-editor.hc-light.theme.ts
  src/packages/code-editor/themes/code-editor.light.theme.ts
  src/packages/code-editor/themes/index.ts
  src/packages/code-editor/umbraco-package.ts
  src/packages/code-editor/vite.config.ts
  src/packages/markdown-editor/components/input-markdown-editor/input-markdown.element.ts
  src/packages/templating/code-editor/code-editor.stories.ts
  src/packages/templating/partial-views/workspace/partial-view-workspace-editor.element.ts
  src/packages/templating/vite.config.ts
  tsconfig.json
Labels: community/pr, type/feature, notable

#2132 Bugfix: Data Type selection for Property Editors without schema in manifests
  src/packages/data-type/workspace/data-type-workspace.context.ts
Labels: type/bug, release/14.2.0

#2137 Bugfix: Show the action button inside a button-group only if there are extensions registered
  src/packages/core/workspace/components/workspace-action-menu/workspace-action-menu.element.ts
  src/packages/core/workspace/components/workspace-action/default/workspace-action.element.ts
Labels: type/bug, storybook

#2142 build: add sonar-project.properties to account for what are sources and test files
  .github/README.md
  sonar-project.properties
Labels: ignore-for-release, internal

#2140 Chore: Bundle members package
  package-lock.json
  package.json
  src/packages/members/member-group/repository/detail/index.ts
  src/packages/members/member-group/repository/detail/member-group-detail.repository.ts
  src/packages/members/member-group/repository/detail/member-group-detail.store.context-token.ts
  src/packages/members/member-group/repository/detail/member-group-detail.store.ts
  src/packages/members/member-group/repository/item/index.ts
  src/packages/members/member-group/repository/item/member-group-item.repository.ts
  src/packages/members/member-group/repository/item/member-group-item.store.context-token.ts
  src/packages/members/member-group/repository/item/member-group-item.store.ts
  src/packages/members/member-type/repository/detail/index.ts
  src/packages/members/member-type/repository/detail/member-type-detail.repository.ts
  src/packages/members/member-type/repository/detail/member-type-detail.store.context-token.ts
  src/packages/members/member-type/repository/detail/member-type-detail.store.ts
  src/packages/members/member-type/repository/item/index.ts
  src/packages/members/member-type/repository/item/member-type-item.repository.ts
  src/packages/members/member-type/repository/item/member-type-item.store.context-token.ts
  src/packages/members/member-type/repository/item/member-type-item.store.ts
  src/packages/members/member-type/tree/index.ts
  src/packages/members/member-type/tree/member-type-tree.repository.ts
  src/packages/members/member-type/tree/member-type-tree.store.context-token.ts
  src/packages/members/member-type/tree/member-type-tree.store.ts
  src/packages/members/member/repository/detail/index.ts
  src/packages/members/member/repository/detail/member-detail.repository.ts
  src/packages/members/member/repository/detail/member-detail.store.context-token.ts
  src/packages/members/member/repository/detail/member-detail.store.ts
  src/packages/members/member/repository/item/index.ts
  src/packages/members/member/repository/item/member-item.repository.ts
  src/packages/members/member/repository/item/member-item.store.context-token.ts
  src/packages/members/member/repository/item/member-item.store.ts
  src/packages/members/member/repository/member-repository-base.ts
  src/packages/members/package.json
  src/packages/members/vite.config.ts
Labels: type/feature, release/14.2.0

#2143 build(deps): bump @umbraco-ui/uui from 1.8.2 to 1.9.0
  package-lock.json
  package.json
Labels: dependencies, javascript, release/14.2.0

#2144 Bugfix: Caret buttons in the menus have no aria-label
  src/packages/core/menu/components/menu-item-layout/menu-item-layout.element.ts
  src/packages/core/tree/tree-item/tree-item-base/tree-item-element-base.ts
Labels: type/bug

#2145 Bugfix: Crops do not show their label and invalid crops are rendered
  src/packages/media/media/components/input-image-cropper/image-cropper-field.element.ts
  src/packages/media/media/components/input-image-cropper/image-cropper-preview.element.ts
  src/packages/media/media/components/input-image-cropper/types.ts
  src/packages/media/media/components/input-rich-media/input-rich-media.element.ts
  src/packages/media/media/index.ts
  src/packages/media/media/modals/image-cropper-editor/image-cropper-editor-modal.element.ts
  src/packages/media/media/modals/image-cropper-editor/image-cropper-editor-modal.token.ts
  src/packages/media/media/property-editors/media-picker/index.ts
  src/packages/media/media/property-editors/media-picker/property-editor-ui-media-picker.element.ts
  src/packages/media/media/property-editors/types.ts
  src/packages/media/media/types.ts
Labels: type/bug, release/14.2.0

#2147 Bugfix: Enables document blueprint create menu
  src/packages/documents/documents/entity-actions/create/document-create-options-modal.element.ts
Labels: type/bug, release/14.2.0

#2148 Use the right property editor UI alias for config options
  examples/property-editor/README.md
  examples/property-editor/index.ts
  examples/property-editor/property-editor.ts
  src/assets/lang/en.ts
  src/packages/data-type/components/property-editor-config/property-editor-config.element.ts
  src/packages/data-type/workspace/data-type-workspace.context.ts
Labels: type/bug

#2152 Bugfix: Webhooks localizations + other fixes
  src/assets/lang/en.ts
  src/packages/webhook/collection/views/table/column-layouts/boolean/webhook-table-boolean-column-layout.element.ts
  src/packages/webhook/collection/views/table/column-layouts/content-type/webhook-table-name-column-layout.element.ts
  src/packages/webhook/collection/views/table/webhook-table-collection-view.element.ts
  src/packages/webhook/components/input-webhook-events.element.ts
  src/packages/webhook/components/input-webhook-headers.element.ts
  src/packages/webhook/components/webhook-events-modal/webhook-events-modal.element.ts
  src/packages/webhook/workspace/webhook-root/webhook-root-workspace.element.ts
  src/packages/webhook/workspace/webhook/views/webhook-details-workspace-view.element.ts
  src/packages/webhook/workspace/webhook/webhook-workspace-editor.element.ts
Labels: type/bug, release/14.2.0
