Repository umbraco/Umbraco.CMS.Backoffice, pull requests merged in 2024-04, with the labels that each got.

#1521 Breaking: rename Umbraco controller methods
  src/libs/class-api/class.mixin.ts
  src/libs/context-api/consume/context-consumer.controller.ts
  src/libs/context-api/provide/context-provider.controller.test.ts
  src/libs/context-api/provide/context-provider.controller.ts
  src/libs/controller-api/controller-host-element.interface.ts
  src/libs/controller-api/controller-host.interface.ts
  src/libs/controller-api/controller-host.mixin.ts
  src/libs/controller-api/controller.test.ts
  src/libs/element-api/element.mixin.ts
  src/libs/element-api/element.test.ts
  src/libs/extension-api/controller/base-extension-initializer.controller.test.ts
  src/libs/extension-api/controller/base-extension-initializer.controller.ts
  src/libs/localization-api/localization.controller.test.ts
  src/libs/localization-api/localization.controller.ts
  src/libs/observable-api/observer.controller.test.ts
  src/libs/observable-api/observer.controller.ts
  src/packages/block/block-grid/context/block-grid-entries.context.ts
  src/packages/block/block-grid/workspace/views/block-grid-type-workspace-view-settings.element.ts
  src/packages/block/block-list/context/block-list-entry.context.ts
  src/packages/block/block/context/block-entry.context.ts
  src/packages/block/block/workspace/block-workspace.context.ts
  src/packages/core/content-type/components/property-type-based-property/property-type-based-property.element.ts
  src/packages/core/content-type/structure/content-type-container-structure-helper.class.ts
  src/packages/core/content-type/structure/content-type-property-structure-helper.class.ts
  src/packages/core/content-type/workspace/views/design/content-type-design-editor-group.element.ts
  src/packages/core/section/section-sidebar-context-menu/section-sidebar-context-menu.element.ts
  src/packages/core/sorter/sorter.controller.ts
  src/packages/data-type/components/ref-data-type/ref-data-type.element.ts
  src/packages/data-type/workspace/data-type-workspace-editor.element.ts
  src/packages/documents/document-types/workspace/document-type-workspace-editor.element.ts
  src/packages/documents/document-types/workspace/document-type-workspace.context.ts
  src/packages/language/workspace/language/language-workspace.context.ts
  src/packages/media/media-types/workspace/media-type-workspace-editor.element.ts
  src/packages/members/member-type/workspace/member-type-workspace-editor.element.ts
  src/packages/packages/package/repository/server-extension.controller.ts
  src/packages/user/user-group/components/user-group-ref/user-group-ref.element.ts
Labels: storybook, category/breaking

#1497 Feature/mfa login providers
  .storybook/preview.js
  src/assets/lang/en-us.ts
  src/mocks/data/user/user.data.ts
  src/mocks/data/user/user.db.ts
  src/mocks/handlers/manifests.handlers.ts
  src/mocks/handlers/user/current.handlers.ts
  src/packages/core/extension-registry/models/index.ts
  src/packages/core/extension-registry/models/mfa-login-provider.model.ts
  src/packages/user/current-user/components/index.ts
  src/packages/user/current-user/components/mfa-provider-default.element.ts
  src/packages/user/current-user/external-login/manifests.ts
  src/packages/user/current-user/index.ts
  src/packages/user/current-user/manifests.ts
  src/packages/user/current-user/mfa-login/manifests.ts
  src/packages/user/current-user/mfa-login/mfa-providers-user-profile-app.element.ts
  src/packages/user/current-user/modals/current-user-mfa-disable-provider/current-user-mfa-disable-provider-modal.element.ts
  src/packages/user/current-user/modals/current-user-mfa-disable-provider/current-user-mfa-disable-provider-modal.stories.ts
  src/packages/user/current-user/modals/current-user-mfa-disable-provider/current-user-mfa-disable-provider-modal.token.ts
  src/packages/user/current-user/modals/current-user-mfa-enable-provider/current-user-mfa-enable-provider-modal.element.ts
  src/packages/user/current-user/modals/current-user-mfa-enable-provider/current-user-mfa-enable-provider-modal.stories.ts
  src/packages/user/current-user/modals/current-user-mfa-enable-provider/current-user-mfa-enable-provider-modal.token.ts
  src/packages/user/current-user/modals/current-user-mfa/current-user-mfa-modal.element.ts
  src/packages/user/current-user/modals/current-user-mfa/current-user-mfa-modal.stories.ts
  src/packages/user/current-user/modals/current-user-mfa/current-user-mfa-modal.token.ts
  src/packages/user/current-user/modals/manifests.ts
  src/packages/user/current-user/repository/current-user.repository.ts
  src/packages/user/current-user/repository/current-user.server.data-source.ts
  src/packages/user/current-user/repository/current-user.store.ts
  src/packages/user/current-user/types.ts
Labels: storybook, notable

#1523 Feature: Sort children Entity Action
  src/packages/core/entity-action/common/sort-children-of/manifests.ts
  src/packages/core/entity-action/common/sort-children-of/modal/constants.ts
  src/packages/core/entity-action/common/sort-children-of/modal/index.ts
  src/packages/core/entity-action/common/sort-children-of/modal/manifests.ts
  src/packages/core/entity-action/common/sort-children-of/modal/sort-children-of-modal.element.ts
  src/packages/core/entity-action/common/sort-children-of/modal/sort-children-of-modal.token.ts
  src/packages/core/entity-action/common/sort-children-of/sort-children-of.action.kind.ts
  src/packages/core/entity-action/common/sort-children-of/sort-children-of.action.ts
  src/packages/core/extension-registry/models/entity-action.model.ts
  src/packages/core/extension-registry/models/index.ts
  src/packages/core/tree/default/default-tree.context.ts
  src/packages/core/tree/folder/entity-action/create-folder/create-folder.action.ts
  src/packages/core/tree/index.ts
  src/packages/core/tree/reload-tree-item-children/index.ts
  src/packages/core/tree/tree-item/tree-item-base/tree-item-context-base.ts
  src/packages/data-type/workspace/data-type-workspace.context.ts
  src/packages/dictionary/workspace/dictionary-workspace.context.ts
  src/packages/documents/document-types/workspace/document-type-workspace.context.ts
  src/packages/documents/documents/entity-actions/index.ts
  src/packages/documents/documents/entity-actions/manifests.ts
  src/packages/documents/documents/entity-actions/sort-children-of/index.ts
  src/packages/documents/documents/entity-actions/sort-children-of/manifests.ts
  src/packages/documents/documents/entity-actions/sort-children-of/repository/constants.ts
  src/packages/documents/documents/entity-actions/sort-children-of/repository/index.ts
  src/packages/documents/documents/entity-actions/sort-children-of/repository/manifests.ts
  src/packages/documents/documents/entity-actions/sort-children-of/repository/sort-children-of.repository.ts
  src/packages/documents/documents/entity-actions/sort-children-of/repository/sort-children-of.server.data.ts
  src/packages/documents/documents/entity-actions/sort-children-of/repository/types.ts
  src/packages/documents/documents/workspace/document-workspace.context.ts
  src/packages/media/media-types/workspace/media-type-workspace.context.ts
  src/packages/media/media/workspace/media-workspace.context.ts
  src/packages/members/member-type/workspace/member-type-workspace.context.ts
  src/packages/templating/partial-views/workspace/partial-view-workspace.context.ts
  src/packages/templating/scripts/workspace/script-workspace.context.ts
  src/packages/templating/stylesheets/workspace/stylesheet-workspace.context.ts
  src/packages/templating/templates/workspace/template-workspace.context.ts
Labels: storybook

#1534 Feature/admin mfa login providers
  src/assets/lang/da-dk.ts
  src/assets/lang/en-us.ts
  src/mocks/data/user/user.data.ts
  src/mocks/data/user/user.db.ts
  src/mocks/handlers/manifests.handlers.ts
  src/mocks/handlers/user/index.ts
  src/mocks/handlers/user/mfa.handlers.ts
  src/packages/core/resources/index.ts
  src/packages/user/current-user/components/mfa-provider-default.element.ts
  src/packages/user/current-user/current-user.context.ts
  src/packages/user/current-user/modals/current-user-mfa-disable-provider/current-user-mfa-disable-provider-modal.element.ts
  src/packages/user/current-user/repository/current-user.repository.ts
  src/packages/user/current-user/repository/current-user.server.data-source.ts
  src/packages/user/current-user/repository/current-user.store.ts
  src/packages/user/current-user/types.ts
  src/packages/user/current-user/utils/is-current-user.function.ts
  src/packages/user/user/collection/repository/user-collection.server.data-source.ts
  src/packages/user/user/conditions/manifests.ts
  src/packages/user/user/conditions/user-allow-action-base.condition.ts
  src/packages/user/user/conditions/user-allow-mfa-action.condition.ts
  src/packages/user/user/entity-actions/disable/disable-user.action.ts
  src/packages/user/user/entity-actions/enable/enable-user.action.ts
  src/packages/user/user/entity-actions/manifests.ts
  src/packages/user/user/entity-actions/mfa/mfa-user.action.ts
  src/packages/user/user/entity-actions/unlock/unlock-user.action.ts
  src/packages/user/user/index.ts
  src/packages/user/user/modals/manifests.ts
  src/packages/user/user/modals/user-mfa/user-mfa-modal.element.ts
  src/packages/user/user/modals/user-mfa/user-mfa-modal.stories.ts
  src/packages/user/user/modals/user-mfa/user-mfa-modal.token.ts
  src/packages/user/user/repository/change-password/change-user-password.repository.ts
  src/packages/user/user/repository/detail/user-detail.server.data-source.ts
  src/packages/user/user/repository/sources/user-mfa.server.data-source.ts
  src/packages/user/user/repository/user.repository.ts
  src/packages/user/user/types.ts
  src/packages/user/user/utils/index.ts
  src/packages/user/user/utils/is-user.function.ts
Labels: storybook

#1555 Fixed issue in profiling dashboard leading to the checkbox always bei…
  src/packages/settings/dashboards/performance-profiling/dashboard-performance-profiling.element.ts
Labels: type/bug

#1524 Remove exports from packages/core/index.ts
  .storybook/preview.js
  src/packages/core/collection/components/collection-selection-actions.element.ts
  src/packages/core/extension-registry/models/tree-item.model.ts
  src/packages/core/index.ts
  src/packages/core/manifests.ts
  src/packages/core/workspace/components/workspace-action/default/workspace-action.element.ts
Labels: storybook, category/breaking

#1537 Feature: Media Recycle Bin
  src/packages/media/media/manifests.ts
  src/packages/media/media/recycle-bin/entity-action/manifests.ts
  src/packages/media/media/recycle-bin/entity.ts
  src/packages/media/media/recycle-bin/index.ts
  src/packages/media/media/recycle-bin/manifests.ts
  src/packages/media/media/recycle-bin/menu-item/manifests.ts
  src/packages/media/media/recycle-bin/repository/constants.ts
  src/packages/media/media/recycle-bin/repository/index.ts
  src/packages/media/media/recycle-bin/repository/manifests.ts
  src/packages/media/media/recycle-bin/repository/media-recycle-bin.repository.ts
  src/packages/media/media/recycle-bin/repository/media-recycle-bin.server.data-source.ts
  src/packages/media/media/recycle-bin/tree/constants.ts
  src/packages/media/media/recycle-bin/tree/index.ts
  src/packages/media/media/recycle-bin/tree/manifests.ts
  src/packages/media/media/recycle-bin/tree/media-recycle-bin-tree.repository.ts
  src/packages/media/media/recycle-bin/tree/media-recycle-bin-tree.server.data-source.ts
  src/packages/media/media/recycle-bin/tree/media-recycle-bin-tree.store.ts
  src/packages/media/media/recycle-bin/tree/reload-tree-item-children/manifests.ts
  src/packages/media/media/recycle-bin/tree/types.ts
Labels: storybook

#1595 Bugfix: Workspace Breadcrumb: Localizes ancestor names
  src/packages/core/workspace/components/workspace-breadcrumb/workspace-menu-breadcrumb/workspace-menu-breadcrumb.element.ts
Labels: type/bug

#1612 Bugfix: Localize section labels in picker
  src/packages/core/section/section-picker-modal/section-picker-modal.element.ts
Labels: type/bug

#1609 Bugifx: correct display of document tree item invariant name
  src/packages/documents/documents/tree/tree-item/document-tree-item.element.ts
Labels: type/bug

#1614 Bugfix: Hide variant dropdown when invariant
  src/packages/core/workspace/components/variant-selector/variant-selector.element.ts
Labels: type/bug

#1611 feature: Media Tree Item
  src/packages/media/media/tree/manifests.ts
  src/packages/media/media/tree/tree-item/media-tree-item.context.ts
  src/packages/media/media/tree/tree-item/media-tree-item.element.ts
Labels: type/feature

#1616 Bugfix: Check for tree root items
  src/packages/data-type/tree/data-type-tree.repository.ts
  src/packages/dictionary/tree/dictionary-tree.repository.ts
  src/packages/documents/document-blueprints/tree/document-blueprint-tree.repository.ts
  src/packages/documents/document-types/tree/document-type-tree.repository.ts
  src/packages/documents/documents/tree/document-tree.repository.ts
  src/packages/media/media-types/tree/media-type-tree.repository.ts
  src/packages/media/media/tree/media-tree.repository.ts
  src/packages/members/member-type/tree/member-type-tree.repository.ts
  src/packages/static-file/tree/static-file-tree.repository.ts
  src/packages/templating/partial-views/tree/partial-view-tree.repository.ts
  src/packages/templating/scripts/tree/script-tree.repository.ts
  src/packages/templating/stylesheets/tree/stylesheet-tree.repository.ts
  src/packages/templating/templates/tree/template-tree.repository.ts
Labels: type/bug

#1604 Bugfix: Date Picker story
  src/packages/core/components/input-date/input-date.stories.ts
Labels: storybook

#1622 bugfix: Add missing user group icon picker
  src/packages/user/user-group/repository/detail/user-group-detail.server.data-source.ts
  src/packages/user/user-group/workspace/user-group-workspace-editor.element.ts
Labels: type/bug

#1623 Bugfix/storybook-extensions-registry-error
  .storybook/main.ts
  package-lock.json
  package.json
  src/apps/app/app-auth.controller.ts
  src/packages/core/auth/auth.context.ts
  src/packages/core/auth/modals/umb-app-auth-modal.element.ts
Labels: storybook

#1624 Bugfix: User group add missing language permissions
  src/packages/language/components/index.ts
  src/packages/language/index.ts
  src/packages/user/user-group/workspace/user-group-workspace-editor.element.ts
Labels: type/bug

#1630 Bugfix: Remove guid in picked document
  src/packages/documents/documents/components/input-document/input-document.element.ts
Labels: type/bug

#1632 Bugfix: Logviewer: removes the `decodeURIComponent`
  src/packages/log-viewer/workspace/logviewer-workspace.context.ts
Labels: type/bug

#1633 Bugfix: Simplifies `umb-input-collection-configuration` (refactor)
  src/packages/core/components/input-collection-configuration/input-collection-configuration.element.ts
Labels: type/bug

#1634 Bugfix: ColorPicker: Regex to ensure hex color hash prefix
  src/packages/core/property-editor/uis/color-picker/property-editor-ui-color-picker.element.ts
Labels: type/bug

#1643 Chore: minor corrections for form control
  src/packages/core/components/input-number-range/input-number-range.element.ts
  src/packages/core/components/multiple-text-string-input/input-multiple-text-string.element.ts
  src/packages/core/property-editor/uis/number-range/property-editor-ui-number-range.element.ts
  src/packages/core/validation/controllers/bind-validation-message-to-form-control.controller.ts
  src/packages/core/validation/controllers/form-control-validator.controller.ts
  src/packages/core/validation/mixins/form-control.mixin.ts
Labels: storybook

#1647 Bugfix: Color Picker: default value for `useLabel` configuration
  src/packages/core/components/input-toggle/input-toggle.element.ts
  src/packages/core/components/multiple-color-picker-input/multiple-color-picker-input.element.ts
  src/packages/core/components/multiple-color-picker-input/multiple-color-picker-item-input.element.ts
  src/packages/core/property-editor/uis/color-swatches-editor/property-editor-ui-color-swatches-editor.element.ts
Labels: type/bug

#1648 Bugfix: Radio Button List: prevent triggering double 'change' event
  src/packages/core/components/input-radio-button-list/input-radio-button-list.element.ts
Labels: type/bug

#1659 Bugfix: Member Group Picker sorting
  src/packages/core/property-editor/uis/member-group-picker/property-editor-ui-member-group-picker.element.ts
  src/packages/members/member-group/components/input-member-group/input-member-group.element.ts
Labels: type/bug

#1662 Corrects "minimum" to "maximum" in the integer and decimal property editors
  src/packages/core/property-editor/schemas/Umbraco.Decimal.ts
  src/packages/core/property-editor/schemas/Umbraco.Integer.ts
Labels: community/pr, type/bug

#1676 Fixes issue with RTE query string links #1674 and ensures #1169
  src/packages/tiny-mce/plugins/tiny-mce-linkpicker.plugin.ts
Labels: community/pr, type/bug

#1679 Delete UmbInputListBaseElement
  src/packages/core/components/index.ts
  src/packages/core/components/input-list-base/index.ts
  src/packages/core/components/input-list-base/input-list-base.ts
Labels: category/breaking

#1682 Feature: Adds "multiple" feature to Dropdown property-editor UI
  src/packages/core/property-editor/uis/dropdown/property-editor-ui-dropdown.element.ts
Labels: type/feature

#1656 Feature: icons extension
  .storybook/preview.js
  devops/icons/index.js
  devops/icons/todo_implement_this_data_thesaurus.json
  src/apps/app/app.element.ts
  src/apps/backoffice/backoffice.element.ts
  src/apps/backoffice/components/backoffice-header-sections.element.ts
  src/apps/backoffice/components/backoffice-main.element.ts
  src/packages/core/extension-registry/models/icons.model.ts
  src/packages/core/extension-registry/models/index.ts
  src/packages/core/icon-registry/icon-registry.context-token.ts
  src/packages/core/icon-registry/icon-registry.context.ts
  src/packages/core/icon-registry/icon.registry.ts
  src/packages/core/icon-registry/icon.stories.ts
  src/packages/core/icon-registry/icons/icons.json
  src/packages/core/icon-registry/icons/icons.ts
  src/packages/core/icon-registry/index.ts
  src/packages/core/icon-registry/manifests.ts
  src/packages/core/icon-registry/types.ts
  src/packages/core/manifests.ts
  src/packages/core/modal/common/icon-picker/icon-picker-modal.element.ts
  src/packages/core/resources/extractUmbColorVariable.function.ts
  src/packages/core/section/section-default.element.ts
  src/packages/core/section/section-main-views/section-main-views.element.ts
Labels: storybook, notable

#1680 Feature: "Select" Property Editor UI
  src/packages/core/property-editor/schemas/Umbraco.Tags.ts
  src/packages/core/property-editor/uis/manifests.ts
  src/packages/core/property-editor/uis/select/manifests.ts
  src/packages/core/property-editor/uis/select/property-editor-ui-select.element.ts
  src/packages/core/property-editor/uis/select/property-editor-ui-select.stories.ts
  src/packages/core/property-editor/uis/select/property-editor-ui-select.test.ts
Labels: type/feature, type/bug, storybook

#1688 Feature: Add /error route
  src/apps/app/app-error.element.ts
  src/apps/app/app.element.ts
  src/assets/lang/da-dk.ts
  src/assets/lang/en-us.ts
Labels: type/feature

#1690 Fix: use setValue for setValue on modal context
  src/packages/core/modal/context/modal.context.ts
Labels: category/breaking

#1696 Bugfix: Added sorting to Collection configuration editors
  src/packages/property-editors/collection-view/config/column/column-configuration.element.ts
  src/packages/property-editors/collection-view/config/layout/layout-configuration.element.ts
Labels: type/bug

#1719 Bugfix: Remove History Item circular dependency
  .github/workflows/build_test.yml
  src/packages/core/components/history/history-item.element.ts
  src/packages/documents/documents/workspace/views/info/document-workspace-view-info-history.element.ts
  src/packages/media/media/workspace/views/info/media-workspace-view-info-history.element.ts
Labels: category/breaking

#1708 Make input-content-type-property element local
  src/packages/core/components/index.ts
  src/packages/property-editors/collection-view/config/column/column-configuration.element.ts
  src/packages/property-editors/collection-view/config/column/components/input-content-type-property/index.ts
  src/packages/property-editors/collection-view/config/column/components/input-content-type-property/input-content-type-property.element.ts
Labels: category/breaking

#1704 Only load the umb-field-dropdown-list element locally
  src/packages/core/components/index.ts
  src/packages/templating/modals/templating-page-field-builder/components/field-dropdown-list/field-dropdown-list.element.ts
  src/packages/templating/modals/templating-page-field-builder/components/field-dropdown-list/field-dropdown-list.stories.ts
  src/packages/templating/modals/templating-page-field-builder/components/field-dropdown-list/field-dropdown-list.test.ts
  src/packages/templating/modals/templating-page-field-builder/components/field-dropdown-list/index.ts
  src/packages/templating/modals/templating-page-field-builder/templating-page-field-builder-modal.element.ts
Labels: category/breaking

#1723 Adds title attribute to icons in icon picker modal - to help identify…
  src/packages/core/modal/common/icon-picker/icon-picker-modal.element.ts
Labels: community/pr, type/feature

#1710 Bugfix: Member Picker property-editor, `max` = 1
  src/packages/members/member/components/input-member/input-member.element.ts
  src/packages/members/member/property-editor/member-picker/property-editor-ui-member-picker.element.ts
  src/packages/user/user/components/user-input/user-input.element.ts
  src/packages/user/user/property-editor/user-picker/property-editor-ui-user-picker.element.ts
Labels: type/bug

#1711 Bugfix: Positive integers for min/max config
  src/packages/block/block-grid/property-editors/block-grid-editor/Umbraco.BlockGrid.ts
  src/packages/block/block-grid/property-editors/block-grid-editor/manifests.ts
  src/packages/block/block-list/property-editors/block-list-editor/Umbraco.BlockList.ts
  src/packages/core/components/input-number-range/input-number-range.element.ts
  src/packages/media/media/property-editors/image-crops-configuration/property-editor-ui-image-crops-configuration.element.ts
  src/packages/media/media/property-editors/media-picker/Umbraco.MediaPicker.ts
  src/packages/property-editors/collection-view/manifests.ts
  src/packages/property-editors/multi-url-picker/Umbraco.MultiUrlPicker.ts
  src/packages/property-editors/multiple-text-string/Umbraco.MultipleTextString.ts
  src/packages/property-editors/number-range/property-editor-ui-number-range.element.ts
  src/packages/property-editors/number/property-editor-ui-number.element.ts
  src/packages/property-editors/slider/Umbraco.Slider.ts
  src/packages/property-editors/textarea/Umbraco.TextArea.ts
  src/packages/property-editors/textarea/manifests.ts
  src/packages/property-editors/tree-picker/Umbraco.MultiNodeTreePicker.ts
  src/packages/tiny-mce/property-editors/max-image-size/property-editor-ui-tiny-mce-maximagesize-configuration.element.ts
Labels: type/bug

#1709 Bugfix: Fixed sorting of Collection configuration editors (on new data-types)
  src/packages/property-editors/collection-view/config/column/column-configuration.element.ts
  src/packages/property-editors/collection-view/config/layout/layout-configuration.element.ts
Labels: type/bug

#1712 Bugfix: Collection View default data-type configuration
  src/packages/property-editors/collection-view/manifests.ts
Labels: type/bug

#1713 Bugfix: RTE default data-type configuration
  src/packages/tiny-mce/components/input-tiny-mce/input-tiny-mce.element.ts
  src/packages/tiny-mce/property-editors/tiny-mce/manifests.ts
  src/packages/tiny-mce/property-editors/tiny-mce/property-editor-ui-tiny-mce.element.ts
Labels: type/bug

#1714 Bugfix: Data Type Details Workspace View - Picker fixes
  src/packages/data-type/workspace/views/details/data-type-details-workspace-view.element.ts
Labels: type/bug

#1722 Feat: accept tree-item-type as a generic type on the picker context
  src/packages/core/picker-input/picker-input.context.ts
  src/packages/documents/document-types/components/input-document-type/input-document-type.context.ts
  src/packages/documents/document-types/components/input-document-type/input-document-type.element.ts
  src/packages/documents/document-types/workspace/views/structure/document-type-workspace-view-structure.element.ts
Labels: type/feature

#1715 Feature: Align layout of the auth provider screen and the backend login screen
  src/apps/app/app-auth.controller.ts
  src/assets/login.jpg
  src/packages/core/auth/modals/umb-app-auth-modal.element.ts
  src/packages/core/components/backoffice-modal-container/backoffice-modal-container.element.ts
Labels: type/feature

#1728 Bugfix: Collection View Table fixes
  src/mocks/data/data-type/data-type.data.ts
  src/packages/documents/documents/collection/repository/document-collection.server.data-source.ts
  src/packages/documents/documents/collection/types.ts
  src/packages/documents/documents/collection/views/grid/document-grid-collection-view.element.ts
  src/packages/documents/documents/collection/views/index.ts
  src/packages/documents/documents/collection/views/table/column-layouts/document-table-column-name.element.ts
  src/packages/documents/documents/collection/views/table/document-table-collection-view.element.ts
  src/packages/media/media/collection/repository/media-collection.server.data-source.ts
  src/packages/media/media/collection/types.ts
  src/packages/media/media/collection/views/table/media-table-collection-view.element.ts
  src/packages/property-editors/collection/config/column/components/input-collection-content-type-property.element.ts
  src/packages/property-editors/collection/manifests.ts
  src/packages/templating/modals/templating-page-field-builder/components/template-field-dropdown-list/template-field-dropdown-list.element.ts
Labels: type/bug

#1724 Feature: Section Context Menu Context Request Proxy
  src/packages/core/components/entity-actions-bundle/entity-actions-bundle.element.ts
  src/packages/core/section/section-sidebar-context-menu/section-sidebar-context-menu.element.ts
  src/packages/core/section/section-sidebar/section-sidebar.context.ts
  src/packages/core/section/section-sidebar/types.ts
  src/packages/core/tree/tree-item/tree-item-base/tree-item-context-base.ts
Labels: category/breaking
