Repository umbraco/Umbraco.CMS.Backoffice, pull requests merged in 2024-09, with the labels that each got.

#2229 Feature: Readonly mode for Content Picker Property Editor UI
  src/packages/documents/documents/components/input-document/input-document.element.ts
  src/packages/media/media/components/input-media/input-media.element.ts
  src/packages/media/media/components/input-rich-media/input-rich-media.element.ts
  src/packages/media/media/property-editors/media-entity-picker/manifests.ts
  src/packages/media/media/property-editors/media-entity-picker/property-editor-ui-media-entity-picker.element.ts
  src/packages/members/member-group/components/input-member-group/input-member-group.element.ts
  src/packages/members/member/components/input-member/input-member.element.ts
  src/packages/multi-url-picker/components/input-multi-url/input-multi-url.element.ts
  src/packages/property-editors/content-picker/components/input-content/input-content.element.ts
  src/packages/property-editors/content-picker/manifests.ts
  src/packages/property-editors/content-picker/property-editor-ui-content-picker.element.ts
Labels: type/feature, release/14.3.0

#2235 Feature: Workspace Save, Publish, Publish With Descendants, and Schedule language permissions
  src/packages/core/utils/state-manager/state.manager.ts
  src/packages/documents/documents/modals/publish-modal/document-publish-modal.element.ts
  src/packages/documents/documents/modals/publish-with-descendants-modal/document-publish-with-descendants-modal.element.ts
  src/packages/documents/documents/modals/save-modal/document-save-modal.element.ts
  src/packages/documents/documents/modals/schedule-modal/document-schedule-modal.element.ts
  src/packages/documents/documents/modals/shared/document-variant-language-picker.element.ts
  src/packages/documents/documents/modals/types.ts
  src/packages/documents/documents/modals/unpublish-modal/document-unpublish-modal.element.ts
  src/packages/documents/documents/workspace/document-workspace.context.ts
Labels: type/feature, release/14.3.0

#2248 Feature: Readonly mode for Block List Property Editor UI
  src/packages/block/block-list/components/block-list-entry/block-list-entry.element.ts
  src/packages/block/block-list/property-editors/block-list-editor/manifests.ts
  src/packages/block/block-list/property-editors/block-list-editor/property-editor-ui-block-list.element.ts
  src/packages/block/block/workspace/block-element-property-dataset.context.ts
  src/packages/block/block/workspace/block-workspace.context.ts
Labels: type/feature, release/14.3.0

#2255 Fix: Block Grid Editor — Specified Permissions Group Rules
  src/packages/block/block-grid/context/block-grid-entries.context.ts
  src/packages/block/block-grid/workspace/block-grid-type-workspace.modal-token.ts
  src/packages/block/block/context/block-manager.context.ts
  src/packages/core/validation/mixins/form-control.mixin.ts
  src/packages/data-type/components/data-type-flow-input/data-type-flow-input.element.ts
Labels: release/14.3.0

#2257 Fix: Update dictionary's name fallback value when using it as a placeholder in `dictionaryItem_description` localization term
  src/packages/dictionary/workspace/views/workspace-view-dictionary-editor.element.ts
Labels: community/pr, type/bug, release/14.3.0

#2260 Feature: Show system information
  package.json
  src/apps/backoffice/backoffice.element.ts
  src/apps/backoffice/components/backoffice-header-logo.element.ts
  src/assets/lang/da-dk.ts
  src/assets/lang/de-de.ts
  src/assets/lang/en-us.ts
  src/assets/lang/en.ts
  src/mocks/browser-handlers.ts
  src/mocks/e2e-handlers.ts
  src/mocks/handlers/server.handlers.ts
  src/packages/core/components/code-block/code-block.element.ts
  src/packages/sysinfo/components/sysinfo.element.ts
  src/packages/sysinfo/index.ts
  src/packages/sysinfo/manifests.ts
  src/packages/sysinfo/modals/index.ts
  src/packages/sysinfo/modals/sysinfo-modal.token.ts
  src/packages/sysinfo/package.json
  src/packages/sysinfo/repository/index.ts
  src/packages/sysinfo/repository/sysinfo.repository.ts
  src/packages/sysinfo/umbraco-package.ts
  src/packages/sysinfo/vite.config.ts
  src/packages/user/current-user/current-user.context.ts
  tsconfig.json
Labels: type/feature, release/14.3.0

#2262 Feature: Member client credentials
  package.json
  src/assets/lang/da-dk.ts
  src/assets/lang/en-us.ts
  src/packages/members/member/collection/repository/member-collection.server.data-source.ts
  src/packages/members/member/collection/types.ts
  src/packages/members/member/collection/views/table/member-table-collection-view.element.ts
  src/packages/members/member/repository/detail/member-detail.server.data-source.ts
  src/packages/members/member/repository/item/member-item.server.data-source.ts
  src/packages/members/member/repository/item/types.ts
  src/packages/members/member/search/member-search.server.data-source.ts
  src/packages/members/member/types.ts
  src/packages/members/member/utils/index.ts
  src/packages/members/member/workspace/member-workspace.context.ts
  src/packages/members/member/workspace/views/member/member-workspace-view-member-info.element.ts
  src/packages/members/member/workspace/views/member/member-workspace-view-member.element.ts
  src/packages/user/user/workspace/components/user-workspace-info/user-workspace-info.element.ts
Labels: type/feature, category/breaking, release/15.0.0

#2246 Feature: UFM component filters
  src/packages/core/extension-registry/models/index.ts
  src/packages/core/extension-registry/models/ufm-filter.model.ts
  src/packages/ufm/components/content-name/content-name.component.ts
  src/packages/ufm/components/content-name/content-name.element.ts
  src/packages/ufm/components/index.ts
  src/packages/ufm/components/label-value/label-value.component.ts
  src/packages/ufm/components/label-value/label-value.element.ts
  src/packages/ufm/components/localize/localize.component.ts
  src/packages/ufm/components/localize/localize.element.ts
  src/packages/ufm/components/manifests.ts
  src/packages/ufm/components/ufm-component-base.ts
  src/packages/ufm/components/ufm-element-base.ts
  src/packages/ufm/components/ufm-render/ufm-render.context.ts
  src/packages/ufm/components/ufm-render/ufm-render.element.ts
  src/packages/ufm/contexts/index.ts
  src/packages/ufm/contexts/manifest.ts
  src/packages/ufm/contexts/ufm.context.ts
  src/packages/ufm/filters/fallback.filter.ts
  src/packages/ufm/filters/lowercase.filter.ts
  src/packages/ufm/filters/manifests.ts
  src/packages/ufm/filters/strip-html.filter.ts
  src/packages/ufm/filters/title-case.filter.ts
  src/packages/ufm/filters/truncate.filter.ts
  src/packages/ufm/filters/uppercase.filter.ts
  src/packages/ufm/filters/word-limit.filter.ts
  src/packages/ufm/index.ts
  src/packages/ufm/manifests.ts
  src/packages/ufm/plugins/index.ts
  src/packages/ufm/plugins/marked-ufm.plugin.ts
  src/packages/ufm/plugins/marked-ufm.test.ts
  src/packages/ufm/types.ts
  src/packages/ufm/ufm-components/document-name.component.ts
  src/packages/ufm/ufm-components/document-name.element.ts
  src/packages/ufm/ufm-components/label-value.component.ts
  src/packages/ufm/ufm-components/localize.component.ts
  src/packages/ufm/ufm-components/ufm-component-base.ts
Labels: type/feature, release/14.3.0

#2264 Build: Treat src/packages/* as workspaces
  package-lock.json
  package.json
  src/packages/sysinfo/components/sysinfo.element.ts
  src/packages/sysinfo/index.ts
  src/packages/sysinfo/manifests.ts
  src/packages/sysinfo/modals/sysinfo-modal.token.ts
Labels: internal, release/14.3.0

#2277 V14: Rename readonly of Property Datatsets
  src/packages/block/block-grid/components/block-grid-block-inline/block-grid-inline-property-dataset.context.ts
  src/packages/block/block/workspace/block-element-property-dataset.context.ts
  src/packages/core/content/property-dataset-context/content-property-dataset.context.ts
  src/packages/core/property/property-dataset/property-dataset-base-context.ts
  src/packages/core/property/property-dataset/property-dataset-context.interface.ts
  src/packages/core/property/property/property.context.ts
  src/packages/core/workspace/workspace-property-dataset/invariant-workspace-property-dataset-context.ts
Labels: release/14.3.0

#2274 Build: Add advanced module check
  devops/tsconfig/index.js
  examples/sorter-with-nested-containers/sorter-item.ts
  examples/sorter-with-two-containers/sorter-group.ts
  examples/sorter-with-two-containers/sorter-item.ts
  src/external/router-slot/config.ts
  src/external/router-slot/router-slot.ts
  src/external/router-slot/util/events.ts
  src/external/router-slot/util/history.ts
  src/external/router-slot/util/router.ts
  src/external/router-slot/util/shadow.ts
  src/external/router-slot/util/url.ts
  tsconfig.json
Labels: internal

#2261 Feature: Help Header App + Menu
  package-lock.json
  package.json
  src/apps/backoffice/backoffice.element.ts
  src/packages/core/extension-registry/models/index.ts
  src/packages/core/extension-registry/models/menu-item.model.ts
  src/packages/core/manifests.ts
  src/packages/core/menu/components/menu-item-layout/menu-item-layout.element.ts
  src/packages/core/menu/components/menu-item/link/link-menu-item.element.ts
  src/packages/core/menu/components/menu-item/link/manifests.ts
  src/packages/core/menu/components/menu-item/manifests.ts
  src/packages/core/menu/manifests.ts
  src/packages/help/header-app/help-header-app.element.ts
  src/packages/help/header-app/manifests.ts
  src/packages/help/index.ts
  src/packages/help/manifests.ts
  src/packages/help/menu/constants.ts
  src/packages/help/menu/index.ts
  src/packages/help/menu/manifests.ts
  src/packages/help/package.json
  src/packages/help/umbraco-package.ts
  src/packages/help/vite.config.ts
  src/packages/user/current-user/conditions/index.ts
  src/packages/user/current-user/conditions/is-admin/constants.ts
  src/packages/user/current-user/conditions/is-admin/index.ts
  src/packages/user/current-user/conditions/is-admin/is-admin.condition.manifest.ts
  src/packages/user/current-user/conditions/is-admin/is-admin.condition.ts
  src/packages/user/current-user/conditions/manifests.ts
  src/packages/user/current-user/index.ts
  src/packages/user/current-user/manifests.ts
  tsconfig.json
Labels: type/feature, release/15.0.0

#2269 Add client credential id pattern validation
  src/packages/user/user/client-credential/create/modal/create-user-client-credential-modal.element.ts
Labels: release/15.0.0

#2279 Bugfix: RTE TinyMCE data-type sorts configuration field order
  src/packages/tiny-mce/property-editors/tiny-mce/Umbraco.RichText.ts
  src/packages/tiny-mce/property-editors/tiny-mce/manifests.ts
Labels: type/bug

#2270 Feature: Version check
  src/apps/backoffice/backoffice.context.ts
  src/apps/backoffice/components/backoffice-header-logo.element.ts
  src/assets/lang/da-dk.ts
  src/assets/lang/de-de.ts
  src/assets/lang/en-us.ts
  src/assets/lang/en.ts
  src/external/backend-api/src/services.gen.ts
  src/external/backend-api/src/types.gen.ts
  src/mocks/handlers/server.handlers.ts
  src/packages/sysinfo/components/new-version.element.ts
  src/packages/sysinfo/index.ts
  src/packages/sysinfo/manifests.ts
  src/packages/sysinfo/modals/index.ts
  src/packages/sysinfo/modals/new-version-modal.token.ts
  src/packages/sysinfo/repository/sysinfo.repository.ts
  src/packages/sysinfo/types.ts
Labels: type/feature, release/14.3.0

#2282 Bugfix: Fix bug user can not login after remove ui culture of user
  src/packages/core/localization/components/ui-culture-input/ui-culture-input.element.ts
Labels: type/bug, release/14.3.0

#2249 Feature: Dynamic global extension manifest map
  examples/block-custom-view/block-custom-view.ts
  examples/block-custom-view/index.ts
  package.json
  src/libs/extension-api/models/extension-api.interface.ts
  src/libs/extension-api/models/index.ts
  src/libs/extension-api/registry/extension.registry.ts
  src/libs/extension-api/types/manifest-bundle.interface.ts
  src/packages/block/block-custom-view/block-editor-custom-view.extension.ts
  src/packages/block/block-custom-view/index.ts
  src/packages/block/block-custom-view/types.ts
  src/packages/block/block-grid/components/block-grid-block-inline/block-grid-block-inline.element.ts
  src/packages/block/block-grid/components/block-grid-block/block-grid-block.element.ts
  src/packages/block/block-grid/components/block-grid-entry/block-grid-entry.element.ts
  src/packages/block/block-list/components/block-list-entry/block-list-entry.element.ts
  src/packages/block/block-list/property-editors/block-list-editor/property-editor-ui-block-list.element.ts
  src/packages/block/block-list/property-editors/block-list-type-configuration/property-editor-ui-block-list-type-configuration.element.ts
  src/packages/block/block-list/types.ts
  src/packages/block/block-rte/components/block-rte-entry/block-rte-entry.element.ts
  src/packages/block/block-rte/tiny-mce-plugin/tiny-mce-block-picker.plugin.ts
  src/packages/block/block-rte/types.ts
  src/packages/block/block-type/components/block-type-custom-view-guide/block-type-custom-view-guide.element.ts
  src/packages/block/block-type/components/input-block-type/input-block-type.element.ts
  src/packages/block/block-type/types.ts
  src/packages/block/block-type/workspace/block-type-workspace.context.ts
  src/packages/block/block/context/block-entries.context-token.ts
  src/packages/block/block/context/block-entries.context.ts
  src/packages/block/block/context/block-entry.context-token.ts
  src/packages/block/block/context/block-entry.context.ts
  src/packages/block/block/context/block-manager.context.ts
  src/packages/block/block/index.ts
  src/packages/block/block/modals/block-catalogue/block-catalogue-modal.token.ts
  src/packages/block/block/types.ts
  src/packages/block/custom-view/custom-view.element.ts
  src/packages/block/custom-view/manifest.ts
  src/packages/block/vite.config.ts
  src/packages/core/extension-registry/interfaces/index.ts
  src/packages/core/extension-registry/models/index.ts
  src/packages/core/extension-registry/registry.ts
  src/packages/core/extension-registry/umbraco-package.ts
  src/packages/core/json-schema/umbraco-package.ts
  src/packages/tiny-mce/property-editors/block/property-editor-ui-block-rte-type-configuration.element.ts
  src/packages/user/user/manifests.ts
  tsconfig.json
  utils/json-schema/test-umbraco-package.json
Labels: type/feature, category/breaking, release/15.0.0

#2285 V15: Global condition types
  src/packages/block/block/conditions/types.ts
  src/packages/core/extension-registry/conditions/types.ts
  src/packages/core/extension-registry/models/collection-action.model.ts
  src/packages/core/extension-registry/models/collection-view.model.ts
  src/packages/core/extension-registry/models/collection.models.ts
  src/packages/core/extension-registry/models/current-user-action.model.ts
  src/packages/core/extension-registry/models/dashboard.model.ts
  src/packages/core/extension-registry/models/entity-action.model.ts
  src/packages/core/extension-registry/models/entity-bulk-action.model.ts
  src/packages/core/extension-registry/models/menu-item.model.ts
  src/packages/core/extension-registry/models/property-action.model.ts
  src/packages/core/extension-registry/models/repository.model.ts
  src/packages/core/extension-registry/models/section-sidebar-app.model.ts
  src/packages/core/extension-registry/models/section-view.model.ts
  src/packages/core/extension-registry/models/section.model.ts
  src/packages/core/extension-registry/models/tree.model.ts
  src/packages/core/extension-registry/models/workspace-action-menu-item.model.ts
  src/packages/core/extension-registry/models/workspace-action.model.ts
  src/packages/core/extension-registry/models/workspace-context.model.ts
  src/packages/core/extension-registry/models/workspace-footer-app.model.ts
  src/packages/core/extension-registry/models/workspace-view.model.ts
  src/packages/core/workspace/conditions/const.ts
  src/packages/core/workspace/conditions/index.ts
  src/packages/core/workspace/conditions/types.ts
  src/packages/core/workspace/conditions/workspace-alias.condition.ts
  src/packages/core/workspace/conditions/workspace-content-type-alias.condition.ts
  src/packages/core/workspace/conditions/workspace-entity-type.condition.ts
  src/packages/core/workspace/conditions/workspace-has-collection.condition.ts
Labels: release/15.0.0

#2290 Feature: Extension Manifest Map: Search
  src/packages/core/extension-registry/models/index.ts
  src/packages/data-type/search/manifests.ts
  src/packages/documents/document-types/search/manifests.ts
  src/packages/documents/documents/search/manifests.ts
  src/packages/media/media-types/search/manifests.ts
  src/packages/media/media/search/manifests.ts
  src/packages/members/member-type/search/manifests.ts
  src/packages/members/member/search/manifests.ts
  src/packages/search/extensions/index.ts
  src/packages/search/extensions/search-provider.extension.ts
  src/packages/search/extensions/search-result-item.extension.ts
  src/packages/search/index.ts
  src/packages/search/search-modal/search-modal.element.ts
  src/packages/templating/templates/search/manifests.ts
Labels: category/breaking, release/15.0.0

#2292 Feature: clean up block conditions
  src/packages/block/block/conditions/block-entry-show-content-edit.condition.ts
  src/packages/block/block/conditions/block-workspace-has-settings.condition.ts
  src/packages/core/extension-registry/conditions/index.ts
  src/packages/core/extension-registry/conditions/types.ts
Labels: category/breaking, release/15.0.0

#2293 Move User Permission Conditions
  src/packages/core/extension-registry/conditions/types.ts
  src/packages/core/section/conditions/section-user-permission.condition.ts
  src/packages/core/section/conditions/types.ts
  src/packages/core/section/index.ts
  src/packages/core/section/manifests.ts
  src/packages/core/section/types.ts
  src/packages/core/tree/tree-item/tree-item-base/tree-item-context-base.ts
  src/packages/documents/documents/types.ts
  src/packages/documents/documents/user-permissions/conditions/document-user-permission.condition.ts
  src/packages/documents/documents/user-permissions/conditions/manifests.ts
  src/packages/documents/documents/user-permissions/conditions/types.ts
  src/packages/documents/documents/user-permissions/manifests.ts
  src/packages/documents/documents/user-permissions/types.ts
  src/packages/documents/documents/workspace/actions/save-and-preview.action.ts
  src/packages/documents/documents/workspace/actions/save-and-publish.action.ts
  src/packages/documents/documents/workspace/actions/save.action.ts
Labels: category/breaking, release/15.0.0

#2291 move multiple language condition
  src/packages/core/extension-registry/conditions/manifests.ts
  src/packages/core/extension-registry/conditions/types.ts
  src/packages/language/conditions/multiple-app-languages.condition.ts
  src/packages/language/conditions/types.ts
  src/packages/language/manifests.ts
  src/packages/language/types.ts
Labels: category/breaking, release/15.0.0

#2294 Feature: Extension Manifest Map: Tree
  src/packages/core/extension-registry/models/index.ts
  src/packages/core/tree/default/default-tree.context.ts
  src/packages/core/tree/default/manifests.ts
  src/packages/core/tree/extensions/index.ts
  src/packages/core/tree/extensions/tree-item.extension.ts
  src/packages/core/tree/extensions/tree.extension.ts
  src/packages/core/tree/index.ts
  src/packages/core/tree/tree-item/tree-item-base/tree-item-context-base.ts
  src/packages/core/tree/tree-item/tree-item.element.ts
  src/packages/core/tree/tree.element.ts
  src/packages/data-type/tree/manifests.ts
  src/packages/dictionary/tree/manifests.ts
  src/packages/documents/document-blueprints/tree/manifests.ts
  src/packages/documents/document-types/tree/manifests.ts
  src/packages/documents/documents/recycle-bin/tree/manifests.ts
  src/packages/documents/documents/tree/manifests.ts
  src/packages/media/media-types/tree/manifests.ts
  src/packages/media/media/recycle-bin/tree/manifests.ts
  src/packages/media/media/tree/manifests.ts
  src/packages/members/member-type/tree/manifests.ts
  src/packages/static-file/tree/manifests.ts
  src/packages/templating/partial-views/tree/manifests.ts
  src/packages/templating/scripts/tree/manifests.ts
  src/packages/templating/stylesheets/tree/manifests.ts
  src/packages/templating/templates/tree/manifests.ts
Labels: category/breaking, release/15.0.0

#2295 Move section conditions to section package
  src/packages/core/extension-registry/conditions/manifests.ts
  src/packages/core/extension-registry/conditions/types.ts
  src/packages/core/section/conditions/index.ts
  src/packages/core/section/conditions/manifests.ts
  src/packages/core/section/conditions/section-alias.condition.ts
  src/packages/core/section/conditions/section-user-permission.condition.ts
  src/packages/core/section/conditions/types.ts
  src/packages/core/section/manifests.ts
Labels: category/breaking, release/15.0.0

#2288 Bugfix: Enforce Rollback permissions
  src/packages/core/icon-registry/icon-dictionary.json
  src/packages/core/icon-registry/icons.ts
  src/packages/core/icon-registry/icons/icon-history.ts
  src/packages/documents/documents/manifests.ts
  src/packages/documents/documents/modals/manifests.ts
  src/packages/documents/documents/rollback/entity-action/manifests.ts
  src/packages/documents/documents/rollback/entity-action/rollback.action.ts
  src/packages/documents/documents/rollback/index.ts
  src/packages/documents/documents/rollback/manifests.ts
  src/packages/documents/documents/rollback/modal/constants.ts
  src/packages/documents/documents/rollback/modal/index.ts
  src/packages/documents/documents/rollback/modal/manifests.ts
  src/packages/documents/documents/rollback/modal/rollback-modal.element.ts
  src/packages/documents/documents/rollback/modal/rollback-modal.token.ts
  src/packages/documents/documents/rollback/repository/index.ts
  src/packages/documents/documents/rollback/repository/manifests.ts
  src/packages/documents/documents/rollback/repository/rollback.repository.ts
  src/packages/documents/documents/rollback/repository/rollback.server.data-source.ts
  src/packages/documents/documents/workspace/constants.ts
  src/packages/documents/documents/workspace/document-workspace.context.ts
  src/packages/documents/documents/workspace/index.ts
  src/packages/documents/documents/workspace/manifests.ts
  src/packages/documents/documents/workspace/views/info/document-workspace-view-info-history.element.ts
Labels: type/bug

#2297 Feature: Members section sidebar menu
  package-lock.json
  src/packages/members/manifests.ts
  src/packages/members/member-group/entity-actions/create-member-group.action.ts
  src/packages/members/member-group/entity-actions/manifests.ts
  src/packages/members/member-group/manifests.ts
  src/packages/members/member-group/menu-item/manifests.ts
  src/packages/members/member-group/paths.ts
  src/packages/members/member-group/section-view/manifests.ts
  src/packages/members/member-group/section-view/member-group-section-view.element.ts
  src/packages/members/member-group/workspace/manifests.ts
  src/packages/members/member-group/workspace/member-group-root/manifests.ts
  src/packages/members/member-group/workspace/member-group-root/member-group-root-workspace.element.ts
  src/packages/members/member-group/workspace/member-group/index.ts
  src/packages/members/member-group/workspace/member-group/manifests.ts
  src/packages/members/member-group/workspace/member-group/member-group-workspace-editor.element.ts
  src/packages/members/member-group/workspace/member-group/member-group-workspace.context-token.ts
  src/packages/members/member-group/workspace/member-group/member-group-workspace.context.ts
  src/packages/members/member-group/workspace/member-group/views/info/member-type-workspace-view-info.element.ts
  src/packages/members/member-section/manifests.ts
  src/packages/members/member-type/tree/member-type-tree.server.data-source.ts
  src/packages/members/member/collection/views/table/member-table-collection-view.element.ts
  src/packages/members/member/collection/views/table/member-table-entity-actions-column-layout.element.ts
  src/packages/members/member/entity-actions/create/create.action.ts
  src/packages/members/member/entity-actions/create/manifests.ts
  src/packages/members/member/entity-actions/create/member-create-options-modal.element.ts
  src/packages/members/member/entity-actions/create/member-create-options-modal.token.ts
  src/packages/members/member/entity-actions/manifests.ts
  src/packages/members/member/manifests.ts
  src/packages/members/member/menu-item/manifests.ts
  src/packages/members/member/paths.ts
  src/packages/members/member/section-view/manifests.ts
  src/packages/members/member/section-view/member-section-view.element.ts
  src/packages/members/member/workspace/manifests.ts
  src/packages/members/member/workspace/member-root/manifests.ts
  src/packages/members/member/workspace/member-root/member-root-workspace.element.ts
  src/packages/members/member/workspace/member/index.ts
  src/packages/members/member/workspace/member/manifests.ts
  src/packages/members/member/workspace/member/member-workspace-editor.element.ts
  src/packages/members/member/workspace/member/member-workspace-split-view.element.ts
  src/packages/members/member/workspace/member/member-workspace.context-token.ts
  src/packages/members/member/workspace/member/member-workspace.context.ts
  src/packages/members/member/workspace/member/views/member/member-workspace-view-member-info.element.ts
  src/packages/members/member/workspace/member/views/member/member-workspace-view-member.element.ts
  src/packages/members/member/workspace/member/views/member/utils.ts
  src/packages/members/section/constants.ts
  src/packages/members/section/index.ts
  src/packages/members/section/manifests.ts
  src/packages/members/section/menu/constants.ts
  src/packages/members/section/menu/index.ts
  src/packages/members/section/menu/manifests.ts
  src/packages/members/section/paths.ts
  src/packages/members/section/sidebar-app/index.ts
  src/packages/members/section/sidebar-app/manifests.ts
Labels: type/feature, release/15.0.0

#2303 MultipleTextString: Add new line on pressing enter
  src/packages/core/components/multiple-text-string-input/input-multiple-text-string-item.element.ts
  src/packages/core/components/multiple-text-string-input/input-multiple-text-string.element.ts
Labels: type/bug

#2271 Feature: Document Notifications
  src/assets/lang/bs.ts
  src/assets/lang/cs-cz.ts
  src/assets/lang/cy-gb.ts
  src/assets/lang/da-dk.ts
  src/assets/lang/de-de.ts
  src/assets/lang/en-us.ts
  src/assets/lang/en.ts
  src/assets/lang/es-es.ts
  src/assets/lang/fr-fr.ts
  src/assets/lang/he-il.ts
  src/assets/lang/hr-hr.ts
  src/assets/lang/it-it.ts
  src/assets/lang/ja-jp.ts
  src/assets/lang/ko-kr.ts
  src/assets/lang/nb-no.ts
  src/assets/lang/nl-nl.ts
  src/assets/lang/pl-pl.ts
  src/assets/lang/pt-br.ts
  src/assets/lang/ru-ru.ts
  src/assets/lang/sv-se.ts
  src/assets/lang/tr-tr.ts
  src/assets/lang/uk-ua.ts
  src/assets/lang/zh-cn.ts
  src/assets/lang/zh-tw.ts
  src/external/backend-api/src/services.gen.ts
  src/external/backend-api/src/types.gen.ts
  src/packages/documents/documents/entity-actions/manifests.ts
  src/packages/documents/documents/entity-actions/notifications/document-notifications.action.ts
  src/packages/documents/documents/entity-actions/notifications/index.ts
  src/packages/documents/documents/entity-actions/notifications/manifests.ts
  src/packages/documents/documents/entity-actions/notifications/modal/document-notifications-modal.element.ts
  src/packages/documents/documents/entity-actions/notifications/modal/document-notifications-modal.token.ts
  src/packages/documents/documents/entity-actions/notifications/modal/index.ts
  src/packages/documents/documents/entity-actions/notifications/modal/manifests.ts
  src/packages/documents/documents/entity-actions/notifications/repository/document-notifications.repository.ts
  src/packages/documents/documents/entity-actions/notifications/repository/document-notifications.server.data.ts
  src/packages/documents/documents/entity-actions/notifications/repository/index.ts
  src/packages/documents/documents/entity-actions/notifications/repository/manifests.ts
Labels: type/feature, release/14.3.0

#2298 Bugfix: Prevent publishing of readonly cultures
  src/packages/core/utils/selection-manager/selection.manager.test.ts
  src/packages/core/utils/selection-manager/selection.manager.ts
  src/packages/documents/documents/modals/schedule-modal/document-schedule-modal.element.ts
  src/packages/documents/documents/modals/shared/document-variant-language-picker.element.ts
  src/packages/documents/documents/workspace/document-workspace.context.ts
Labels: type/bug, release/14.3.0

#2304 Feature: V14: correct workspace action padding
  src/packages/core/workspace/components/workspace-action-menu/workspace-action-menu.element.ts
Labels: type/bug, release/14.3.0

#2305 MultipleColorPicker: Tab behaviour and new line on enter
  src/packages/core/components/multiple-color-picker-input/multiple-color-picker-input.element.ts
  src/packages/core/components/multiple-color-picker-input/multiple-color-picker-item-input.element.ts
Labels: type/bug

#2306 Bugfix: add null check before passing search config
  src/packages/core/tree/tree-picker-modal/tree-picker-modal.element.ts
Labels: type/bug, release/14.3.0

#2307 Bugfix: update current user edit path to new navigation structure
  src/packages/user/current-user/profile/edit-current-user.action.ts
  src/packages/user/user/index.ts
Labels: type/bug, release/15.0.0

#2314 V14: hotfix, Validation Context polish
  src/packages/block/block-grid/property-editors/block-grid-editor/property-editor-ui-block-grid.element.ts
  src/packages/block/block-list/property-editors/block-list-editor/property-editor-ui-block-list.element.ts
  src/packages/block/block/workspace/block-element-manager.ts
  src/packages/core/property-type/workspace/property-type-workspace.context.ts
  src/packages/core/validation/context/index.ts
  src/packages/core/validation/context/server-model-validator.context-token.ts
  src/packages/core/validation/context/server-model-validator.context.ts
  src/packages/core/validation/context/validation.context-token.ts
  src/packages/core/validation/context/validation.context.ts
  src/packages/core/validation/controllers/index.ts
  src/packages/core/validation/controllers/validation.controller.ts
  src/packages/core/workspace/contexts/submittable-workspace-context-base.ts
  src/packages/data-type/workspace/data-type-workspace.context.ts
  src/packages/documents/document-types/workspace/document-type-workspace.context.ts
  src/packages/documents/documents/workspace/document-workspace.context.ts
Labels: type/feature, release/14.3.0

#2321 V15: cherry pick editor-alias changes from block variant POC
  src/external/backend-api/src/types.gen.ts
  src/mocks/data/document-blueprint/document-blueprint.data.ts
  src/mocks/data/document-blueprint/document-blueprint.db.ts
  src/mocks/data/document/document.data.ts
  src/mocks/data/document/document.db.ts
  src/mocks/data/media/media.data.ts
  src/mocks/data/media/media.db.ts
  src/mocks/data/member/member.db.ts
  src/packages/documents/document-blueprints/repository/detail/document-blueprint-detail.server.data-source.ts
  src/packages/documents/document-blueprints/workspace/document-blueprint-workspace.context.ts
  src/packages/documents/documents/repository/detail/document-detail.server.data-source.ts
  src/packages/documents/documents/workspace/document-workspace.context.ts
  src/packages/media/media/dropzone/dropzone-manager.class.ts
  src/packages/media/media/workspace/media-workspace.context.ts
  src/packages/members/member/repository/detail/member-detail.server.data-source.ts
  src/packages/members/member/workspace/member/member-workspace.context.ts
Labels: ignore-for-release

#2324 Fix: Move workspace modal token to workspace module
  src/packages/block/block-grid/components/block-grid-area-config-entry/workspace/block-grid-area-type-workspace.modal-token.ts
  src/packages/block/block-grid/workspace/block-grid-type-workspace.modal-token.ts
  src/packages/block/block-grid/workspace/block-grid-workspace.modal-token.ts
  src/packages/block/block-list/property-editors/block-list-type-configuration/property-editor-ui-block-list-type-configuration.element.ts
  src/packages/block/block-list/workspace/block-list-workspace.modal-token.ts
  src/packages/block/block-rte/workspace/block-rte-workspace.modal-token.ts
  src/packages/block/block/workspace/block-workspace.modal-token.ts
  src/packages/core/content-type/workspace/views/design/content-type-design-editor-tab.element.ts
  src/packages/core/modal/token/index.ts
  src/packages/core/property-type/workspace/property-type-workspace.modal-token.ts
  src/packages/core/tree/tree-picker-modal/tree-picker-modal.element.ts
  src/packages/core/tree/tree-picker-modal/tree-picker-modal.token.ts
  src/packages/core/workspace/modals/index.ts
  src/packages/core/workspace/modals/workspace-modal.element.ts
  src/packages/core/workspace/modals/workspace-modal.token.ts
  src/packages/data-type/workspace/data-type-workspace.modal-token.ts
  src/packages/data-type/workspace/views/info/data-type-workspace-view-info-reference.element.ts
  src/packages/documents/document-types/workspace/document-type-workspace.modal-token.ts
  src/packages/documents/documents/collection/action/create-document-collection-action.element.ts
  src/packages/documents/documents/collection/views/grid/document-grid-collection-view.element.ts
  src/packages/documents/documents/collection/views/table/document-table-collection-view.element.ts
  src/packages/documents/documents/components/input-document/input-document.element.ts
  src/packages/documents/documents/workspace/views/info/document-workspace-view-info-reference.element.ts
  src/packages/documents/documents/workspace/views/info/document-workspace-view-info.element.ts
  src/packages/language/workspace/language/language-workspace.modal-token.ts
  src/packages/media/media-types/components/input-media-type/input-media-type.element.ts
  src/packages/media/media/collection/action/create-media-collection-action.element.ts
  src/packages/media/media/collection/views/grid/media-grid-collection-view.element.ts
  src/packages/media/media/collection/views/table/media-table-collection-view.element.ts
  src/packages/media/media/components/input-media/input-media.element.ts
  src/packages/media/media/modals/image-cropper-editor/image-cropper-editor-modal.element.ts
  src/packages/media/media/workspace/views/info/media-workspace-view-info-reference.element.ts
  src/packages/media/media/workspace/views/info/media-workspace-view-info.element.ts
  src/packages/members/member-group/components/input-member-group/input-member-group.element.ts
  src/packages/members/member/components/input-member/input-member.element.ts
  src/packages/members/member/workspace/member/views/member/member-workspace-view-member-info.element.ts
  src/packages/search/examine-management-dashboard/views/section-view-examine-searchers.ts
  src/packages/templating/templates/global-components/input-template/input-template.element.ts
  src/packages/tiny-mce/property-editors/block/property-editor-ui-block-rte-type-configuration.element.ts
  src/packages/user/user-group/components/input-user-group/user-group-input.element.ts
Labels: category/breaking, release/15.0.0

#2325 Fix: move icon picker modal token
  src/packages/core/icon-registry/icon-picker-modal/icon-picker-modal.element.ts
  src/packages/core/icon-registry/icon-picker-modal/icon-picker-modal.stories.ts
  src/packages/core/icon-registry/icon-picker-modal/icon-picker-modal.test.ts
  src/packages/core/icon-registry/icon-picker-modal/icon-picker-modal.token.ts
  src/packages/core/icon-registry/icon-picker-modal/index.ts
  src/packages/core/icon-registry/icon-picker-modal/manifests.ts
  src/packages/core/icon-registry/index.ts
  src/packages/core/icon-registry/manifests.ts
  src/packages/core/modal/common/manifests.ts
  src/packages/core/modal/token/index.ts
  src/packages/documents/document-types/workspace/document-type-workspace-editor.element.ts
  src/packages/media/media-types/workspace/media-type-workspace-editor.element.ts
  src/packages/members/member-type/workspace/member-type-workspace-editor.element.ts
  src/packages/property-editors/collection/config/layout/layout-configuration.element.ts
  src/packages/property-editors/icon-picker/property-editor-ui-icon-picker.element.ts
  src/packages/property-editors/icon-picker/property-editor-ui-icon-picker.stories.ts
  src/packages/user/user-group/workspace/user-group/user-group-workspace-editor.element.ts
Labels: category/breaking, release/15.0.0

#2326 Fix: move code editor modal
  src/packages/code-editor/code-editor-modal/code-editor-modal.element.ts
  src/packages/code-editor/code-editor-modal/code-editor-modal.stories.ts
  src/packages/code-editor/code-editor-modal/code-editor-modal.token.ts
  src/packages/code-editor/code-editor-modal/index.ts
  src/packages/code-editor/code-editor-modal/manifests.ts
  src/packages/code-editor/index.ts
  src/packages/code-editor/manifests.ts
  src/packages/core/modal/common/manifests.ts
  src/packages/core/modal/token/index.ts
  src/packages/tiny-mce/plugins/tiny-mce-code-editor.plugin.ts
Labels: category/breaking, release/15.0.0

#2327 Fix: move debug modal token
  src/packages/core/debug/debug-modal/debug-modal.element.ts
  src/packages/core/debug/debug-modal/debug-modal.token.ts
  src/packages/core/debug/debug-modal/index.ts
  src/packages/core/debug/debug-modal/manifests.ts
  src/packages/core/debug/debug.element.ts
  src/packages/core/debug/index.ts
  src/packages/core/debug/manifests.ts
  src/packages/core/modal/token/index.ts
Labels: category/breaking, release/15.0.0

#2323 Feature: Entity Actions additional options
  src/packages/core/entity-action/common/delete/delete.action.kind.ts
  src/packages/core/entity-action/common/duplicate/duplicate.action.kind.ts
  src/packages/core/entity-action/default/entity-action.element.ts
  src/packages/core/extension-registry/models/entity-action.model.ts
  src/packages/core/recycle-bin/entity-action/empty-recycle-bin/empty-recycle-bin.action.kind.ts
  src/packages/core/recycle-bin/entity-action/restore-from-recycle-bin/restore-from-recycle-bin.action.kind.ts
  src/packages/core/recycle-bin/entity-action/trash/trash.action.kind.ts
  src/packages/core/tree/entity-actions/duplicate-to/duplicate-to.action.kind.ts
  src/packages/core/tree/entity-actions/move/move-to.action.kind.ts
  src/packages/core/tree/entity-actions/sort-children-of/sort-children-of.action.kind.ts
  src/packages/core/tree/folder/entity-action/create-folder/create-folder.action.kind.ts
  src/packages/core/tree/folder/entity-action/delete-folder/delete-folder.action.kind.ts
  src/packages/core/tree/folder/entity-action/update-folder/update-folder.action.kind.ts
  src/packages/data-type/entity-actions/create/manifests.ts
  src/packages/dictionary/entity-action/manifests.ts
  src/packages/documents/document-blueprints/entity-actions/create/manifests.ts
  src/packages/documents/document-types/entity-actions/create/manifests.ts
  src/packages/documents/document-types/entity-actions/export/manifests.ts
  src/packages/documents/document-types/entity-actions/import/manifests.ts
  src/packages/documents/document-types/entity-actions/manifests.ts
  src/packages/documents/documents/entity-actions/create-blueprint/manifests.ts
  src/packages/documents/documents/entity-actions/create/manifests.ts
  src/packages/documents/documents/entity-actions/culture-and-hostnames/manifests.ts
  src/packages/documents/documents/entity-actions/manifests.ts
  src/packages/documents/documents/entity-actions/notifications/manifests.ts
  src/packages/documents/documents/entity-actions/public-access/manifests.ts
  src/packages/documents/documents/entity-actions/sort-children-of/manifests.ts
  src/packages/language/entity-actions/manifests.ts
  src/packages/media/media-types/entity-actions/create/manifests.ts
  src/packages/media/media-types/entity-actions/export/manifests.ts
  src/packages/media/media-types/entity-actions/import/manifests.ts
  src/packages/media/media/entity-actions/create/manifests.ts
  src/packages/members/member-group/entity-actions/manifests.ts
  src/packages/members/member-type/entity-actions/manifests.ts
  src/packages/members/member/entity-actions/create/manifests.ts
  src/packages/templating/partial-views/entity-actions/create/manifests.ts
  src/packages/templating/scripts/entity-actions/create/manifests.ts
  src/packages/templating/stylesheets/entity-actions/create/manifests.ts
  src/packages/templating/templates/entity-actions/manifests.ts
  src/packages/user/user/entity-actions/create/manifests.ts
  src/packages/user/user/entity-actions/manifests.ts
  src/packages/user/user/invite/entity-action/invite/manifests.ts
  src/packages/user/user/invite/entity-action/resend-invite/manifests.ts
Labels: type/feature, release/15.0.0

#2330 Fix: Implement validation in 'insert field' modal
  src/packages/templating/modals/templating-page-field-builder/components/template-field-dropdown-list/template-field-dropdown-list.element.ts
  src/packages/templating/modals/templating-page-field-builder/templating-page-field-builder-modal.element.ts
Labels: type/bug, release/15.0.0

#2328 Fix: move user permission settings token
  src/packages/core/manifests.ts
  src/packages/core/modal/common/confirm/confirm-modal.controller.ts
  src/packages/core/modal/common/confirm/confirm-modal.token.ts
  src/packages/core/modal/common/confirm/index.ts
  src/packages/core/modal/common/confirm/manifests.ts
  src/packages/core/modal/common/index.ts
  src/packages/core/modal/common/item-picker/index.ts
  src/packages/core/modal/common/item-picker/item-picker-modal.token.ts
  src/packages/core/modal/common/item-picker/manifests.ts
  src/packages/core/modal/common/manifests.ts
  src/packages/core/modal/index.ts
  src/packages/core/modal/manifests.ts
  src/packages/core/modal/token/index.ts
  src/packages/documents/documents/user-permissions/input-document-granular-user-permission/input-document-granular-user-permission.element.ts
  src/packages/user/user-permission/index.ts
  src/packages/user/user-permission/modals/index.ts
  src/packages/user/user-permission/modals/manifests.ts
  src/packages/user/user-permission/modals/settings/entity-user-permission-settings-modal.element.ts
  src/packages/user/user-permission/modals/settings/entity-user-permission-settings-modal.token.ts
  src/packages/user/user-permission/modals/settings/index.ts
  src/packages/user/user-permission/modals/settings/manifests.ts
Labels: category/breaking, release/15.0.0

#2329 Fix: Move property editor UI picker modal
  src/packages/core/manifests.ts
  src/packages/core/modal/token/index.ts
  src/packages/core/property-editor/index.ts
  src/packages/core/property-editor/manifests.ts
  src/packages/core/property-editor/ui-picker-modal/index.ts
  src/packages/core/property-editor/ui-picker-modal/manifests.ts
  src/packages/core/property-editor/ui-picker-modal/property-editor-ui-picker-modal.element.ts
  src/packages/core/property-editor/ui-picker-modal/property-editor-ui-picker-modal.stories.ts
  src/packages/core/property-editor/ui-picker-modal/property-editor-ui-picker-modal.token.ts
  src/packages/data-type/modals/manifests.ts
  src/packages/data-type/workspace/views/details/data-type-details-workspace-view.element.ts
Labels: category/breaking, release/15.0.0

#2332 Feature: Embedded media package
  package-lock.json
  package.json
  src/apps/backoffice/backoffice.element.ts
  src/packages/core/modal/common/embedded-media/manifests.ts
  src/packages/core/modal/common/embedded-media/repository/index.ts
  src/packages/core/modal/common/index.ts
  src/packages/core/modal/common/manifests.ts
  src/packages/core/modal/token/index.ts
  src/packages/embedded-media/index.ts
  src/packages/embedded-media/manifests.ts
  src/packages/embedded-media/modal/embedded-media-modal.element.ts
  src/packages/embedded-media/modal/embedded-media-modal.stories.ts
  src/packages/embedded-media/modal/embedded-media-modal.token.ts
  src/packages/embedded-media/modal/index.ts
  src/packages/embedded-media/modal/manifests.ts
  src/packages/embedded-media/package.json
  src/packages/embedded-media/repository/constants.ts
  src/packages/embedded-media/repository/index.ts
  src/packages/embedded-media/repository/manifests.ts
  src/packages/embedded-media/repository/oembed.repository.ts
  src/packages/embedded-media/repository/oembed.server.data.ts
  src/packages/embedded-media/umbraco-package.ts
  src/packages/embedded-media/vite.config.ts
  src/packages/tiny-mce/plugins/tiny-mce-embeddedmedia.plugin.ts
  tsconfig.json
Labels: type/feature, category/breaking, release/15.0.0

#2333 Fix: move change password token
  package-lock.json
  package.json
  src/packages/code-editor/code-editor-modal/code-editor-modal.stories.ts
  src/packages/core/icon-registry/icon-picker-modal/icon-picker-modal.stories.ts
  src/packages/core/modal/token/index.ts
  src/packages/embedded-media/modal/embedded-media-modal.stories.ts
  src/packages/user/change-password/entity-action/change-user-password.action.ts
  src/packages/user/change-password/entity-action/manifests.ts
  src/packages/user/change-password/index.ts
  src/packages/user/change-password/manifests.ts
  src/packages/user/change-password/modal/change-password-modal.element.ts
  src/packages/user/change-password/modal/change-password-modal.token.ts
  src/packages/user/change-password/modal/index.ts
  src/packages/user/change-password/modal/manifests.ts
  src/packages/user/current-user/profile/change-password-current-user.action.ts
  src/packages/user/vite.config.ts
  tsconfig.json
Labels: category/breaking, release/15.0.0

#2340 Bugfix: No document type allowed at root message
  src/packages/documents/documents/entity-actions/create/document-create-options-modal.element.ts
Labels: type/bug

#2339 Fix: implement UmbEntityDetailWorkspaceContextBase across all non content workspaces
  src/packages/core/workspace/entity-detail/entity-detail-workspace-base.ts
  src/packages/data-type/workspace/data-type-workspace.context.ts
  src/packages/dictionary/workspace/dictionary-workspace.context.ts
  src/packages/language/workspace/language/language-workspace.context.ts
  src/packages/members/member-group/workspace/member-group/member-group-workspace.context.ts
  src/packages/templating/partial-views/workspace/partial-view-workspace.context.ts
  src/packages/templating/partial-views/workspace/partial-view-workspace.element.ts
  src/packages/templating/scripts/workspace/script-workspace.context.ts
  src/packages/templating/templates/workspace/template-workspace.context.ts
  src/packages/user/user-group/workspace/user-group/user-group-workspace.context.ts
  src/packages/webhook/workspace/webhook/webhook-workspace.context.ts
Labels: category/breaking, release/15.0.0

#2343 Feature: Unsupported properties
  src/packages/block/block/workspace/views/edit/block-workspace-view-edit-properties.element.ts
  src/packages/core/content-type/components/property-type-based-property/property-type-based-property.element.ts
  src/packages/core/property/index.ts
  src/packages/core/property/types/index.ts
  src/packages/core/property/types/unsupported-properties.type.ts
  src/packages/core/property/unsupported-property/index.ts
  src/packages/core/property/unsupported-property/unsupported-property.element.ts
  src/packages/core/property/unsupported-property/utils.ts
Labels: type/feature, release/14.3.0

#2367 Bugfix: Code Block is removing spaces
  src/packages/core/components/code-block/code-block.element.ts
  src/packages/sysinfo/components/sysinfo.element.ts
Labels: type/bug

#2363 Extension Manifest Map: dashboard
  examples/dashboard-with-property-dataset/index.ts
  examples/manifest-picker/index.ts
  examples/sorter-with-nested-containers/index.ts
  examples/sorter-with-two-containers/index.ts
  package.json
  src/packages/core/dashboard/dashboard-element.interface.ts
  src/packages/core/dashboard/dashboard.extension.ts
  src/packages/core/dashboard/index.ts
  src/packages/core/extension-registry/components/extension-slot/extension-slot.test.ts
  src/packages/core/extension-registry/interfaces/index.ts
  src/packages/core/extension-registry/models/index.ts
  src/packages/core/section/section-main-views/section-main-views.element.ts
  src/packages/core/vite.config.ts
  src/packages/umbraco-news/manifests.ts
  tsconfig.json
Labels: category/breaking, release/15.0.0

#2364 Extension Manifest Map: Health Check
  package.json
  src/packages/core/extension-registry/extensions/index.ts
  src/packages/core/extension-registry/models/index.ts
  src/packages/health-check/dashboard-health-check.element.ts
  src/packages/health-check/health-check-dashboard.context.ts
  src/packages/health-check/health-check.extension.ts
  src/packages/health-check/index.ts
  src/packages/health-check/views/health-check-group-box-overview.element.ts
  src/packages/health-check/vite.config.ts
  tsconfig.json
Labels: category/breaking, release/15.0.0

#2369 Extension Manifest Map: Markdown Editor Action
  src/packages/core/extension-registry/models/index.ts
  src/packages/markdown-editor/index.ts
  src/packages/markdown-editor/monaco-markdown-editor-action.extension.ts
Labels: category/breaking, release/15.0.0

#2372 Extension Manifest Map: Tiny MCE Plugin
  src/packages/core/extension-registry/models/index.ts
  src/packages/tiny-mce/components/input-tiny-mce/input-tiny-mce.element.ts
  src/packages/tiny-mce/index.ts
  src/packages/tiny-mce/plugins/index.ts
  src/packages/tiny-mce/plugins/manifests.ts
  src/packages/tiny-mce/plugins/tinymce-plugin.extension.ts
Labels: category/breaking, release/15.0.0

#2373 Extension Manifest Map: User Profile App + Current User Action
  src/packages/core/extension-registry/models/index.ts
  src/packages/user/current-user/action/current-user-app-button.element.ts
  src/packages/user/current-user/current-user-action.extension.ts
  src/packages/user/current-user/external-login/configure-external-login-providers-action.ts
  src/packages/user/current-user/index.ts
  src/packages/user/current-user/mfa-login/configure-mfa-providers-action.ts
  src/packages/user/current-user/profile/change-password-current-user.action.ts
  src/packages/user/current-user/profile/edit-current-user.action.ts
  src/packages/user/current-user/user-profile-app.extension.ts
Labels: category/breaking, release/15.0.0

#2376 Extension Manifest Map: Auth Provider
  src/packages/core/auth/auth-provider.extension.ts
  src/packages/core/auth/auth.context.ts
  src/packages/core/auth/components/auth-provider-default.element.ts
  src/packages/core/auth/index.ts
  src/packages/core/auth/modals/umb-app-auth-modal.element.ts
  src/packages/core/auth/providers/manifests.ts
  src/packages/core/auth/types.ts
  src/packages/core/extension-registry/extensions/external-login-provider.extension.ts
  src/packages/core/extension-registry/extensions/index.ts
  src/packages/core/extension-registry/extensions/mfa-login-provider.extension.ts
  src/packages/core/extension-registry/interfaces/external-login-provider-element.interface.ts
  src/packages/core/extension-registry/models/index.ts
Labels: category/breaking, release/15.0.0

#2351 Feature: Workspace name element
  src/packages/core/workspace/components/index.ts
  src/packages/core/workspace/components/workspace-header-name-editable/index.ts
  src/packages/core/workspace/components/workspace-header-name-editable/workspace-header-name-editable.element.ts
  src/packages/core/workspace/namable/index.ts
  src/packages/core/workspace/namable/namable-workspace-context.interface.ts
  src/packages/core/workspace/namable/namable-workspace.context-token.ts
  src/packages/data-type/tree/folder/workspace/data-type-folder-editor.element.ts
  src/packages/data-type/tree/folder/workspace/data-type-folder-workspace.context.ts
  src/packages/data-type/workspace/data-type-workspace-editor.element.ts
  src/packages/dictionary/workspace/dictionary-workspace-editor.element.ts
  src/packages/dictionary/workspace/dictionary-workspace.context.ts
  src/packages/documents/document-blueprints/tree/folder/workspace/document-blueprint-folder-editor.element.ts
  src/packages/documents/document-blueprints/tree/folder/workspace/document-blueprint-folder-workspace.context.ts
  src/packages/documents/document-types/tree/folder/workspace/document-type-folder-editor.element.ts
  src/packages/documents/document-types/tree/folder/workspace/document-type-folder-workspace.context.ts
  src/packages/language/workspace/language/language-workspace-editor.element.ts
  src/packages/language/workspace/language/language-workspace.context.ts
  src/packages/media/media-types/tree/folder/workspace/media-type-folder-editor.element.ts
  src/packages/media/media-types/tree/folder/workspace/media-type-folder-workspace.context.ts
  src/packages/members/member-group/workspace/member-group/member-group-workspace-editor.element.ts
  src/packages/templating/partial-views/tree/folder/workspace/partial-view-folder-workspace-editor.element.ts
  src/packages/templating/scripts/tree/folder/workspace/script-folder-workspace-editor.element.ts
  src/packages/templating/stylesheets/tree/folder/workspace/stylesheet-folder-workspace-editor.element.ts
  src/packages/user/user/workspace/user/user-workspace-editor.element.ts
  src/packages/user/user/workspace/user/user-workspace.context.ts
Labels: type/feature, release/15.0.0

#2379 Extension Manifest Map: Dynamic Root
  src/packages/core/extension-registry/models/index.ts
  src/packages/property-editors/content-picker/dynamic-root/components/input-content-picker-document-root.element.ts
  src/packages/property-editors/content-picker/dynamic-root/dynamic-root.extension.ts
  src/packages/property-editors/content-picker/dynamic-root/index.ts
  src/packages/property-editors/content-picker/dynamic-root/modals/dynamic-root-origin-picker-modal.element.ts
  src/packages/property-editors/content-picker/dynamic-root/modals/dynamic-root-query-step-picker-modal.element.ts
  src/packages/property-editors/content-picker/dynamic-root/modals/index.ts
Labels: category/breaking, release/15.0.0

#2381 Extension Manifest Map: File Upload Preview
  src/packages/core/extension-registry/extensions/external-login-provider-element.interface.ts
  src/packages/core/extension-registry/extensions/external-login-provider.extension.ts
  src/packages/core/extension-registry/extensions/index.ts
  src/packages/core/extension-registry/index.ts
  src/packages/core/extension-registry/interfaces/index.ts
  src/packages/core/extension-registry/models/index.ts
  src/packages/media/media/components/input-upload-field/file-upload-preview.extension.ts
  src/packages/media/media/components/input-upload-field/file-upload-preview.interface.ts
  src/packages/media/media/components/input-upload-field/index.ts
  src/packages/media/media/components/input-upload-field/input-upload-field.element.ts
Labels: category/breaking, release/15.0.0

#2316 Feature: Validate specific cultures
  src/external/backend-api/src/services.gen.ts
  src/external/backend-api/src/types.gen.ts
  src/packages/documents/documents/repository/validation/document-validation.repository.ts
  src/packages/documents/documents/repository/validation/document-validation.server.data-source.ts
  src/packages/documents/documents/workspace/document-workspace.context.ts
Labels: type/bug, release/15.0.0

#2383 Feature: Translation package
  package.json
  src/apps/backoffice/backoffice.element.ts
  src/assets/lang/en-us.ts
  src/assets/lang/en.ts
  src/packages/core/dashboard/index.ts
  src/packages/core/dashboard/paths.ts
  src/packages/dictionary/collection/views/table/dictionary-table-collection-view.element.ts
  src/packages/dictionary/dashboard/index.ts
  src/packages/dictionary/dashboard/manifests.ts
  src/packages/dictionary/dashboard/paths.ts
  src/packages/dictionary/entity-action/create/create.action.ts
  src/packages/dictionary/index.ts
  src/packages/dictionary/manifests.ts
  src/packages/dictionary/menu-item/dictionary-menu-structure.context.ts
  src/packages/dictionary/menu-item/manifests.ts
  src/packages/dictionary/menu/constants.ts
  src/packages/dictionary/menu/index.ts
  src/packages/dictionary/section/constants.ts
  src/packages/dictionary/section/index.ts
  src/packages/dictionary/section/manifests.ts
  src/packages/dictionary/workspace/dictionary-workspace-editor.element.ts
  src/packages/dictionary/workspace/index.ts
  src/packages/dictionary/workspace/paths.ts
  src/packages/translation/index.ts
  src/packages/translation/manifests.ts
  src/packages/translation/menu/constants.ts
  src/packages/translation/menu/index.ts
  src/packages/translation/menu/manifests.ts
  src/packages/translation/section/constants.ts
  src/packages/translation/section/index.ts
  src/packages/translation/section/manifests.ts
  src/packages/translation/section/paths.ts
  src/packages/translation/umbraco-package.ts
  src/packages/translation/vite.config.ts
  tsconfig.json
Labels: category/breaking, release/15.0.0
