Repository umbraco/Umbraco.CMS.Backoffice, pull requests merged in 2024-11, with the labels that each got.

#2488 15-rc: Front-end Validation for Variant Blocks
  src/packages/block/block-grid/components/block-grid-entries/block-grid-entries.element.ts
  src/packages/block/block-list/property-editors/block-list-editor/property-editor-ui-block-list.element.ts
  src/packages/block/block/validation/block-data-property-validation-path-translator.controller.ts
  src/packages/block/block/validation/block-element-data-validation-path-translator.controller.ts
  src/packages/block/block/validation/block-element-values-validation-path-translator.controller.ts
  src/packages/block/block/validation/data-path-element-data-query.function.ts
  src/packages/block/block/validation/index.ts
  src/packages/block/block/workspace/block-element-manager.ts
  src/packages/block/block/workspace/views/edit/block-workspace-view-edit-properties.element.ts
  src/packages/core/property/property/property.element.ts
  src/packages/core/validation/README.md
  src/packages/core/validation/controllers/validation.controller.ts
  src/packages/core/validation/utils/data-path-property-value-query.function.ts
  src/packages/core/validation/utils/data-path-variant-query.function.ts
  src/packages/core/validation/utils/json-path.function.ts
  src/packages/core/validation/utils/json-path.test.ts
Labels: category/breaking, release/15.0.0-rc3

#2480 Hotfix: Block Type card thunbnail image path/URL
  src/packages/block/block-type/components/block-type-card/block-type-card.element.ts
Labels: type/bug, release/15.0.0-rc3

#2500 Feature: Set the URL field as required and focus on it
  src/packages/webhook/workspace/webhook/views/webhook-details-workspace-view.element.ts
Labels: community/pr, type/bug, hacktoberfest-accepted, hacktoberfest/contrib-2024, release/15.0.0-rc3

#2510 Hotfix: UFM alias prefixes
  src/packages/ufm/components/content-name/content-name.component.ts
  src/packages/ufm/components/manifests.ts
  src/packages/ufm/contexts/ufm.context.ts
  src/packages/ufm/plugins/marked-ufm.plugin.ts
  src/packages/ufm/plugins/marked-ufm.test.ts
  src/packages/ufm/ufm-component.extension.ts
Labels: type/feature, release/15.0.0-rc3

#2501 Allow for the document create options to be opened on space/enter clicked
  src/packages/documents/documents/entity-actions/create/document-create-options-modal.element.ts
Labels: type/bug, hacktoberfest-accepted, hacktoberfest/contrib-2024, release/15.0.0-rc3

#2444 Fix for issue with multiple server-validation errors
  examples/validation-context/index.ts
  examples/validation-context/validation-context-dashboard.ts
  src/packages/core/validation/controllers/bind-server-validation-to-form-control.controller.ts
Labels: hacktoberfest-accepted

#2511 Chore: Upgraded Tiptap dependencies to 2.9.1
  package-lock.json
  package.json
Labels: dependencies, release/15.1.0

#2448 Feature: reusable table column view components
  src/packages/core/collection/components/boolean-table-column-view/boolean-table-column-view.element.ts
  src/packages/core/collection/components/index.ts
  src/packages/core/entity-action/global-components/entity-actions-table-column-view/entity-actions-table-column-view.element.ts
  src/packages/core/entity-action/global-components/index.ts
  src/packages/core/entity-action/index.ts
  src/packages/documents/documents/collection/views/table/document-table-collection-view.element.ts
  src/packages/extension-insights/collection/views/table/extension-table-collection-view.element.ts
  src/packages/extension-insights/collection/views/table/extension-table-entity-actions-column-layout.element.ts
  src/packages/language/collection/views/table/column-layouts/entity-actions/language-table-entity-actions-column-layout.element.ts
  src/packages/language/collection/views/table/language-table-collection-view.element.ts
  src/packages/media/media/collection/views/table/media-table-collection-view.element.ts
  src/packages/members/member-group/collection/views/table/member-group-table-collection-view.element.ts
  src/packages/members/member/collection/views/table/member-table-collection-view.element.ts
  src/packages/members/member/collection/views/table/member-table-entity-actions-column-layout.element.ts
  src/packages/user/user-group/collection/views/user-group-table-collection-view.element.ts
  src/packages/user/user/collection/views/table/user-table-collection-view.element.ts
  src/packages/webhook/collection/views/table/column-layouts/boolean/webhook-table-boolean-column-layout.element.ts
  src/packages/webhook/collection/views/table/column-layouts/entity-actions/webhook-table-entity-actions-column-layout.element.ts
  src/packages/webhook/collection/views/table/webhook-table-collection-view.element.ts
Labels: type/feature, release/15.1.0

#2514 Hotfix: Ensure scaffolding is done before initializing the redirect controller
  src/packages/block/block-type/workspace/block-type-workspace.context.ts
  src/packages/block/block/workspace/block-workspace.context.ts
  src/packages/core/property-type/workspace/property-type-workspace.context.ts
  src/packages/data-type/workspace/data-type-workspace.context.ts
  src/packages/dictionary/workspace/dictionary-workspace.context.ts
  src/packages/documents/document-blueprints/workspace/document-blueprint-workspace.context.ts
  src/packages/documents/document-types/workspace/document-type-workspace.context.ts
  src/packages/documents/documents/workspace/document-workspace.context.ts
  src/packages/language/workspace/language/language-workspace.context.ts
  src/packages/media/media-types/workspace/media-type-workspace.context.ts
  src/packages/media/media/workspace/media-workspace.context.ts
  src/packages/members/member-group/workspace/member-group/member-group-workspace.context.ts
  src/packages/members/member-type/workspace/member-type-workspace.context.ts
  src/packages/members/member/workspace/member/member-workspace.context.ts
  src/packages/templating/scripts/workspace/script-workspace.context.ts
  src/packages/templating/stylesheets/workspace/stylesheet-workspace.context.ts
  src/packages/templating/templates/workspace/template-workspace.context.ts
  src/packages/user/user-group/workspace/user-group/user-group-workspace.context.ts
  src/packages/webhook/workspace/webhook/webhook-workspace.context.ts
Labels: type/bug, release/15.0.0-rc4

#2512 [v14.2+] Fix Block Grid layoutStylesheet not using correct URL
  src/packages/block/block-grid/context/block-grid-manager.context.ts
Labels: type/bug, release/15.1.0

#2503 Feature: Add Swiss backoffice localizations
  src/assets/lang/de-ch.ts
  src/assets/lang/fr-ch.ts
  src/assets/lang/it-ch.ts
  src/packages/core/localization/manifests.ts
Labels: type/feature, hacktoberfest-accepted, release/15.1.0

#2518 hotfix: 17434 (prevent routable modals inside not routable modals)
  src/libs/context-api/consume/context-consumer.test.ts
  src/libs/context-api/consume/context-request.event.ts
  src/libs/context-api/provide/context-boundary.controller.ts
  src/libs/context-api/provide/context-boundary.ts
  src/libs/context-api/provide/context-provider.ts
  src/libs/context-api/provide/index.ts
  src/packages/core/modal/component/modal.element.ts
  src/packages/core/router/modal-registration/modal-route-registration.controller.ts
  src/packages/tiny-mce/components/input-tiny-mce/input-tiny-mce.defaults.ts
Labels: type/bug, release/15.0.0-rc4

#2146 Fixes with `umb-route-slot` inside routed modal
  examples/modal-routed/dashboard.element.ts
  examples/modal-routed/dashboard2.element.ts
  examples/modal-routed/index.ts
  examples/modal-routed/modal/example-modal-token.ts
  examples/modal-routed/modal/example-modal.element.ts
  examples/modal-routed/modal/steps/example-modal-step1.element.ts
  examples/modal-routed/modal/steps/example-modal-step2.element.ts
  examples/modal-routed/tabs/tab1.element.ts
  examples/modal-routed/tabs/tab2.element.ts
  src/external/router-slot/router-slot.ts
  src/packages/core/router/route.context.ts
  src/packages/core/router/router-slot.element.ts
Labels: type/bug, release/15.1.0

#2524 Bugfix: Corrects "Public access" notification typo
  src/packages/documents/documents/entity-actions/public-access/repository/public-access.repository.ts
Labels: type/bug, release/15.1.0

#2523 Bugfix: creating new doc type properties sort order doesn't count existing properties - puts it at top (+1)
  src/packages/core/content-type/workspace/views/design/content-type-design-editor-properties.element.ts
Labels: type/bug

#2521 Bugfix: Disables Link Picker modal submit button
  src/packages/multi-url-picker/link-picker-modal/link-picker-modal.element.ts
Labels: type/bug, release/15.1.0

#1507 Feature: Custom modal type
  examples/custom-modal/example-custom-modal-dashboard.element.ts
  examples/custom-modal/example-custom-modal-element.element.ts
  examples/custom-modal/example-modal-token.ts
  examples/custom-modal/example-modal-view.element.ts
  examples/custom-modal/index.ts
  examples/modal-routed/index.ts
  src/packages/core/components/backoffice-modal-container/backoffice-modal-container.element.ts
  src/packages/core/modal/component/modal.element.ts
  src/packages/core/modal/context/modal-manager.context.ts
  src/packages/core/modal/context/modal.context.ts
  src/packages/core/router/route.context.ts
Labels: type/feature, release/15.1.0

#2522 Bugfix: Tiptap Link Picker, fixes anchor with an empty URL
  src/packages/tiptap/extensions/toolbar/link.extension.ts
Labels: type/bug, release/15.1.0

#2525 Feature: Block Grid — make area create button hide on drag
  src/packages/block/block-grid/components/block-grid-areas-container/block-grid-areas-container.element.ts
  src/packages/block/block-grid/components/block-grid-entries/block-grid-entries.element.ts
  src/packages/block/block-grid/property-editors/block-grid-areas-config/property-editor-ui-block-grid-areas-config.element.ts
Labels: release/15.1.0
